// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ad-hermes-proxy.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rule struct {
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Times                *uint32  `protobuf:"varint,2,opt,name=times" json:"times,omitempty"`
	Interval             *uint64  `protobuf:"varint,3,opt,name=interval" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c1b50dd39ded022, []int{0}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Rule) GetTimes() uint32 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

func (m *Rule) GetInterval() uint64 {
	if m != nil && m.Interval != nil {
		return *m.Interval
	}
	return 0
}

type AdRequest struct {
	ClientLanguage       *string  `protobuf:"bytes,1,opt,name=client_language,json=clientLanguage" json:"client_language,omitempty"`
	Product              *string  `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Version              *uint32  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Type                 *string  `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	AvoidAds             []string `protobuf:"bytes,5,rep,name=avoidAds" json:"avoidAds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdRequest) Reset()         { *m = AdRequest{} }
func (m *AdRequest) String() string { return proto.CompactTextString(m) }
func (*AdRequest) ProtoMessage()    {}
func (*AdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c1b50dd39ded022, []int{1}
}

func (m *AdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdRequest.Unmarshal(m, b)
}
func (m *AdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdRequest.Marshal(b, m, deterministic)
}
func (m *AdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdRequest.Merge(m, src)
}
func (m *AdRequest) XXX_Size() int {
	return xxx_messageInfo_AdRequest.Size(m)
}
func (m *AdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdRequest proto.InternalMessageInfo

func (m *AdRequest) GetClientLanguage() string {
	if m != nil && m.ClientLanguage != nil {
		return *m.ClientLanguage
	}
	return ""
}

func (m *AdRequest) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *AdRequest) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AdRequest) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *AdRequest) GetAvoidAds() []string {
	if m != nil {
		return m.AvoidAds
	}
	return nil
}

type AdQueueResponse struct {
	AdQueueEntry         []*AdQueueEntry `protobuf:"bytes,1,rep,name=adQueueEntry" json:"adQueueEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AdQueueResponse) Reset()         { *m = AdQueueResponse{} }
func (m *AdQueueResponse) String() string { return proto.CompactTextString(m) }
func (*AdQueueResponse) ProtoMessage()    {}
func (*AdQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c1b50dd39ded022, []int{2}
}

func (m *AdQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdQueueResponse.Unmarshal(m, b)
}
func (m *AdQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdQueueResponse.Marshal(b, m, deterministic)
}
func (m *AdQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdQueueResponse.Merge(m, src)
}
func (m *AdQueueResponse) XXX_Size() int {
	return xxx_messageInfo_AdQueueResponse.Size(m)
}
func (m *AdQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdQueueResponse proto.InternalMessageInfo

func (m *AdQueueResponse) GetAdQueueEntry() []*AdQueueEntry {
	if m != nil {
		return m.AdQueueEntry
	}
	return nil
}

type AdFile struct {
	Id                   *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Format               *string  `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdFile) Reset()         { *m = AdFile{} }
func (m *AdFile) String() string { return proto.CompactTextString(m) }
func (*AdFile) ProtoMessage()    {}
func (*AdFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c1b50dd39ded022, []int{3}
}

func (m *AdFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdFile.Unmarshal(m, b)
}
func (m *AdFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdFile.Marshal(b, m, deterministic)
}
func (m *AdFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdFile.Merge(m, src)
}
func (m *AdFile) XXX_Size() int {
	return xxx_messageInfo_AdFile.Size(m)
}
func (m *AdFile) XXX_DiscardUnknown() {
	xxx_messageInfo_AdFile.DiscardUnknown(m)
}

var xxx_messageInfo_AdFile proto.InternalMessageInfo

func (m *AdFile) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AdFile) GetFormat() string {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return ""
}

type AdQueueEntry struct {
	StartTime            *uint64   `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime              *uint64   `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Priority             *float64  `protobuf:"fixed64,3,opt,name=priority" json:"priority,omitempty"`
	Token                *string   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	AdVersion            *uint32   `protobuf:"varint,5,opt,name=ad_version,json=adVersion" json:"ad_version,omitempty"`
	Id                   *string   `protobuf:"bytes,6,opt,name=id" json:"id,omitempty"`
	Type                 *string   `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
	Campaign             *string   `protobuf:"bytes,8,opt,name=campaign" json:"campaign,omitempty"`
	Advertiser           *string   `protobuf:"bytes,9,opt,name=advertiser" json:"advertiser,omitempty"`
	Url                  *string   `protobuf:"bytes,10,opt,name=url" json:"url,omitempty"`
	Duration             *uint64   `protobuf:"varint,11,opt,name=duration" json:"duration,omitempty"`
	Expiry               *uint64   `protobuf:"varint,12,opt,name=expiry" json:"expiry,omitempty"`
	TrackingUrl          *string   `protobuf:"bytes,13,opt,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	BannerType           *string   `protobuf:"bytes,14,opt,name=banner_type,json=bannerType" json:"banner_type,omitempty"`
	Html                 *string   `protobuf:"bytes,15,opt,name=html" json:"html,omitempty"`
	Image                *string   `protobuf:"bytes,16,opt,name=image" json:"image,omitempty"`
	BackgroundImage      *string   `protobuf:"bytes,17,opt,name=background_image,json=backgroundImage" json:"background_image,omitempty"`
	BackgroundUrl        *string   `protobuf:"bytes,18,opt,name=background_url,json=backgroundUrl" json:"background_url,omitempty"`
	BackgroundColor      *string   `protobuf:"bytes,19,opt,name=background_color,json=backgroundColor" json:"background_color,omitempty"`
	Title                *string   `protobuf:"bytes,20,opt,name=title" json:"title,omitempty"`
	Caption              *string   `protobuf:"bytes,21,opt,name=caption" json:"caption,omitempty"`
	File                 []*AdFile `protobuf:"bytes,22,rep,name=file" json:"file,omitempty"`
	Rule                 []*Rule   `protobuf:"bytes,23,rep,name=rule" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AdQueueEntry) Reset()         { *m = AdQueueEntry{} }
func (m *AdQueueEntry) String() string { return proto.CompactTextString(m) }
func (*AdQueueEntry) ProtoMessage()    {}
func (*AdQueueEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c1b50dd39ded022, []int{4}
}

func (m *AdQueueEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdQueueEntry.Unmarshal(m, b)
}
func (m *AdQueueEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdQueueEntry.Marshal(b, m, deterministic)
}
func (m *AdQueueEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdQueueEntry.Merge(m, src)
}
func (m *AdQueueEntry) XXX_Size() int {
	return xxx_messageInfo_AdQueueEntry.Size(m)
}
func (m *AdQueueEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AdQueueEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AdQueueEntry proto.InternalMessageInfo

func (m *AdQueueEntry) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *AdQueueEntry) GetEndTime() uint64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *AdQueueEntry) GetPriority() float64 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *AdQueueEntry) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *AdQueueEntry) GetAdVersion() uint32 {
	if m != nil && m.AdVersion != nil {
		return *m.AdVersion
	}
	return 0
}

func (m *AdQueueEntry) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AdQueueEntry) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *AdQueueEntry) GetCampaign() string {
	if m != nil && m.Campaign != nil {
		return *m.Campaign
	}
	return ""
}

func (m *AdQueueEntry) GetAdvertiser() string {
	if m != nil && m.Advertiser != nil {
		return *m.Advertiser
	}
	return ""
}

func (m *AdQueueEntry) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *AdQueueEntry) GetDuration() uint64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *AdQueueEntry) GetExpiry() uint64 {
	if m != nil && m.Expiry != nil {
		return *m.Expiry
	}
	return 0
}

func (m *AdQueueEntry) GetTrackingUrl() string {
	if m != nil && m.TrackingUrl != nil {
		return *m.TrackingUrl
	}
	return ""
}

func (m *AdQueueEntry) GetBannerType() string {
	if m != nil && m.BannerType != nil {
		return *m.BannerType
	}
	return ""
}

func (m *AdQueueEntry) GetHtml() string {
	if m != nil && m.Html != nil {
		return *m.Html
	}
	return ""
}

func (m *AdQueueEntry) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

func (m *AdQueueEntry) GetBackgroundImage() string {
	if m != nil && m.BackgroundImage != nil {
		return *m.BackgroundImage
	}
	return ""
}

func (m *AdQueueEntry) GetBackgroundUrl() string {
	if m != nil && m.BackgroundUrl != nil {
		return *m.BackgroundUrl
	}
	return ""
}

func (m *AdQueueEntry) GetBackgroundColor() string {
	if m != nil && m.BackgroundColor != nil {
		return *m.BackgroundColor
	}
	return ""
}

func (m *AdQueueEntry) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *AdQueueEntry) GetCaption() string {
	if m != nil && m.Caption != nil {
		return *m.Caption
	}
	return ""
}

func (m *AdQueueEntry) GetFile() []*AdFile {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *AdQueueEntry) GetRule() []*Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func init() {
	proto.RegisterType((*Rule)(nil), "spotify.Rule")
	proto.RegisterType((*AdRequest)(nil), "spotify.AdRequest")
	proto.RegisterType((*AdQueueResponse)(nil), "spotify.AdQueueResponse")
	proto.RegisterType((*AdFile)(nil), "spotify.AdFile")
	proto.RegisterType((*AdQueueEntry)(nil), "spotify.AdQueueEntry")
}

func init() { proto.RegisterFile("ad-hermes-proxy.proto", fileDescriptor_3c1b50dd39ded022) }

var fileDescriptor_3c1b50dd39ded022 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xda, 0x74, 0x6d, 0x6e, 0xbf, 0x86, 0xd9, 0x86, 0x99, 0x04, 0x74, 0x45, 0x88, 0xf2,
	0xb0, 0x09, 0xf1, 0xc6, 0x63, 0x85, 0x40, 0x42, 0xda, 0x0b, 0xd6, 0xe0, 0xb5, 0xf2, 0xe2, 0xbb,
	0xce, 0x5a, 0x62, 0x07, 0xc7, 0xa9, 0xd6, 0x7f, 0xc2, 0x33, 0xbf, 0x14, 0xd9, 0x4e, 0xb2, 0x94,
	0x37, 0x9f, 0x73, 0xae, 0x8e, 0xef, 0x3d, 0xbe, 0x86, 0x53, 0x2e, 0x2e, 0xef, 0xd1, 0xe4, 0x58,
	0x5e, 0x16, 0x46, 0x3f, 0xee, 0xaf, 0x0a, 0xa3, 0xad, 0x26, 0xc3, 0xb2, 0xd0, 0x56, 0xde, 0xed,
	0x97, 0xd7, 0x10, 0xb3, 0x2a, 0x43, 0x42, 0x20, 0xb6, 0xfb, 0x02, 0x69, 0xb4, 0x88, 0x56, 0x09,
	0xf3, 0x67, 0x72, 0x02, 0x03, 0x2b, 0x73, 0x2c, 0x69, 0x6f, 0x11, 0xad, 0xa6, 0x2c, 0x00, 0x72,
	0x0e, 0x23, 0xa9, 0x2c, 0x9a, 0x1d, 0xcf, 0x68, 0x7f, 0x11, 0xad, 0x62, 0xd6, 0xe2, 0xe5, 0x9f,
	0x08, 0x92, 0xb5, 0x60, 0xf8, 0xbb, 0xc2, 0xd2, 0x92, 0xf7, 0x30, 0x4f, 0x33, 0x89, 0xca, 0x6e,
	0x32, 0xae, 0xb6, 0x15, 0xdf, 0x36, 0xf6, 0xb3, 0x40, 0x5f, 0xd7, 0x2c, 0xa1, 0x30, 0x2c, 0x8c,
	0x16, 0x55, 0x6a, 0xfd, 0x55, 0x09, 0x6b, 0xa0, 0x53, 0x76, 0x68, 0x4a, 0xa9, 0x95, 0xbf, 0x6b,
	0xca, 0x1a, 0xd8, 0x36, 0x1c, 0x77, 0x1a, 0x3e, 0x87, 0x11, 0xdf, 0x69, 0x29, 0xd6, 0xa2, 0xa4,
	0x83, 0x45, 0x7f, 0x95, 0xb0, 0x16, 0x2f, 0xaf, 0x61, 0xbe, 0x16, 0x3f, 0x2a, 0xac, 0x90, 0x61,
	0x59, 0x68, 0x55, 0x22, 0xf9, 0x0c, 0x13, 0x1e, 0xa8, 0xaf, 0xca, 0x9a, 0x3d, 0x8d, 0x16, 0xfd,
	0xd5, 0xf8, 0xd3, 0xe9, 0x55, 0x9d, 0xcd, 0xd5, 0xba, 0x23, 0xb2, 0x83, 0xd2, 0xe5, 0x47, 0x38,
	0x5a, 0x8b, 0x6f, 0x32, 0x43, 0x32, 0x83, 0x9e, 0x14, 0xf5, 0x5c, 0x3d, 0x29, 0xc8, 0x19, 0x1c,
	0xdd, 0x69, 0x93, 0xf3, 0x66, 0x94, 0x1a, 0x2d, 0xff, 0x0e, 0x60, 0xd2, 0x35, 0x24, 0xaf, 0x00,
	0x4a, 0xcb, 0x8d, 0xdd, 0xb8, 0x58, 0xbd, 0x41, 0xcc, 0x12, 0xcf, 0xdc, 0xc8, 0x1c, 0xc9, 0x4b,
	0x18, 0xa1, 0x12, 0x41, 0xec, 0x79, 0x71, 0x88, 0x4a, 0x78, 0xe9, 0x1c, 0x46, 0x85, 0x91, 0xda,
	0x48, 0xbb, 0xf7, 0xa9, 0x44, 0xac, 0xc5, 0xfe, 0xcd, 0xf4, 0x03, 0xaa, 0x3a, 0x97, 0x00, 0xdc,
	0x5d, 0x5c, 0x6c, 0x9a, 0x24, 0x07, 0x3e, 0xc9, 0x84, 0x8b, 0x5f, 0x75, 0x96, 0x61, 0x86, 0xa3,
	0x76, 0x86, 0x26, 0xdb, 0xe1, 0x61, 0xb6, 0x29, 0xcf, 0x0b, 0x2e, 0xb7, 0x8a, 0x8e, 0x3c, 0xdf,
	0x62, 0xf2, 0xda, 0xd9, 0xef, 0xd0, 0x58, 0x59, 0xa2, 0xa1, 0x89, 0x57, 0x3b, 0x0c, 0x39, 0x86,
	0x7e, 0x65, 0x32, 0x0a, 0x5e, 0x70, 0x47, 0xe7, 0x26, 0x2a, 0xc3, 0xad, 0x6b, 0x67, 0x1c, 0x96,
	0xa8, 0xc1, 0x2e, 0x41, 0x7c, 0x2c, 0xa4, 0xd9, 0xd3, 0x89, 0x57, 0x6a, 0x44, 0x2e, 0x60, 0x62,
	0x0d, 0x4f, 0x1f, 0xa4, 0xda, 0x6e, 0x9c, 0xdd, 0xd4, 0xdb, 0x8d, 0x1b, 0xee, 0xa7, 0xc9, 0xc8,
	0x1b, 0x18, 0xdf, 0x72, 0xa5, 0xd0, 0x6c, 0x7c, 0xff, 0xb3, 0xd0, 0x49, 0xa0, 0x6e, 0xdc, 0x14,
	0x04, 0xe2, 0x7b, 0x9b, 0x67, 0x74, 0x1e, 0x26, 0x73, 0x67, 0x17, 0x99, 0xcc, 0xdd, 0x72, 0x1e,
	0x87, 0xc8, 0x3c, 0x20, 0x1f, 0xe0, 0xf8, 0x96, 0xa7, 0x0f, 0x5b, 0xa3, 0x2b, 0x25, 0x36, 0xa1,
	0xe0, 0x99, 0x2f, 0x98, 0x3f, 0xf1, 0xdf, 0x7d, 0xe9, 0x3b, 0x98, 0x75, 0x4a, 0x5d, 0x6b, 0xc4,
	0x17, 0x4e, 0x9f, 0x58, 0xd7, 0xdc, 0xa1, 0x63, 0xaa, 0x33, 0x6d, 0xe8, 0xf3, 0xff, 0x1d, 0xbf,
	0x38, 0x3a, 0xfc, 0x3c, 0x9b, 0x21, 0x3d, 0xa9, 0x5f, 0xd1, 0x01, 0xf7, 0x19, 0x52, 0x5e, 0xf8,
	0xcc, 0x4e, 0xc3, 0x37, 0xa9, 0x21, 0x79, 0x0b, 0xf1, 0x9d, 0xcc, 0x90, 0x9e, 0xf9, 0x0d, 0x9e,
	0x77, 0x36, 0xd8, 0xed, 0x28, 0xf3, 0x22, 0xb9, 0x80, 0xd8, 0x54, 0x19, 0xd2, 0x17, 0xbe, 0x68,
	0xda, 0x16, 0xb9, 0xff, 0xcf, 0xbc, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x7e, 0x7a, 0x47,
	0x2e, 0x04, 0x00, 0x00,
}
