// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticationType int32

const (
	AuthenticationType_AUTHENTICATION_USER_PASS                   AuthenticationType = 0
	AuthenticationType_AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS  AuthenticationType = 1
	AuthenticationType_AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS AuthenticationType = 2
	AuthenticationType_AUTHENTICATION_SPOTIFY_TOKEN               AuthenticationType = 3
	AuthenticationType_AUTHENTICATION_FACEBOOK_TOKEN              AuthenticationType = 4
)

var AuthenticationType_name = map[int32]string{
	0: "AUTHENTICATION_USER_PASS",
	1: "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
	2: "AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS",
	3: "AUTHENTICATION_SPOTIFY_TOKEN",
	4: "AUTHENTICATION_FACEBOOK_TOKEN",
}

var AuthenticationType_value = map[string]int32{
	"AUTHENTICATION_USER_PASS":                   0,
	"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS":  1,
	"AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS": 2,
	"AUTHENTICATION_SPOTIFY_TOKEN":               3,
	"AUTHENTICATION_FACEBOOK_TOKEN":              4,
}

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return proto.EnumName(AuthenticationType_name, int32(x))
}

func (x *AuthenticationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthenticationType_value, data, "AuthenticationType")
	if err != nil {
		return err
	}
	*x = AuthenticationType(value)
	return nil
}

func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

type AccountCreation int32

const (
	AccountCreation_ACCOUNT_CREATION_ALWAYS_PROMPT AccountCreation = 1
	AccountCreation_ACCOUNT_CREATION_ALWAYS_CREATE AccountCreation = 3
)

var AccountCreation_name = map[int32]string{
	1: "ACCOUNT_CREATION_ALWAYS_PROMPT",
	3: "ACCOUNT_CREATION_ALWAYS_CREATE",
}

var AccountCreation_value = map[string]int32{
	"ACCOUNT_CREATION_ALWAYS_PROMPT": 1,
	"ACCOUNT_CREATION_ALWAYS_CREATE": 3,
}

func (x AccountCreation) Enum() *AccountCreation {
	p := new(AccountCreation)
	*p = x
	return p
}

func (x AccountCreation) String() string {
	return proto.EnumName(AccountCreation_name, int32(x))
}

func (x *AccountCreation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountCreation_value, data, "AccountCreation")
	if err != nil {
		return err
	}
	*x = AccountCreation(value)
	return nil
}

func (AccountCreation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

type CpuFamily int32

const (
	CpuFamily_CPU_UNKNOWN  CpuFamily = 0
	CpuFamily_CPU_X86      CpuFamily = 1
	CpuFamily_CPU_X86_64   CpuFamily = 2
	CpuFamily_CPU_PPC      CpuFamily = 3
	CpuFamily_CPU_PPC_64   CpuFamily = 4
	CpuFamily_CPU_ARM      CpuFamily = 5
	CpuFamily_CPU_IA64     CpuFamily = 6
	CpuFamily_CPU_SH       CpuFamily = 7
	CpuFamily_CPU_MIPS     CpuFamily = 8
	CpuFamily_CPU_BLACKFIN CpuFamily = 9
)

var CpuFamily_name = map[int32]string{
	0: "CPU_UNKNOWN",
	1: "CPU_X86",
	2: "CPU_X86_64",
	3: "CPU_PPC",
	4: "CPU_PPC_64",
	5: "CPU_ARM",
	6: "CPU_IA64",
	7: "CPU_SH",
	8: "CPU_MIPS",
	9: "CPU_BLACKFIN",
}

var CpuFamily_value = map[string]int32{
	"CPU_UNKNOWN":  0,
	"CPU_X86":      1,
	"CPU_X86_64":   2,
	"CPU_PPC":      3,
	"CPU_PPC_64":   4,
	"CPU_ARM":      5,
	"CPU_IA64":     6,
	"CPU_SH":       7,
	"CPU_MIPS":     8,
	"CPU_BLACKFIN": 9,
}

func (x CpuFamily) Enum() *CpuFamily {
	p := new(CpuFamily)
	*p = x
	return p
}

func (x CpuFamily) String() string {
	return proto.EnumName(CpuFamily_name, int32(x))
}

func (x *CpuFamily) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CpuFamily_value, data, "CpuFamily")
	if err != nil {
		return err
	}
	*x = CpuFamily(value)
	return nil
}

func (CpuFamily) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{2}
}

type Brand int32

const (
	Brand_BRAND_UNBRANDED Brand = 0
	Brand_BRAND_INQ       Brand = 1
	Brand_BRAND_HTC       Brand = 2
	Brand_BRAND_NOKIA     Brand = 3
)

var Brand_name = map[int32]string{
	0: "BRAND_UNBRANDED",
	1: "BRAND_INQ",
	2: "BRAND_HTC",
	3: "BRAND_NOKIA",
}

var Brand_value = map[string]int32{
	"BRAND_UNBRANDED": 0,
	"BRAND_INQ":       1,
	"BRAND_HTC":       2,
	"BRAND_NOKIA":     3,
}

func (x Brand) Enum() *Brand {
	p := new(Brand)
	*p = x
	return p
}

func (x Brand) String() string {
	return proto.EnumName(Brand_name, int32(x))
}

func (x *Brand) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Brand_value, data, "Brand")
	if err != nil {
		return err
	}
	*x = Brand(value)
	return nil
}

func (Brand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{3}
}

type Os int32

const (
	Os_OS_UNKNOWN    Os = 0
	Os_OS_WINDOWS    Os = 1
	Os_OS_OSX        Os = 2
	Os_OS_IPHONE     Os = 3
	Os_OS_S60        Os = 4
	Os_OS_LINUX      Os = 5
	Os_OS_WINDOWS_CE Os = 6
	Os_OS_ANDROID    Os = 7
	Os_OS_PALM       Os = 8
	Os_OS_FREEBSD    Os = 9
	Os_OS_BLACKBERRY Os = 10
	Os_OS_SONOS      Os = 11
	Os_OS_LOGITECH   Os = 12
	Os_OS_WP7        Os = 13
	Os_OS_ONKYO      Os = 14
	Os_OS_PHILIPS    Os = 15
	Os_OS_WD         Os = 16
	Os_OS_VOLVO      Os = 17
	Os_OS_TIVO       Os = 18
	Os_OS_AWOX       Os = 19
	Os_OS_MEEGO      Os = 20
	Os_OS_QNXNTO     Os = 21
	Os_OS_BCO        Os = 22
)

var Os_name = map[int32]string{
	0:  "OS_UNKNOWN",
	1:  "OS_WINDOWS",
	2:  "OS_OSX",
	3:  "OS_IPHONE",
	4:  "OS_S60",
	5:  "OS_LINUX",
	6:  "OS_WINDOWS_CE",
	7:  "OS_ANDROID",
	8:  "OS_PALM",
	9:  "OS_FREEBSD",
	10: "OS_BLACKBERRY",
	11: "OS_SONOS",
	12: "OS_LOGITECH",
	13: "OS_WP7",
	14: "OS_ONKYO",
	15: "OS_PHILIPS",
	16: "OS_WD",
	17: "OS_VOLVO",
	18: "OS_TIVO",
	19: "OS_AWOX",
	20: "OS_MEEGO",
	21: "OS_QNXNTO",
	22: "OS_BCO",
}

var Os_value = map[string]int32{
	"OS_UNKNOWN":    0,
	"OS_WINDOWS":    1,
	"OS_OSX":        2,
	"OS_IPHONE":     3,
	"OS_S60":        4,
	"OS_LINUX":      5,
	"OS_WINDOWS_CE": 6,
	"OS_ANDROID":    7,
	"OS_PALM":       8,
	"OS_FREEBSD":    9,
	"OS_BLACKBERRY": 10,
	"OS_SONOS":      11,
	"OS_LOGITECH":   12,
	"OS_WP7":        13,
	"OS_ONKYO":      14,
	"OS_PHILIPS":    15,
	"OS_WD":         16,
	"OS_VOLVO":      17,
	"OS_TIVO":       18,
	"OS_AWOX":       19,
	"OS_MEEGO":      20,
	"OS_QNXNTO":     21,
	"OS_BCO":        22,
}

func (x Os) Enum() *Os {
	p := new(Os)
	*p = x
	return p
}

func (x Os) String() string {
	return proto.EnumName(Os_name, int32(x))
}

func (x *Os) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Os_value, data, "Os")
	if err != nil {
		return err
	}
	*x = Os(value)
	return nil
}

func (Os) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{4}
}

type AccountType int32

const (
	AccountType_Spotify  AccountType = 0
	AccountType_Facebook AccountType = 1
)

var AccountType_name = map[int32]string{
	0: "Spotify",
	1: "Facebook",
}

var AccountType_value = map[string]int32{
	"Spotify":  0,
	"Facebook": 1,
}

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (x *AccountType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountType_value, data, "AccountType")
	if err != nil {
		return err
	}
	*x = AccountType(value)
	return nil
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{5}
}

type ClientResponseEncrypted struct {
	LoginCredentials     *LoginCredentials         `protobuf:"bytes,10,req,name=login_credentials,json=loginCredentials" json:"login_credentials,omitempty"`
	AccountCreation      *AccountCreation          `protobuf:"varint,20,opt,name=account_creation,json=accountCreation,enum=spotify.AccountCreation" json:"account_creation,omitempty"`
	FingerprintResponse  *FingerprintResponseUnion `protobuf:"bytes,30,opt,name=fingerprint_response,json=fingerprintResponse" json:"fingerprint_response,omitempty"`
	PeerTicket           *PeerTicketUnion          `protobuf:"bytes,40,opt,name=peer_ticket,json=peerTicket" json:"peer_ticket,omitempty"`
	SystemInfo           *SystemInfo               `protobuf:"bytes,50,req,name=system_info,json=systemInfo" json:"system_info,omitempty"`
	PlatformModel        *string                   `protobuf:"bytes,60,opt,name=platform_model,json=platformModel" json:"platform_model,omitempty"`
	VersionString        *string                   `protobuf:"bytes,70,opt,name=version_string,json=versionString" json:"version_string,omitempty"`
	Appkey               *LibspotifyAppKey         `protobuf:"bytes,80,opt,name=appkey" json:"appkey,omitempty"`
	ClientInfo           *ClientInfo               `protobuf:"bytes,90,opt,name=client_info,json=clientInfo" json:"client_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ClientResponseEncrypted) Reset()         { *m = ClientResponseEncrypted{} }
func (m *ClientResponseEncrypted) String() string { return proto.CompactTextString(m) }
func (*ClientResponseEncrypted) ProtoMessage()    {}
func (*ClientResponseEncrypted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

func (m *ClientResponseEncrypted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponseEncrypted.Unmarshal(m, b)
}
func (m *ClientResponseEncrypted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponseEncrypted.Marshal(b, m, deterministic)
}
func (m *ClientResponseEncrypted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponseEncrypted.Merge(m, src)
}
func (m *ClientResponseEncrypted) XXX_Size() int {
	return xxx_messageInfo_ClientResponseEncrypted.Size(m)
}
func (m *ClientResponseEncrypted) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponseEncrypted.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponseEncrypted proto.InternalMessageInfo

func (m *ClientResponseEncrypted) GetLoginCredentials() *LoginCredentials {
	if m != nil {
		return m.LoginCredentials
	}
	return nil
}

func (m *ClientResponseEncrypted) GetAccountCreation() AccountCreation {
	if m != nil && m.AccountCreation != nil {
		return *m.AccountCreation
	}
	return AccountCreation_ACCOUNT_CREATION_ALWAYS_PROMPT
}

func (m *ClientResponseEncrypted) GetFingerprintResponse() *FingerprintResponseUnion {
	if m != nil {
		return m.FingerprintResponse
	}
	return nil
}

func (m *ClientResponseEncrypted) GetPeerTicket() *PeerTicketUnion {
	if m != nil {
		return m.PeerTicket
	}
	return nil
}

func (m *ClientResponseEncrypted) GetSystemInfo() *SystemInfo {
	if m != nil {
		return m.SystemInfo
	}
	return nil
}

func (m *ClientResponseEncrypted) GetPlatformModel() string {
	if m != nil && m.PlatformModel != nil {
		return *m.PlatformModel
	}
	return ""
}

func (m *ClientResponseEncrypted) GetVersionString() string {
	if m != nil && m.VersionString != nil {
		return *m.VersionString
	}
	return ""
}

func (m *ClientResponseEncrypted) GetAppkey() *LibspotifyAppKey {
	if m != nil {
		return m.Appkey
	}
	return nil
}

func (m *ClientResponseEncrypted) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type LoginCredentials struct {
	Username             *string             `protobuf:"bytes,10,opt,name=username" json:"username,omitempty"`
	Typ                  *AuthenticationType `protobuf:"varint,20,req,name=typ,enum=spotify.AuthenticationType" json:"typ,omitempty"`
	AuthData             []byte              `protobuf:"bytes,30,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoginCredentials) Reset()         { *m = LoginCredentials{} }
func (m *LoginCredentials) String() string { return proto.CompactTextString(m) }
func (*LoginCredentials) ProtoMessage()    {}
func (*LoginCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

func (m *LoginCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCredentials.Unmarshal(m, b)
}
func (m *LoginCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCredentials.Marshal(b, m, deterministic)
}
func (m *LoginCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCredentials.Merge(m, src)
}
func (m *LoginCredentials) XXX_Size() int {
	return xxx_messageInfo_LoginCredentials.Size(m)
}
func (m *LoginCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCredentials proto.InternalMessageInfo

func (m *LoginCredentials) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginCredentials) GetTyp() AuthenticationType {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return AuthenticationType_AUTHENTICATION_USER_PASS
}

func (m *LoginCredentials) GetAuthData() []byte {
	if m != nil {
		return m.AuthData
	}
	return nil
}

type FingerprintResponseUnion struct {
	Grain                *FingerprintGrainResponse      `protobuf:"bytes,10,opt,name=grain" json:"grain,omitempty"`
	HmacRipemd           *FingerprintHmacRipemdResponse `protobuf:"bytes,20,opt,name=hmac_ripemd,json=hmacRipemd" json:"hmac_ripemd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FingerprintResponseUnion) Reset()         { *m = FingerprintResponseUnion{} }
func (m *FingerprintResponseUnion) String() string { return proto.CompactTextString(m) }
func (*FingerprintResponseUnion) ProtoMessage()    {}
func (*FingerprintResponseUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{2}
}

func (m *FingerprintResponseUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerprintResponseUnion.Unmarshal(m, b)
}
func (m *FingerprintResponseUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerprintResponseUnion.Marshal(b, m, deterministic)
}
func (m *FingerprintResponseUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerprintResponseUnion.Merge(m, src)
}
func (m *FingerprintResponseUnion) XXX_Size() int {
	return xxx_messageInfo_FingerprintResponseUnion.Size(m)
}
func (m *FingerprintResponseUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerprintResponseUnion.DiscardUnknown(m)
}

var xxx_messageInfo_FingerprintResponseUnion proto.InternalMessageInfo

func (m *FingerprintResponseUnion) GetGrain() *FingerprintGrainResponse {
	if m != nil {
		return m.Grain
	}
	return nil
}

func (m *FingerprintResponseUnion) GetHmacRipemd() *FingerprintHmacRipemdResponse {
	if m != nil {
		return m.HmacRipemd
	}
	return nil
}

type FingerprintGrainResponse struct {
	EncryptedKey         []byte   `protobuf:"bytes,10,req,name=encrypted_key,json=encryptedKey" json:"encrypted_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FingerprintGrainResponse) Reset()         { *m = FingerprintGrainResponse{} }
func (m *FingerprintGrainResponse) String() string { return proto.CompactTextString(m) }
func (*FingerprintGrainResponse) ProtoMessage()    {}
func (*FingerprintGrainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{3}
}

func (m *FingerprintGrainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerprintGrainResponse.Unmarshal(m, b)
}
func (m *FingerprintGrainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerprintGrainResponse.Marshal(b, m, deterministic)
}
func (m *FingerprintGrainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerprintGrainResponse.Merge(m, src)
}
func (m *FingerprintGrainResponse) XXX_Size() int {
	return xxx_messageInfo_FingerprintGrainResponse.Size(m)
}
func (m *FingerprintGrainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerprintGrainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FingerprintGrainResponse proto.InternalMessageInfo

func (m *FingerprintGrainResponse) GetEncryptedKey() []byte {
	if m != nil {
		return m.EncryptedKey
	}
	return nil
}

type FingerprintHmacRipemdResponse struct {
	Hmac                 []byte   `protobuf:"bytes,10,req,name=hmac" json:"hmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FingerprintHmacRipemdResponse) Reset()         { *m = FingerprintHmacRipemdResponse{} }
func (m *FingerprintHmacRipemdResponse) String() string { return proto.CompactTextString(m) }
func (*FingerprintHmacRipemdResponse) ProtoMessage()    {}
func (*FingerprintHmacRipemdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{4}
}

func (m *FingerprintHmacRipemdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerprintHmacRipemdResponse.Unmarshal(m, b)
}
func (m *FingerprintHmacRipemdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerprintHmacRipemdResponse.Marshal(b, m, deterministic)
}
func (m *FingerprintHmacRipemdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerprintHmacRipemdResponse.Merge(m, src)
}
func (m *FingerprintHmacRipemdResponse) XXX_Size() int {
	return xxx_messageInfo_FingerprintHmacRipemdResponse.Size(m)
}
func (m *FingerprintHmacRipemdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerprintHmacRipemdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FingerprintHmacRipemdResponse proto.InternalMessageInfo

func (m *FingerprintHmacRipemdResponse) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

type PeerTicketUnion struct {
	PublicKey            *PeerTicketPublicKey `protobuf:"bytes,10,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	OldTicket            *PeerTicketOld       `protobuf:"bytes,20,opt,name=old_ticket,json=oldTicket" json:"old_ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PeerTicketUnion) Reset()         { *m = PeerTicketUnion{} }
func (m *PeerTicketUnion) String() string { return proto.CompactTextString(m) }
func (*PeerTicketUnion) ProtoMessage()    {}
func (*PeerTicketUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{5}
}

func (m *PeerTicketUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerTicketUnion.Unmarshal(m, b)
}
func (m *PeerTicketUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerTicketUnion.Marshal(b, m, deterministic)
}
func (m *PeerTicketUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerTicketUnion.Merge(m, src)
}
func (m *PeerTicketUnion) XXX_Size() int {
	return xxx_messageInfo_PeerTicketUnion.Size(m)
}
func (m *PeerTicketUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerTicketUnion.DiscardUnknown(m)
}

var xxx_messageInfo_PeerTicketUnion proto.InternalMessageInfo

func (m *PeerTicketUnion) GetPublicKey() *PeerTicketPublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeerTicketUnion) GetOldTicket() *PeerTicketOld {
	if m != nil {
		return m.OldTicket
	}
	return nil
}

type PeerTicketPublicKey struct {
	PublicKey            []byte   `protobuf:"bytes,10,req,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerTicketPublicKey) Reset()         { *m = PeerTicketPublicKey{} }
func (m *PeerTicketPublicKey) String() string { return proto.CompactTextString(m) }
func (*PeerTicketPublicKey) ProtoMessage()    {}
func (*PeerTicketPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{6}
}

func (m *PeerTicketPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerTicketPublicKey.Unmarshal(m, b)
}
func (m *PeerTicketPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerTicketPublicKey.Marshal(b, m, deterministic)
}
func (m *PeerTicketPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerTicketPublicKey.Merge(m, src)
}
func (m *PeerTicketPublicKey) XXX_Size() int {
	return xxx_messageInfo_PeerTicketPublicKey.Size(m)
}
func (m *PeerTicketPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerTicketPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PeerTicketPublicKey proto.InternalMessageInfo

func (m *PeerTicketPublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type PeerTicketOld struct {
	PeerTicket           []byte   `protobuf:"bytes,10,req,name=peer_ticket,json=peerTicket" json:"peer_ticket,omitempty"`
	PeerTicketSignature  []byte   `protobuf:"bytes,20,req,name=peer_ticket_signature,json=peerTicketSignature" json:"peer_ticket_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerTicketOld) Reset()         { *m = PeerTicketOld{} }
func (m *PeerTicketOld) String() string { return proto.CompactTextString(m) }
func (*PeerTicketOld) ProtoMessage()    {}
func (*PeerTicketOld) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{7}
}

func (m *PeerTicketOld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerTicketOld.Unmarshal(m, b)
}
func (m *PeerTicketOld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerTicketOld.Marshal(b, m, deterministic)
}
func (m *PeerTicketOld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerTicketOld.Merge(m, src)
}
func (m *PeerTicketOld) XXX_Size() int {
	return xxx_messageInfo_PeerTicketOld.Size(m)
}
func (m *PeerTicketOld) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerTicketOld.DiscardUnknown(m)
}

var xxx_messageInfo_PeerTicketOld proto.InternalMessageInfo

func (m *PeerTicketOld) GetPeerTicket() []byte {
	if m != nil {
		return m.PeerTicket
	}
	return nil
}

func (m *PeerTicketOld) GetPeerTicketSignature() []byte {
	if m != nil {
		return m.PeerTicketSignature
	}
	return nil
}

type SystemInfo struct {
	CpuFamily               *CpuFamily `protobuf:"varint,10,req,name=cpu_family,json=cpuFamily,enum=spotify.CpuFamily" json:"cpu_family,omitempty"`
	CpuSubtype              *uint32    `protobuf:"varint,20,opt,name=cpu_subtype,json=cpuSubtype" json:"cpu_subtype,omitempty"`
	CpuExt                  *uint32    `protobuf:"varint,30,opt,name=cpu_ext,json=cpuExt" json:"cpu_ext,omitempty"`
	Brand                   *Brand     `protobuf:"varint,40,opt,name=brand,enum=spotify.Brand" json:"brand,omitempty"`
	BrandFlags              *uint32    `protobuf:"varint,50,opt,name=brand_flags,json=brandFlags" json:"brand_flags,omitempty"`
	Os                      *Os        `protobuf:"varint,60,req,name=os,enum=spotify.Os" json:"os,omitempty"`
	OsVersion               *uint32    `protobuf:"varint,70,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	OsExt                   *uint32    `protobuf:"varint,80,opt,name=os_ext,json=osExt" json:"os_ext,omitempty"`
	SystemInformationString *string    `protobuf:"bytes,90,opt,name=system_information_string,json=systemInformationString" json:"system_information_string,omitempty"`
	DeviceId                *string    `protobuf:"bytes,100,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}   `json:"-"`
	XXX_unrecognized        []byte     `json:"-"`
	XXX_sizecache           int32      `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{8}
}

func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (m *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(m, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetCpuFamily() CpuFamily {
	if m != nil && m.CpuFamily != nil {
		return *m.CpuFamily
	}
	return CpuFamily_CPU_UNKNOWN
}

func (m *SystemInfo) GetCpuSubtype() uint32 {
	if m != nil && m.CpuSubtype != nil {
		return *m.CpuSubtype
	}
	return 0
}

func (m *SystemInfo) GetCpuExt() uint32 {
	if m != nil && m.CpuExt != nil {
		return *m.CpuExt
	}
	return 0
}

func (m *SystemInfo) GetBrand() Brand {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return Brand_BRAND_UNBRANDED
}

func (m *SystemInfo) GetBrandFlags() uint32 {
	if m != nil && m.BrandFlags != nil {
		return *m.BrandFlags
	}
	return 0
}

func (m *SystemInfo) GetOs() Os {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return Os_OS_UNKNOWN
}

func (m *SystemInfo) GetOsVersion() uint32 {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return 0
}

func (m *SystemInfo) GetOsExt() uint32 {
	if m != nil && m.OsExt != nil {
		return *m.OsExt
	}
	return 0
}

func (m *SystemInfo) GetSystemInformationString() string {
	if m != nil && m.SystemInformationString != nil {
		return *m.SystemInformationString
	}
	return ""
}

func (m *SystemInfo) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

type LibspotifyAppKey struct {
	Version              *uint32  `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Devkey               []byte   `protobuf:"bytes,2,req,name=devkey" json:"devkey,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	Useragent            *string  `protobuf:"bytes,4,req,name=useragent" json:"useragent,omitempty"`
	CallbackHash         []byte   `protobuf:"bytes,5,req,name=callback_hash,json=callbackHash" json:"callback_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibspotifyAppKey) Reset()         { *m = LibspotifyAppKey{} }
func (m *LibspotifyAppKey) String() string { return proto.CompactTextString(m) }
func (*LibspotifyAppKey) ProtoMessage()    {}
func (*LibspotifyAppKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{9}
}

func (m *LibspotifyAppKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibspotifyAppKey.Unmarshal(m, b)
}
func (m *LibspotifyAppKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibspotifyAppKey.Marshal(b, m, deterministic)
}
func (m *LibspotifyAppKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibspotifyAppKey.Merge(m, src)
}
func (m *LibspotifyAppKey) XXX_Size() int {
	return xxx_messageInfo_LibspotifyAppKey.Size(m)
}
func (m *LibspotifyAppKey) XXX_DiscardUnknown() {
	xxx_messageInfo_LibspotifyAppKey.DiscardUnknown(m)
}

var xxx_messageInfo_LibspotifyAppKey proto.InternalMessageInfo

func (m *LibspotifyAppKey) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *LibspotifyAppKey) GetDevkey() []byte {
	if m != nil {
		return m.Devkey
	}
	return nil
}

func (m *LibspotifyAppKey) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *LibspotifyAppKey) GetUseragent() string {
	if m != nil && m.Useragent != nil {
		return *m.Useragent
	}
	return ""
}

func (m *LibspotifyAppKey) GetCallbackHash() []byte {
	if m != nil {
		return m.CallbackHash
	}
	return nil
}

type ClientInfo struct {
	Limited              *bool               `protobuf:"varint,1,opt,name=limited" json:"limited,omitempty"`
	Fb                   *ClientInfoFacebook `protobuf:"bytes,2,opt,name=fb" json:"fb,omitempty"`
	Language             *string             `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{10}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetLimited() bool {
	if m != nil && m.Limited != nil {
		return *m.Limited
	}
	return false
}

func (m *ClientInfo) GetFb() *ClientInfoFacebook {
	if m != nil {
		return m.Fb
	}
	return nil
}

func (m *ClientInfo) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

type ClientInfoFacebook struct {
	MachineId            *string  `protobuf:"bytes,1,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfoFacebook) Reset()         { *m = ClientInfoFacebook{} }
func (m *ClientInfoFacebook) String() string { return proto.CompactTextString(m) }
func (*ClientInfoFacebook) ProtoMessage()    {}
func (*ClientInfoFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{11}
}

func (m *ClientInfoFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfoFacebook.Unmarshal(m, b)
}
func (m *ClientInfoFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfoFacebook.Marshal(b, m, deterministic)
}
func (m *ClientInfoFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfoFacebook.Merge(m, src)
}
func (m *ClientInfoFacebook) XXX_Size() int {
	return xxx_messageInfo_ClientInfoFacebook.Size(m)
}
func (m *ClientInfoFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfoFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfoFacebook proto.InternalMessageInfo

func (m *ClientInfoFacebook) GetMachineId() string {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return ""
}

type APWelcome struct {
	CanonicalUsername           *string              `protobuf:"bytes,10,req,name=canonical_username,json=canonicalUsername" json:"canonical_username,omitempty"`
	AccountTypeLoggedIn         *AccountType         `protobuf:"varint,20,req,name=account_type_logged_in,json=accountTypeLoggedIn,enum=spotify.AccountType" json:"account_type_logged_in,omitempty"`
	CredentialsTypeLoggedIn     *AccountType         `protobuf:"varint,25,req,name=credentials_type_logged_in,json=credentialsTypeLoggedIn,enum=spotify.AccountType" json:"credentials_type_logged_in,omitempty"`
	ReusableAuthCredentialsType *AuthenticationType  `protobuf:"varint,30,req,name=reusable_auth_credentials_type,json=reusableAuthCredentialsType,enum=spotify.AuthenticationType" json:"reusable_auth_credentials_type,omitempty"`
	ReusableAuthCredentials     []byte               `protobuf:"bytes,40,req,name=reusable_auth_credentials,json=reusableAuthCredentials" json:"reusable_auth_credentials,omitempty"`
	LfsSecret                   []byte               `protobuf:"bytes,50,opt,name=lfs_secret,json=lfsSecret" json:"lfs_secret,omitempty"`
	AccountInfo                 *AccountInfo         `protobuf:"bytes,60,opt,name=account_info,json=accountInfo" json:"account_info,omitempty"`
	Fb                          *AccountInfoFacebook `protobuf:"bytes,70,opt,name=fb" json:"fb,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}             `json:"-"`
	XXX_unrecognized            []byte               `json:"-"`
	XXX_sizecache               int32                `json:"-"`
}

func (m *APWelcome) Reset()         { *m = APWelcome{} }
func (m *APWelcome) String() string { return proto.CompactTextString(m) }
func (*APWelcome) ProtoMessage()    {}
func (*APWelcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{12}
}

func (m *APWelcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APWelcome.Unmarshal(m, b)
}
func (m *APWelcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APWelcome.Marshal(b, m, deterministic)
}
func (m *APWelcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APWelcome.Merge(m, src)
}
func (m *APWelcome) XXX_Size() int {
	return xxx_messageInfo_APWelcome.Size(m)
}
func (m *APWelcome) XXX_DiscardUnknown() {
	xxx_messageInfo_APWelcome.DiscardUnknown(m)
}

var xxx_messageInfo_APWelcome proto.InternalMessageInfo

func (m *APWelcome) GetCanonicalUsername() string {
	if m != nil && m.CanonicalUsername != nil {
		return *m.CanonicalUsername
	}
	return ""
}

func (m *APWelcome) GetAccountTypeLoggedIn() AccountType {
	if m != nil && m.AccountTypeLoggedIn != nil {
		return *m.AccountTypeLoggedIn
	}
	return AccountType_Spotify
}

func (m *APWelcome) GetCredentialsTypeLoggedIn() AccountType {
	if m != nil && m.CredentialsTypeLoggedIn != nil {
		return *m.CredentialsTypeLoggedIn
	}
	return AccountType_Spotify
}

func (m *APWelcome) GetReusableAuthCredentialsType() AuthenticationType {
	if m != nil && m.ReusableAuthCredentialsType != nil {
		return *m.ReusableAuthCredentialsType
	}
	return AuthenticationType_AUTHENTICATION_USER_PASS
}

func (m *APWelcome) GetReusableAuthCredentials() []byte {
	if m != nil {
		return m.ReusableAuthCredentials
	}
	return nil
}

func (m *APWelcome) GetLfsSecret() []byte {
	if m != nil {
		return m.LfsSecret
	}
	return nil
}

func (m *APWelcome) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func (m *APWelcome) GetFb() *AccountInfoFacebook {
	if m != nil {
		return m.Fb
	}
	return nil
}

type AccountInfo struct {
	Spotify              *AccountInfoSpotify  `protobuf:"bytes,1,opt,name=spotify" json:"spotify,omitempty"`
	Facebook             *AccountInfoFacebook `protobuf:"bytes,2,opt,name=facebook" json:"facebook,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{13}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetSpotify() *AccountInfoSpotify {
	if m != nil {
		return m.Spotify
	}
	return nil
}

func (m *AccountInfo) GetFacebook() *AccountInfoFacebook {
	if m != nil {
		return m.Facebook
	}
	return nil
}

type AccountInfoSpotify struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfoSpotify) Reset()         { *m = AccountInfoSpotify{} }
func (m *AccountInfoSpotify) String() string { return proto.CompactTextString(m) }
func (*AccountInfoSpotify) ProtoMessage()    {}
func (*AccountInfoSpotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{14}
}

func (m *AccountInfoSpotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfoSpotify.Unmarshal(m, b)
}
func (m *AccountInfoSpotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfoSpotify.Marshal(b, m, deterministic)
}
func (m *AccountInfoSpotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfoSpotify.Merge(m, src)
}
func (m *AccountInfoSpotify) XXX_Size() int {
	return xxx_messageInfo_AccountInfoSpotify.Size(m)
}
func (m *AccountInfoSpotify) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfoSpotify.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfoSpotify proto.InternalMessageInfo

type AccountInfoFacebook struct {
	AccessToken          *string  `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	MachineId            *string  `protobuf:"bytes,2,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfoFacebook) Reset()         { *m = AccountInfoFacebook{} }
func (m *AccountInfoFacebook) String() string { return proto.CompactTextString(m) }
func (*AccountInfoFacebook) ProtoMessage()    {}
func (*AccountInfoFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{15}
}

func (m *AccountInfoFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfoFacebook.Unmarshal(m, b)
}
func (m *AccountInfoFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfoFacebook.Marshal(b, m, deterministic)
}
func (m *AccountInfoFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfoFacebook.Merge(m, src)
}
func (m *AccountInfoFacebook) XXX_Size() int {
	return xxx_messageInfo_AccountInfoFacebook.Size(m)
}
func (m *AccountInfoFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfoFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfoFacebook proto.InternalMessageInfo

func (m *AccountInfoFacebook) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *AccountInfoFacebook) GetMachineId() string {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return ""
}

func init() {
	proto.RegisterEnum("spotify.AuthenticationType", AuthenticationType_name, AuthenticationType_value)
	proto.RegisterEnum("spotify.AccountCreation", AccountCreation_name, AccountCreation_value)
	proto.RegisterEnum("spotify.CpuFamily", CpuFamily_name, CpuFamily_value)
	proto.RegisterEnum("spotify.Brand", Brand_name, Brand_value)
	proto.RegisterEnum("spotify.Os", Os_name, Os_value)
	proto.RegisterEnum("spotify.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*ClientResponseEncrypted)(nil), "spotify.ClientResponseEncrypted")
	proto.RegisterType((*LoginCredentials)(nil), "spotify.LoginCredentials")
	proto.RegisterType((*FingerprintResponseUnion)(nil), "spotify.FingerprintResponseUnion")
	proto.RegisterType((*FingerprintGrainResponse)(nil), "spotify.FingerprintGrainResponse")
	proto.RegisterType((*FingerprintHmacRipemdResponse)(nil), "spotify.FingerprintHmacRipemdResponse")
	proto.RegisterType((*PeerTicketUnion)(nil), "spotify.PeerTicketUnion")
	proto.RegisterType((*PeerTicketPublicKey)(nil), "spotify.PeerTicketPublicKey")
	proto.RegisterType((*PeerTicketOld)(nil), "spotify.PeerTicketOld")
	proto.RegisterType((*SystemInfo)(nil), "spotify.SystemInfo")
	proto.RegisterType((*LibspotifyAppKey)(nil), "spotify.LibspotifyAppKey")
	proto.RegisterType((*ClientInfo)(nil), "spotify.ClientInfo")
	proto.RegisterType((*ClientInfoFacebook)(nil), "spotify.ClientInfoFacebook")
	proto.RegisterType((*APWelcome)(nil), "spotify.APWelcome")
	proto.RegisterType((*AccountInfo)(nil), "spotify.AccountInfo")
	proto.RegisterType((*AccountInfoSpotify)(nil), "spotify.AccountInfoSpotify")
	proto.RegisterType((*AccountInfoFacebook)(nil), "spotify.AccountInfoFacebook")
}

func init() { proto.RegisterFile("authentication.proto", fileDescriptor_d0dbc99083440df2) }

var fileDescriptor_d0dbc99083440df2 = []byte{
	// 1692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x36, 0xa1, 0x27, 0x9b, 0xa4, 0x34, 0x1e, 0xc9, 0x36, 0xbc, 0xb2, 0x1d, 0x9a, 0x79, 0x14,
	0xa3, 0x64, 0x5d, 0x59, 0xae, 0xd7, 0xde, 0x24, 0xae, 0x4a, 0x41, 0x20, 0x68, 0xa1, 0x48, 0x01,
	0xf0, 0x80, 0xb4, 0xa4, 0xbd, 0x20, 0x20, 0x30, 0xa4, 0x50, 0x02, 0x01, 0x14, 0x00, 0xba, 0x96,
	0x39, 0xe4, 0x96, 0x7f, 0x91, 0xdc, 0x92, 0x1f, 0x94, 0x4b, 0x7e, 0x45, 0x7e, 0x42, 0x0e, 0xa9,
	0x19, 0x3c, 0xf8, 0x90, 0xec, 0x3d, 0x11, 0xdd, 0xfd, 0xf5, 0xd7, 0x3d, 0xd3, 0x8f, 0x21, 0x1c,
	0xdb, 0xf3, 0xf4, 0x86, 0x06, 0xa9, 0xe7, 0xd8, 0xa9, 0x17, 0x06, 0xaf, 0xa2, 0x38, 0x4c, 0x43,
	0xbc, 0x97, 0x44, 0x61, 0xea, 0x4d, 0x16, 0xad, 0x7f, 0x6e, 0xc3, 0x13, 0xd9, 0xf7, 0x68, 0x90,
	0x12, 0x9a, 0x44, 0x61, 0x90, 0x50, 0x25, 0x70, 0xe2, 0x45, 0x94, 0x52, 0x17, 0xf7, 0xe0, 0xa1,
	0x1f, 0x4e, 0xbd, 0xc0, 0x72, 0x62, 0xea, 0x32, 0x0a, 0xdb, 0x4f, 0x44, 0x68, 0x0a, 0xed, 0x5a,
	0xe7, 0xe9, 0xab, 0x9c, 0xe0, 0xd5, 0x80, 0x21, 0xe4, 0x25, 0x80, 0x20, 0x7f, 0x43, 0x83, 0x65,
	0x40, 0xb6, 0xe3, 0x84, 0xf3, 0x20, 0x65, 0x4c, 0x3c, 0x0d, 0xf1, 0xb8, 0x59, 0x69, 0x1f, 0x74,
	0xc4, 0x92, 0x46, 0xca, 0x00, 0x72, 0x6e, 0x27, 0x87, 0xf6, 0xba, 0x02, 0x0f, 0xe1, 0x78, 0xe2,
	0x05, 0x53, 0x1a, 0x47, 0xb1, 0x17, 0xa4, 0x56, 0x9c, 0x67, 0x2b, 0xbe, 0x68, 0x56, 0xda, 0xb5,
	0xce, 0xcb, 0x92, 0xa8, 0xb7, 0x04, 0x15, 0x27, 0x1a, 0x05, 0x8c, 0xf1, 0x68, 0x72, 0xd7, 0x82,
	0x7f, 0x0f, 0xb5, 0x88, 0xd2, 0xd8, 0x4a, 0x3d, 0xe7, 0x96, 0xa6, 0x62, 0x9b, 0x93, 0x2d, 0xb3,
	0x32, 0x28, 0x8d, 0x87, 0xdc, 0x94, 0x71, 0x40, 0x54, 0x2a, 0xf0, 0x6b, 0xa8, 0x25, 0x8b, 0x24,
	0xa5, 0x33, 0xcb, 0x0b, 0x26, 0xa1, 0xd8, 0xe1, 0xf7, 0x72, 0x54, 0xba, 0x9a, 0xdc, 0xa6, 0x06,
	0x93, 0x90, 0x40, 0x52, 0x7e, 0xe3, 0x5f, 0xc2, 0x41, 0xe4, 0xdb, 0xe9, 0x24, 0x8c, 0x67, 0xd6,
	0x2c, 0x74, 0xa9, 0x2f, 0xbe, 0x6b, 0x56, 0xda, 0x55, 0xd2, 0x28, 0xb4, 0x17, 0x4c, 0xc9, 0x60,
	0x9f, 0x68, 0x9c, 0x78, 0x61, 0x60, 0x25, 0x69, 0xec, 0x05, 0x53, 0xb1, 0x97, 0xc1, 0x72, 0xad,
	0xc9, 0x95, 0xf8, 0x1b, 0xd8, 0xb5, 0xa3, 0xe8, 0x96, 0x2e, 0x44, 0x83, 0x67, 0xbe, 0x52, 0x16,
	0x6f, 0x9c, 0x7f, 0x4a, 0x51, 0xd4, 0xa7, 0x0b, 0x92, 0x03, 0x59, 0xda, 0x0e, 0xaf, 0x77, 0x96,
	0xf6, 0x0f, 0xdc, 0x6f, 0x99, 0x76, 0xd6, 0x0b, 0x59, 0xda, 0x4e, 0xf9, 0xdd, 0xfa, 0x0b, 0xa0,
	0xcd, 0x42, 0xe3, 0xaf, 0x60, 0x7f, 0x9e, 0xd0, 0x38, 0xb0, 0x67, 0x54, 0x04, 0x9e, 0x5d, 0x29,
	0xe3, 0xaf, 0x61, 0x2b, 0x5d, 0x44, 0xe2, 0x71, 0x53, 0x68, 0x1f, 0x74, 0x4e, 0x96, 0x55, 0x5e,
	0xeb, 0xc5, 0xe1, 0x22, 0xa2, 0x84, 0xe1, 0xf0, 0x09, 0x54, 0x59, 0x9b, 0x5a, 0xae, 0x9d, 0xda,
	0xbc, 0xa2, 0x75, 0xb2, 0xcf, 0x14, 0x5d, 0x3b, 0xb5, 0x5b, 0x7f, 0xaf, 0x80, 0xf8, 0xb9, 0xaa,
	0xe2, 0xb7, 0xb0, 0x33, 0x8d, 0x6d, 0x2f, 0xe0, 0x19, 0x7c, 0xa6, 0x0f, 0xde, 0x33, 0x40, 0xe1,
	0x46, 0x32, 0x3c, 0x7e, 0x0f, 0xb5, 0x9b, 0x99, 0xed, 0x58, 0xb1, 0x17, 0xd1, 0x99, 0xcb, 0xfb,
	0xb1, 0xd6, 0xf9, 0xd5, 0x7d, 0xee, 0xe7, 0x33, 0xdb, 0x21, 0x1c, 0x55, 0x72, 0xc0, 0x4d, 0xa9,
	0x6b, 0xfd, 0x69, 0x2d, 0xbb, 0xb5, 0x58, 0xf8, 0xe7, 0xd0, 0xa0, 0xc5, 0x38, 0x59, 0xac, 0x4c,
	0x6c, 0x7a, 0xea, 0xa4, 0x5e, 0x2a, 0xfb, 0x74, 0xd1, 0xfa, 0x16, 0x9e, 0x7f, 0x31, 0x1a, 0xc6,
	0xb0, 0xcd, 0xe2, 0xe5, 0xce, 0xfc, 0xbb, 0xf5, 0xb7, 0x0a, 0x1c, 0x6e, 0x74, 0x27, 0xfe, 0x23,
	0x40, 0x34, 0x1f, 0xfb, 0x9e, 0x93, 0x87, 0x62, 0x27, 0x7a, 0x76, 0x4f, 0x2f, 0x1b, 0x1c, 0xc4,
	0x9a, 0xa2, 0x1a, 0x15, 0x9f, 0xf8, 0x3b, 0x80, 0xd0, 0x77, 0x8b, 0x41, 0xc8, 0xae, 0xe3, 0xf1,
	0x3d, 0xce, 0xba, 0xef, 0x92, 0x6a, 0xe8, 0xbb, 0x99, 0xd4, 0x7a, 0x0d, 0x47, 0xf7, 0x10, 0xe3,
	0xe7, 0x1b, 0xa9, 0xb0, 0xc4, 0x97, 0xc1, 0x5a, 0x2e, 0x34, 0xd6, 0x18, 0xf1, 0xcf, 0xd6, 0xe7,
	0x30, 0x73, 0x58, 0x9d, 0xb6, 0x0e, 0x3c, 0x5a, 0x01, 0x58, 0x89, 0x37, 0x0d, 0xec, 0x74, 0x1e,
	0x53, 0xde, 0x62, 0x75, 0x72, 0xb4, 0x84, 0x9a, 0x85, 0xa9, 0xf5, 0x5f, 0x01, 0x60, 0x39, 0x86,
	0xf8, 0x1b, 0x00, 0x27, 0x9a, 0x5b, 0x13, 0x7b, 0xe6, 0xf9, 0x59, 0x4e, 0x07, 0x1d, 0xbc, 0x6c,
	0xfc, 0x68, 0xde, 0xe3, 0x16, 0x52, 0x75, 0x8a, 0x4f, 0x96, 0x16, 0x73, 0x49, 0xe6, 0xe3, 0x74,
	0x11, 0x51, 0x7e, 0x2b, 0x0d, 0xc2, 0x58, 0xcc, 0x4c, 0x83, 0x9f, 0xc0, 0x1e, 0x03, 0xd0, 0x1f,
	0x53, 0xde, 0xb6, 0x0d, 0xb2, 0xeb, 0x44, 0x73, 0xe5, 0xc7, 0x14, 0xff, 0x02, 0x76, 0xc6, 0xb1,
	0x1d, 0xb8, 0x7c, 0xa5, 0x1c, 0x74, 0x0e, 0xca, 0x38, 0x67, 0x4c, 0x4b, 0x32, 0x23, 0xe3, 0xe7,
	0x1f, 0xd6, 0xc4, 0xb7, 0xa7, 0x89, 0xd8, 0xc9, 0xf8, 0xb9, 0xaa, 0xc7, 0x34, 0xf8, 0x04, 0x84,
	0x30, 0x11, 0xdf, 0xf1, 0x5c, 0x6b, 0x25, 0x87, 0x9e, 0x10, 0x21, 0x4c, 0xd8, 0x25, 0x87, 0x89,
	0x95, 0x6f, 0x04, 0xbe, 0x20, 0x1a, 0xa4, 0x1a, 0x26, 0x1f, 0x33, 0x05, 0x7e, 0x04, 0xbb, 0x61,
	0xc2, 0x53, 0x33, 0xb8, 0x69, 0x27, 0x4c, 0x58, 0x66, 0x7f, 0x80, 0xa7, 0x2b, 0x7b, 0x2b, 0x9e,
	0xf1, 0x51, 0x2c, 0xb6, 0xcc, 0x0f, 0x7c, 0x8e, 0x9f, 0x2c, 0x17, 0x56, 0x6e, 0xcf, 0xf7, 0xcd,
	0x09, 0x54, 0x5d, 0xfa, 0xc9, 0x73, 0xa8, 0xe5, 0xb9, 0xa2, 0x9b, 0xcd, 0x7c, 0xa6, 0x50, 0xdd,
	0xd6, 0xbf, 0x2a, 0x80, 0x36, 0xd7, 0x0e, 0x16, 0x61, 0xaf, 0x48, 0xb0, 0xd2, 0x14, 0xda, 0x0d,
	0x52, 0x88, 0xf8, 0x31, 0xec, 0xba, 0xf4, 0x13, 0x6b, 0x0f, 0x81, 0x97, 0x30, 0x97, 0xf0, 0x33,
	0xa8, 0x2e, 0xab, 0xbb, 0x95, 0x75, 0x4e, 0xa9, 0x60, 0x56, 0xb6, 0x64, 0xec, 0x29, 0x0d, 0x52,
	0x71, 0xbb, 0x29, 0xb4, 0xab, 0x64, 0xa9, 0x60, 0xf3, 0xe6, 0xd8, 0xbe, 0x3f, 0xb6, 0x9d, 0x5b,
	0xeb, 0xc6, 0x4e, 0x6e, 0xc4, 0x9d, 0x6c, 0xde, 0x0a, 0xe5, 0xb9, 0x9d, 0xdc, 0xb4, 0x42, 0x80,
	0xe5, 0x96, 0x63, 0x09, 0xfa, 0xde, 0xcc, 0x4b, 0xa9, 0x2b, 0x56, 0x9a, 0x95, 0xf6, 0x3e, 0x29,
	0x44, 0xfc, 0x1b, 0x10, 0x26, 0x63, 0x51, 0xe0, 0x93, 0x70, 0x72, 0xcf, 0x82, 0xec, 0xd9, 0x0e,
	0x1d, 0x87, 0xe1, 0x2d, 0x11, 0x26, 0x63, 0xb6, 0x0c, 0x7d, 0x3b, 0x98, 0xce, 0xed, 0x29, 0x4b,
	0x9a, 0x5f, 0x4c, 0x21, 0xb7, 0xbe, 0x05, 0x7c, 0xd7, 0x8b, 0x55, 0x6f, 0x66, 0x3b, 0x37, 0x5e,
	0xc0, 0x2f, 0xb3, 0xc2, 0x7d, 0xaa, 0xb9, 0x46, 0x75, 0x5b, 0xff, 0xdb, 0x82, 0xaa, 0x64, 0x5c,
	0x52, 0xdf, 0x09, 0xf9, 0x3e, 0xc5, 0x8e, 0x1d, 0x84, 0x81, 0xe7, 0xd8, 0xbe, 0xb5, 0xb2, 0x75,
	0xd9, 0xf9, 0x1f, 0x96, 0x96, 0x51, 0xb1, 0x7e, 0x55, 0x78, 0x5c, 0xbc, 0xb8, 0xac, 0x4d, 0x2d,
	0x3f, 0x9c, 0x4e, 0xa9, 0x6b, 0x79, 0x41, 0xbe, 0x91, 0x8f, 0x37, 0xdf, 0x5d, 0xbe, 0x8a, 0x8f,
	0xec, 0xa5, 0x30, 0xe0, 0x1e, 0x6a, 0x80, 0x3f, 0xc0, 0x57, 0x2b, 0xcf, 0xff, 0x26, 0xdd, 0xd3,
	0x2f, 0xd0, 0x3d, 0x59, 0xf1, 0x5b, 0xa3, 0xfc, 0x33, 0xbc, 0x88, 0xe9, 0x3c, 0xb1, 0xc7, 0x3e,
	0xb5, 0xf8, 0xda, 0xdf, 0x0c, 0x20, 0xbe, 0xf8, 0xe9, 0x77, 0xe3, 0xa4, 0xa0, 0x60, 0x36, 0x79,
	0x3d, 0x12, 0xeb, 0xf1, 0xcf, 0x46, 0x10, 0xdb, 0xbc, 0x27, 0x9e, 0x7c, 0xc6, 0x9f, 0xd5, 0xc5,
	0x9f, 0x24, 0x56, 0x42, 0x9d, 0x98, 0xa6, 0x7c, 0x24, 0xeb, 0xa4, 0xea, 0x4f, 0x12, 0x93, 0x2b,
	0xf0, 0x5b, 0xa8, 0x17, 0x57, 0xcb, 0x1f, 0xd0, 0x77, 0xbc, 0x3f, 0xee, 0xdc, 0x00, 0x7f, 0x41,
	0x6b, 0xf6, 0x52, 0xc0, 0xbf, 0xe5, 0xed, 0xd4, 0xdb, 0xd8, 0xca, 0x2b, 0xf0, 0xd5, 0x7e, 0x6a,
	0xfd, 0x15, 0x6a, 0x2b, 0x26, 0xfc, 0x1d, 0x14, 0xff, 0xd8, 0x78, 0xa7, 0xac, 0x36, 0xe4, 0x0a,
	0xcc, 0xcc, 0x54, 0xa4, 0xc0, 0xe2, 0xef, 0x61, 0x7f, 0x92, 0xb3, 0xe6, 0x8d, 0xfc, 0xe5, 0xc8,
	0x25, 0xba, 0x75, 0x0c, 0xf8, 0x2e, 0x71, 0xeb, 0x12, 0x8e, 0xee, 0x71, 0xc3, 0x2f, 0xf9, 0x9d,
	0xd0, 0x24, 0xb1, 0xd2, 0xf0, 0x96, 0x06, 0x79, 0x33, 0xd7, 0x32, 0xdd, 0x90, 0xa9, 0x36, 0xba,
	0x5d, 0xd8, 0xe8, 0xf6, 0xd3, 0xff, 0x54, 0x00, 0xdf, 0x2d, 0x32, 0x7e, 0x06, 0xa2, 0x34, 0x1a,
	0x9e, 0x2b, 0xda, 0x50, 0x95, 0xa5, 0xa1, 0xaa, 0x6b, 0xd6, 0xc8, 0x54, 0x88, 0x65, 0x48, 0xa6,
	0x89, 0x1e, 0xe0, 0xaf, 0xe1, 0xd7, 0x1b, 0x56, 0x73, 0xa8, 0x13, 0xa5, 0x6b, 0x99, 0x86, 0x3e,
	0x54, 0x7b, 0xd7, 0x96, 0x4c, 0x94, 0x2e, 0xb3, 0x4a, 0x03, 0x13, 0x55, 0xf0, 0x2b, 0x38, 0xbd,
	0x1f, 0xde, 0x93, 0x64, 0xe5, 0x4c, 0xd7, 0xfb, 0x6b, 0x78, 0x01, 0x37, 0xe1, 0xd9, 0x26, 0x3e,
	0xe7, 0x1d, 0xea, 0x7d, 0x45, 0x43, 0x5b, 0xf8, 0x25, 0x3c, 0xdf, 0x40, 0x94, 0x54, 0x19, 0x64,
	0xfb, 0xf4, 0x1a, 0x0e, 0x37, 0xfe, 0xda, 0xe2, 0x16, 0xbc, 0x90, 0x64, 0x59, 0x1f, 0x69, 0x43,
	0x16, 0x30, 0xf3, 0x93, 0x06, 0x97, 0xd2, 0xb5, 0x69, 0x19, 0x44, 0xbf, 0x30, 0x86, 0xa8, 0xf2,
	0x25, 0x0c, 0x97, 0x15, 0xb4, 0x75, 0xfa, 0x8f, 0x0a, 0x54, 0xcb, 0x57, 0x0b, 0x1f, 0x42, 0x4d,
	0x36, 0x46, 0xd6, 0x48, 0xeb, 0x6b, 0xfa, 0xa5, 0x86, 0x1e, 0xe0, 0x1a, 0xec, 0x31, 0xc5, 0xd5,
	0xf7, 0x6f, 0x50, 0x05, 0x1f, 0x00, 0xe4, 0x82, 0xf5, 0xe6, 0x35, 0x12, 0x0a, 0xa3, 0x61, 0xc8,
	0x68, 0xab, 0x30, 0x1a, 0x86, 0xcc, 0x8c, 0xdb, 0x85, 0x51, 0x22, 0x17, 0x68, 0x07, 0xd7, 0x61,
	0x9f, 0x09, 0xaa, 0xf4, 0xe6, 0x35, 0xda, 0xc5, 0x00, 0xbb, 0x4c, 0x32, 0xcf, 0xd1, 0x5e, 0x61,
	0xb9, 0x50, 0x0d, 0x13, 0xed, 0x63, 0x04, 0x75, 0x26, 0x9d, 0x0d, 0x24, 0xb9, 0xdf, 0x53, 0x35,
	0x54, 0x3d, 0xed, 0xc3, 0x0e, 0x7f, 0xec, 0xf0, 0x11, 0x1c, 0x9e, 0x11, 0x49, 0xeb, 0x5a, 0x23,
	0x8d, 0xff, 0x2a, 0x5d, 0xf4, 0x00, 0x37, 0xa0, 0x9a, 0x29, 0x55, 0xed, 0x03, 0xaa, 0x2c, 0xc5,
	0xf3, 0xa1, 0x8c, 0x04, 0x76, 0x9a, 0x4c, 0xd4, 0xf4, 0xbe, 0x2a, 0xa1, 0xad, 0xd3, 0x7f, 0x0b,
	0x20, 0xe8, 0x09, 0x4b, 0x55, 0x37, 0x57, 0x0e, 0x99, 0xc9, 0x97, 0xaa, 0xd6, 0xd5, 0x2f, 0x59,
	0x8d, 0x01, 0x76, 0x75, 0xd3, 0xd2, 0xcd, 0x2b, 0x24, 0x30, 0x4a, 0xdd, 0xb4, 0x54, 0xe3, 0x5c,
	0xd7, 0x14, 0xb4, 0x95, 0x9b, 0xcc, 0x37, 0xbf, 0x43, 0xdb, 0x2c, 0x75, 0xdd, 0xb4, 0x06, 0xaa,
	0x36, 0xba, 0x42, 0x3b, 0xf8, 0x21, 0x34, 0x96, 0x24, 0x96, 0xac, 0xa0, 0xdd, 0x9c, 0x57, 0xd2,
	0xba, 0x44, 0x57, 0xbb, 0x68, 0x8f, 0x5d, 0x89, 0x6e, 0x5a, 0x86, 0x34, 0xb8, 0x40, 0xfb, 0xb9,
	0xb1, 0x47, 0x14, 0xe5, 0xcc, 0xec, 0xa2, 0x6a, 0xee, 0xcf, 0x4f, 0x7e, 0xa6, 0x10, 0x72, 0x8d,
	0x20, 0x0f, 0x60, 0xea, 0x9a, 0x6e, 0xa2, 0x1a, 0x3b, 0x0d, 0x0b, 0xa7, 0xbf, 0x57, 0x87, 0x8a,
	0x7c, 0x8e, 0xea, 0x79, 0x2e, 0x97, 0xc6, 0x5b, 0xd4, 0xc8, 0xa1, 0xba, 0xd6, 0xbf, 0xd6, 0xd1,
	0x41, 0xce, 0x6d, 0x9c, 0xab, 0x03, 0x76, 0xad, 0x87, 0xb8, 0x0a, 0x3b, 0x0c, 0xd9, 0x45, 0x28,
	0x07, 0x7e, 0xd4, 0x07, 0x1f, 0x75, 0xf4, 0x30, 0xcf, 0x68, 0xa8, 0x7e, 0xd4, 0x11, 0xce, 0x05,
	0xe9, 0x52, 0xbf, 0x42, 0x47, 0x39, 0xee, 0x42, 0x51, 0xde, 0xeb, 0xe8, 0x38, 0xbf, 0x85, 0x0f,
	0xda, 0x95, 0x36, 0xd4, 0xd1, 0xa3, 0x3c, 0xf2, 0x99, 0xac, 0xa3, 0xc7, 0xa7, 0xed, 0x72, 0xc7,
	0xf0, 0x61, 0xab, 0xc1, 0x5e, 0x3e, 0xe7, 0xe8, 0x01, 0x23, 0x29, 0xc6, 0x1b, 0x55, 0xfe, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0xac, 0x52, 0x23, 0x45, 0x0e, 0x00, 0x00,
}
