// Code generated by protoc-gen-go. DO NOT EDIT.
// source: facebook-publish.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventReply struct {
	Queued               *int32     `protobuf:"varint,1,opt,name=queued" json:"queued,omitempty"`
	Retry                *RetryInfo `protobuf:"bytes,2,opt,name=retry" json:"retry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventReply) Reset()         { *m = EventReply{} }
func (m *EventReply) String() string { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()    {}
func (*EventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{0}
}

func (m *EventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventReply.Unmarshal(m, b)
}
func (m *EventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventReply.Marshal(b, m, deterministic)
}
func (m *EventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReply.Merge(m, src)
}
func (m *EventReply) XXX_Size() int {
	return xxx_messageInfo_EventReply.Size(m)
}
func (m *EventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReply.DiscardUnknown(m)
}

var xxx_messageInfo_EventReply proto.InternalMessageInfo

func (m *EventReply) GetQueued() int32 {
	if m != nil && m.Queued != nil {
		return *m.Queued
	}
	return 0
}

func (m *EventReply) GetRetry() *RetryInfo {
	if m != nil {
		return m.Retry
	}
	return nil
}

type RetryInfo struct {
	RetryDelay           *int32   `protobuf:"varint,1,opt,name=retry_delay,json=retryDelay" json:"retry_delay,omitempty"`
	MaxRetry             *int32   `protobuf:"varint,2,opt,name=max_retry,json=maxRetry" json:"max_retry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryInfo) Reset()         { *m = RetryInfo{} }
func (m *RetryInfo) String() string { return proto.CompactTextString(m) }
func (*RetryInfo) ProtoMessage()    {}
func (*RetryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{1}
}

func (m *RetryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryInfo.Unmarshal(m, b)
}
func (m *RetryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryInfo.Marshal(b, m, deterministic)
}
func (m *RetryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryInfo.Merge(m, src)
}
func (m *RetryInfo) XXX_Size() int {
	return xxx_messageInfo_RetryInfo.Size(m)
}
func (m *RetryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RetryInfo proto.InternalMessageInfo

func (m *RetryInfo) GetRetryDelay() int32 {
	if m != nil && m.RetryDelay != nil {
		return *m.RetryDelay
	}
	return 0
}

func (m *RetryInfo) GetMaxRetry() int32 {
	if m != nil && m.MaxRetry != nil {
		return *m.MaxRetry
	}
	return 0
}

type ID struct {
	Uri                  *string  `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	StartTime            *int64   `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *ID) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type Start struct {
	Length               *int32   `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
	ContextUri           *string  `protobuf:"bytes,2,opt,name=context_uri,json=contextUri" json:"context_uri,omitempty"`
	EndTime              *int64   `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Start) Reset()         { *m = Start{} }
func (m *Start) String() string { return proto.CompactTextString(m) }
func (*Start) ProtoMessage()    {}
func (*Start) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{3}
}

func (m *Start) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Start.Unmarshal(m, b)
}
func (m *Start) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Start.Marshal(b, m, deterministic)
}
func (m *Start) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Start.Merge(m, src)
}
func (m *Start) XXX_Size() int {
	return xxx_messageInfo_Start.Size(m)
}
func (m *Start) XXX_DiscardUnknown() {
	xxx_messageInfo_Start.DiscardUnknown(m)
}

var xxx_messageInfo_Start proto.InternalMessageInfo

func (m *Start) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Start) GetContextUri() string {
	if m != nil && m.ContextUri != nil {
		return *m.ContextUri
	}
	return ""
}

func (m *Start) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Seek struct {
	EndTime              *int64   `protobuf:"varint,1,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seek) Reset()         { *m = Seek{} }
func (m *Seek) String() string { return proto.CompactTextString(m) }
func (*Seek) ProtoMessage()    {}
func (*Seek) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{4}
}

func (m *Seek) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seek.Unmarshal(m, b)
}
func (m *Seek) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seek.Marshal(b, m, deterministic)
}
func (m *Seek) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seek.Merge(m, src)
}
func (m *Seek) XXX_Size() int {
	return xxx_messageInfo_Seek.Size(m)
}
func (m *Seek) XXX_DiscardUnknown() {
	xxx_messageInfo_Seek.DiscardUnknown(m)
}

var xxx_messageInfo_Seek proto.InternalMessageInfo

func (m *Seek) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Pause struct {
	SecondsPlayed        *int32   `protobuf:"varint,1,opt,name=seconds_played,json=secondsPlayed" json:"seconds_played,omitempty"`
	EndTime              *int64   `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pause) Reset()         { *m = Pause{} }
func (m *Pause) String() string { return proto.CompactTextString(m) }
func (*Pause) ProtoMessage()    {}
func (*Pause) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{5}
}

func (m *Pause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pause.Unmarshal(m, b)
}
func (m *Pause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pause.Marshal(b, m, deterministic)
}
func (m *Pause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pause.Merge(m, src)
}
func (m *Pause) XXX_Size() int {
	return xxx_messageInfo_Pause.Size(m)
}
func (m *Pause) XXX_DiscardUnknown() {
	xxx_messageInfo_Pause.DiscardUnknown(m)
}

var xxx_messageInfo_Pause proto.InternalMessageInfo

func (m *Pause) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *Pause) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Resume struct {
	SecondsPlayed        *int32   `protobuf:"varint,1,opt,name=seconds_played,json=secondsPlayed" json:"seconds_played,omitempty"`
	EndTime              *int64   `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resume) Reset()         { *m = Resume{} }
func (m *Resume) String() string { return proto.CompactTextString(m) }
func (*Resume) ProtoMessage()    {}
func (*Resume) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{6}
}

func (m *Resume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resume.Unmarshal(m, b)
}
func (m *Resume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resume.Marshal(b, m, deterministic)
}
func (m *Resume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resume.Merge(m, src)
}
func (m *Resume) XXX_Size() int {
	return xxx_messageInfo_Resume.Size(m)
}
func (m *Resume) XXX_DiscardUnknown() {
	xxx_messageInfo_Resume.DiscardUnknown(m)
}

var xxx_messageInfo_Resume proto.InternalMessageInfo

func (m *Resume) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *Resume) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type End struct {
	SecondsPlayed        *int32   `protobuf:"varint,1,opt,name=seconds_played,json=secondsPlayed" json:"seconds_played,omitempty"`
	EndTime              *int64   `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *End) Reset()         { *m = End{} }
func (m *End) String() string { return proto.CompactTextString(m) }
func (*End) ProtoMessage()    {}
func (*End) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{7}
}

func (m *End) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_End.Unmarshal(m, b)
}
func (m *End) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_End.Marshal(b, m, deterministic)
}
func (m *End) XXX_Merge(src proto.Message) {
	xxx_messageInfo_End.Merge(m, src)
}
func (m *End) XXX_Size() int {
	return xxx_messageInfo_End.Size(m)
}
func (m *End) XXX_DiscardUnknown() {
	xxx_messageInfo_End.DiscardUnknown(m)
}

var xxx_messageInfo_End proto.InternalMessageInfo

func (m *End) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *End) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Event struct {
	Id                   *ID      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Start                *Start   `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	Seek                 *Seek    `protobuf:"bytes,3,opt,name=seek" json:"seek,omitempty"`
	Pause                *Pause   `protobuf:"bytes,4,opt,name=pause" json:"pause,omitempty"`
	Resume               *Resume  `protobuf:"bytes,5,opt,name=resume" json:"resume,omitempty"`
	End                  *End     `protobuf:"bytes,6,opt,name=end" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cffe421ed563434, []int{8}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() *ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetStart() *Start {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetSeek() *Seek {
	if m != nil {
		return m.Seek
	}
	return nil
}

func (m *Event) GetPause() *Pause {
	if m != nil {
		return m.Pause
	}
	return nil
}

func (m *Event) GetResume() *Resume {
	if m != nil {
		return m.Resume
	}
	return nil
}

func (m *Event) GetEnd() *End {
	if m != nil {
		return m.End
	}
	return nil
}

func init() {
	proto.RegisterType((*EventReply)(nil), "spotify.EventReply")
	proto.RegisterType((*RetryInfo)(nil), "spotify.RetryInfo")
	proto.RegisterType((*ID)(nil), "spotify.ID")
	proto.RegisterType((*Start)(nil), "spotify.Start")
	proto.RegisterType((*Seek)(nil), "spotify.Seek")
	proto.RegisterType((*Pause)(nil), "spotify.Pause")
	proto.RegisterType((*Resume)(nil), "spotify.Resume")
	proto.RegisterType((*End)(nil), "spotify.End")
	proto.RegisterType((*Event)(nil), "spotify.Event")
}

func init() { proto.RegisterFile("facebook-publish.proto", fileDescriptor_4cffe421ed563434) }

var fileDescriptor_4cffe421ed563434 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0xa4, 0xee, 0xd6, 0x17, 0x36, 0x90, 0x0f, 0x53, 0xd0, 0x04, 0x6c, 0x15, 0x88,
	0x5e, 0xe8, 0xa1, 0x12, 0xff, 0x41, 0x2b, 0x14, 0x0e, 0x68, 0xf2, 0xe0, 0xc4, 0x21, 0xca, 0xea,
	0x57, 0x66, 0x25, 0xb1, 0x43, 0xec, 0xa0, 0xe6, 0x7f, 0xe5, 0x8f, 0x41, 0x7e, 0x09, 0x19, 0xe1,
	0xdc, 0x5b, 0xfc, 0x7d, 0xdf, 0xfb, 0x29, 0xfe, 0xfc, 0xe0, 0xea, 0x90, 0xef, 0xf1, 0xc1, 0x98,
	0xe2, 0x43, 0xdd, 0x3e, 0x94, 0xca, 0x3e, 0xae, 0xeb, 0xc6, 0x38, 0xc3, 0xcf, 0x6c, 0x6d, 0x9c,
	0x3a, 0x74, 0xcb, 0x2f, 0x00, 0xbb, 0x5f, 0xa8, 0x9d, 0xc0, 0xba, 0xec, 0xf8, 0x15, 0xcc, 0x7f,
	0xb6, 0xd8, 0xa2, 0x4c, 0x82, 0x9b, 0x60, 0xc5, 0xc4, 0x70, 0xe2, 0x2b, 0x60, 0x0d, 0xba, 0xa6,
	0x4b, 0xc2, 0x9b, 0x60, 0x15, 0x6f, 0xf8, 0x7a, 0x18, 0x5f, 0x0b, 0xaf, 0xa6, 0xfa, 0x60, 0x44,
	0x1f, 0x58, 0xa6, 0xb0, 0x18, 0x35, 0xfe, 0x06, 0x62, 0x52, 0x33, 0x89, 0x65, 0xde, 0x0d, 0x4c,
	0x20, 0x69, 0xeb, 0x15, 0x7e, 0x0d, 0x8b, 0x2a, 0x3f, 0x66, 0x4f, 0x6c, 0x26, 0xce, 0xab, 0xfc,
	0x48, 0x84, 0xe5, 0x47, 0x08, 0xd3, 0x2d, 0x7f, 0x01, 0x51, 0xdb, 0x28, 0x9a, 0x5d, 0x08, 0xff,
	0xc9, 0x5f, 0x01, 0x58, 0x97, 0x37, 0x2e, 0x73, 0xaa, 0x42, 0x9a, 0x8a, 0xc4, 0x82, 0x94, 0xaf,
	0xaa, 0xc2, 0xe5, 0x77, 0x60, 0xf7, 0xfe, 0xe0, 0x2f, 0x53, 0xa2, 0xfe, 0xe1, 0x1e, 0xff, 0x5e,
	0xa6, 0x3f, 0xf9, 0xbf, 0xda, 0x1b, 0xed, 0xf0, 0xe8, 0x32, 0x4f, 0x0e, 0x89, 0x0c, 0x83, 0xf4,
	0xad, 0x51, 0xfc, 0x25, 0x9c, 0xa3, 0x96, 0x3d, 0x3e, 0x22, 0xfc, 0x19, 0x6a, 0x49, 0xf0, 0x5b,
	0x98, 0xdd, 0x23, 0x16, 0x93, 0x48, 0x30, 0x8d, 0xa4, 0xc0, 0xee, 0xf2, 0xd6, 0x22, 0x7f, 0x07,
	0x97, 0x16, 0xf7, 0x46, 0x4b, 0x9b, 0xd5, 0x65, 0xde, 0x8d, 0xa5, 0x5e, 0x0c, 0xea, 0x1d, 0x89,
	0x13, 0x54, 0x38, 0x45, 0x7d, 0x86, 0xb9, 0x40, 0xdb, 0x56, 0xa7, 0x60, 0x7d, 0x82, 0x68, 0xa7,
	0xe5, 0x09, 0x40, 0xbf, 0x03, 0x60, 0xb4, 0x32, 0xfc, 0x1a, 0x42, 0xd5, 0xcf, 0xc7, 0x9b, 0x78,
	0x5c, 0x89, 0x74, 0x2b, 0x42, 0x25, 0xf9, 0x5b, 0x60, 0xf4, 0x26, 0xc3, 0xca, 0x5c, 0x8e, 0x3e,
	0x3d, 0x8e, 0xe8, 0x4d, 0x7e, 0x0b, 0x33, 0x8b, 0x58, 0x50, 0xcd, 0xf1, 0xe6, 0xe2, 0x29, 0x84,
	0x58, 0x08, 0xb2, 0x3c, 0xa8, 0xf6, 0x7d, 0x26, 0xb3, 0xff, 0x40, 0xd4, 0xb2, 0xe8, 0x4d, 0xfe,
	0x1e, 0xe6, 0x0d, 0x55, 0x95, 0x30, 0x8a, 0x3d, 0xff, 0x67, 0x45, 0xbd, 0x2c, 0x06, 0x9b, 0xbf,
	0x86, 0x08, 0xb5, 0x4c, 0xe6, 0x94, 0x7a, 0x36, 0xa6, 0x76, 0x5a, 0x0a, 0x6f, 0xfc, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0x85, 0xea, 0x12, 0x32, 0x03, 0x00, 0x00,
}
