// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Album_Type int32

const (
	Album_ALBUM       Album_Type = 1
	Album_SINGLE      Album_Type = 2
	Album_COMPILATION Album_Type = 3
	Album_EP          Album_Type = 4
)

var Album_Type_name = map[int32]string{
	1: "ALBUM",
	2: "SINGLE",
	3: "COMPILATION",
	4: "EP",
}

var Album_Type_value = map[string]int32{
	"ALBUM":       1,
	"SINGLE":      2,
	"COMPILATION": 3,
	"EP":          4,
}

func (x Album_Type) Enum() *Album_Type {
	p := new(Album_Type)
	*p = x
	return p
}

func (x Album_Type) String() string {
	return proto.EnumName(Album_Type_name, int32(x))
}

func (x *Album_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Album_Type_value, data, "Album_Type")
	if err != nil {
		return err
	}
	*x = Album_Type(value)
	return nil
}

func (Album_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{5, 0}
}

type Image_Size int32

const (
	Image_DEFAULT Image_Size = 0
	Image_SMALL   Image_Size = 1
	Image_LARGE   Image_Size = 2
	Image_XLARGE  Image_Size = 3
)

var Image_Size_name = map[int32]string{
	0: "DEFAULT",
	1: "SMALL",
	2: "LARGE",
	3: "XLARGE",
}

var Image_Size_value = map[string]int32{
	"DEFAULT": 0,
	"SMALL":   1,
	"LARGE":   2,
	"XLARGE":  3,
}

func (x Image_Size) Enum() *Image_Size {
	p := new(Image_Size)
	*p = x
	return p
}

func (x Image_Size) String() string {
	return proto.EnumName(Image_Size_name, int32(x))
}

func (x *Image_Size) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Image_Size_value, data, "Image_Size")
	if err != nil {
		return err
	}
	*x = Image_Size(value)
	return nil
}

func (Image_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{7, 0}
}

type Copyright_Type int32

const (
	Copyright_P Copyright_Type = 0
	Copyright_C Copyright_Type = 1
)

var Copyright_Type_name = map[int32]string{
	0: "P",
	1: "C",
}

var Copyright_Type_value = map[string]int32{
	"P": 0,
	"C": 1,
}

func (x Copyright_Type) Enum() *Copyright_Type {
	p := new(Copyright_Type)
	*p = x
	return p
}

func (x Copyright_Type) String() string {
	return proto.EnumName(Copyright_Type_name, int32(x))
}

func (x *Copyright_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Copyright_Type_value, data, "Copyright_Type")
	if err != nil {
		return err
	}
	*x = Copyright_Type(value)
	return nil
}

func (Copyright_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{11, 0}
}

type Restriction_Type int32

const (
	Restriction_STREAMING Restriction_Type = 0
)

var Restriction_Type_name = map[int32]string{
	0: "STREAMING",
}

var Restriction_Type_value = map[string]int32{
	"STREAMING": 0,
}

func (x Restriction_Type) Enum() *Restriction_Type {
	p := new(Restriction_Type)
	*p = x
	return p
}

func (x Restriction_Type) String() string {
	return proto.EnumName(Restriction_Type_name, int32(x))
}

func (x *Restriction_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Restriction_Type_value, data, "Restriction_Type")
	if err != nil {
		return err
	}
	*x = Restriction_Type(value)
	return nil
}

func (Restriction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{12, 0}
}

type AudioFile_Format int32

const (
	AudioFile_OGG_VORBIS_96  AudioFile_Format = 0
	AudioFile_OGG_VORBIS_160 AudioFile_Format = 1
	AudioFile_OGG_VORBIS_320 AudioFile_Format = 2
	AudioFile_MP3_256        AudioFile_Format = 3
	AudioFile_MP3_320        AudioFile_Format = 4
	AudioFile_MP3_160        AudioFile_Format = 5
	AudioFile_MP3_96         AudioFile_Format = 6
	AudioFile_MP3_160_ENC    AudioFile_Format = 7
	AudioFile_OTHER2         AudioFile_Format = 8
	AudioFile_OTHER3         AudioFile_Format = 9
	AudioFile_AAC_160        AudioFile_Format = 10
	AudioFile_AAC_320        AudioFile_Format = 11
	AudioFile_OTHER4         AudioFile_Format = 12
	AudioFile_OTHER5         AudioFile_Format = 13
)

var AudioFile_Format_name = map[int32]string{
	0:  "OGG_VORBIS_96",
	1:  "OGG_VORBIS_160",
	2:  "OGG_VORBIS_320",
	3:  "MP3_256",
	4:  "MP3_320",
	5:  "MP3_160",
	6:  "MP3_96",
	7:  "MP3_160_ENC",
	8:  "OTHER2",
	9:  "OTHER3",
	10: "AAC_160",
	11: "AAC_320",
	12: "OTHER4",
	13: "OTHER5",
}

var AudioFile_Format_value = map[string]int32{
	"OGG_VORBIS_96":  0,
	"OGG_VORBIS_160": 1,
	"OGG_VORBIS_320": 2,
	"MP3_256":        3,
	"MP3_320":        4,
	"MP3_160":        5,
	"MP3_96":         6,
	"MP3_160_ENC":    7,
	"OTHER2":         8,
	"OTHER3":         9,
	"AAC_160":        10,
	"AAC_320":        11,
	"OTHER4":         12,
	"OTHER5":         13,
}

func (x AudioFile_Format) Enum() *AudioFile_Format {
	p := new(AudioFile_Format)
	*p = x
	return p
}

func (x AudioFile_Format) String() string {
	return proto.EnumName(AudioFile_Format_name, int32(x))
}

func (x *AudioFile_Format) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AudioFile_Format_value, data, "AudioFile_Format")
	if err != nil {
		return err
	}
	*x = AudioFile_Format(value)
	return nil
}

func (AudioFile_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{15, 0}
}

type TopTracks struct {
	Country              *string  `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	Track                []*Track `protobuf:"bytes,2,rep,name=track" json:"track,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopTracks) Reset()         { *m = TopTracks{} }
func (m *TopTracks) String() string { return proto.CompactTextString(m) }
func (*TopTracks) ProtoMessage()    {}
func (*TopTracks) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *TopTracks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopTracks.Unmarshal(m, b)
}
func (m *TopTracks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopTracks.Marshal(b, m, deterministic)
}
func (m *TopTracks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopTracks.Merge(m, src)
}
func (m *TopTracks) XXX_Size() int {
	return xxx_messageInfo_TopTracks.Size(m)
}
func (m *TopTracks) XXX_DiscardUnknown() {
	xxx_messageInfo_TopTracks.DiscardUnknown(m)
}

var xxx_messageInfo_TopTracks proto.InternalMessageInfo

func (m *TopTracks) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

func (m *TopTracks) GetTrack() []*Track {
	if m != nil {
		return m.Track
	}
	return nil
}

type ActivityPeriod struct {
	StartYear            *int32   `protobuf:"zigzag32,1,opt,name=start_year,json=startYear" json:"start_year,omitempty"`
	EndYear              *int32   `protobuf:"zigzag32,2,opt,name=end_year,json=endYear" json:"end_year,omitempty"`
	Decade               *int32   `protobuf:"zigzag32,3,opt,name=decade" json:"decade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityPeriod) Reset()         { *m = ActivityPeriod{} }
func (m *ActivityPeriod) String() string { return proto.CompactTextString(m) }
func (*ActivityPeriod) ProtoMessage()    {}
func (*ActivityPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *ActivityPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityPeriod.Unmarshal(m, b)
}
func (m *ActivityPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityPeriod.Marshal(b, m, deterministic)
}
func (m *ActivityPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityPeriod.Merge(m, src)
}
func (m *ActivityPeriod) XXX_Size() int {
	return xxx_messageInfo_ActivityPeriod.Size(m)
}
func (m *ActivityPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityPeriod proto.InternalMessageInfo

func (m *ActivityPeriod) GetStartYear() int32 {
	if m != nil && m.StartYear != nil {
		return *m.StartYear
	}
	return 0
}

func (m *ActivityPeriod) GetEndYear() int32 {
	if m != nil && m.EndYear != nil {
		return *m.EndYear
	}
	return 0
}

func (m *ActivityPeriod) GetDecade() int32 {
	if m != nil && m.Decade != nil {
		return *m.Decade
	}
	return 0
}

type Artist struct {
	Gid                  []byte            `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Name                 *string           `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Popularity           *int32            `protobuf:"zigzag32,3,opt,name=popularity" json:"popularity,omitempty"`
	TopTrack             []*TopTracks      `protobuf:"bytes,4,rep,name=top_track,json=topTrack" json:"top_track,omitempty"`
	AlbumGroup           []*AlbumGroup     `protobuf:"bytes,5,rep,name=album_group,json=albumGroup" json:"album_group,omitempty"`
	SingleGroup          []*AlbumGroup     `protobuf:"bytes,6,rep,name=single_group,json=singleGroup" json:"single_group,omitempty"`
	CompilationGroup     []*AlbumGroup     `protobuf:"bytes,7,rep,name=compilation_group,json=compilationGroup" json:"compilation_group,omitempty"`
	AppearsOnGroup       []*AlbumGroup     `protobuf:"bytes,8,rep,name=appears_on_group,json=appearsOnGroup" json:"appears_on_group,omitempty"`
	Genre                []string          `protobuf:"bytes,9,rep,name=genre" json:"genre,omitempty"`
	ExternalId           []*ExternalID     `protobuf:"bytes,10,rep,name=external_id,json=externalId" json:"external_id,omitempty"`
	Portrait             []*Image          `protobuf:"bytes,11,rep,name=portrait" json:"portrait,omitempty"`
	Biography            []*Biography      `protobuf:"bytes,12,rep,name=biography" json:"biography,omitempty"`
	ActivityPeriod       []*ActivityPeriod `protobuf:"bytes,13,rep,name=activity_period,json=activityPeriod" json:"activity_period,omitempty"`
	Restriction          []*Restriction    `protobuf:"bytes,14,rep,name=restriction" json:"restriction,omitempty"`
	Related              []*Artist         `protobuf:"bytes,15,rep,name=related" json:"related,omitempty"`
	IsPortraitAlbumCover *bool             `protobuf:"varint,16,opt,name=is_portrait_album_cover,json=isPortraitAlbumCover" json:"is_portrait_album_cover,omitempty"`
	PortraitGroup        *ImageGroup       `protobuf:"bytes,17,opt,name=portrait_group,json=portraitGroup" json:"portrait_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Artist) Reset()         { *m = Artist{} }
func (m *Artist) String() string { return proto.CompactTextString(m) }
func (*Artist) ProtoMessage()    {}
func (*Artist) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

func (m *Artist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artist.Unmarshal(m, b)
}
func (m *Artist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artist.Marshal(b, m, deterministic)
}
func (m *Artist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artist.Merge(m, src)
}
func (m *Artist) XXX_Size() int {
	return xxx_messageInfo_Artist.Size(m)
}
func (m *Artist) XXX_DiscardUnknown() {
	xxx_messageInfo_Artist.DiscardUnknown(m)
}

var xxx_messageInfo_Artist proto.InternalMessageInfo

func (m *Artist) GetGid() []byte {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *Artist) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Artist) GetPopularity() int32 {
	if m != nil && m.Popularity != nil {
		return *m.Popularity
	}
	return 0
}

func (m *Artist) GetTopTrack() []*TopTracks {
	if m != nil {
		return m.TopTrack
	}
	return nil
}

func (m *Artist) GetAlbumGroup() []*AlbumGroup {
	if m != nil {
		return m.AlbumGroup
	}
	return nil
}

func (m *Artist) GetSingleGroup() []*AlbumGroup {
	if m != nil {
		return m.SingleGroup
	}
	return nil
}

func (m *Artist) GetCompilationGroup() []*AlbumGroup {
	if m != nil {
		return m.CompilationGroup
	}
	return nil
}

func (m *Artist) GetAppearsOnGroup() []*AlbumGroup {
	if m != nil {
		return m.AppearsOnGroup
	}
	return nil
}

func (m *Artist) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *Artist) GetExternalId() []*ExternalID {
	if m != nil {
		return m.ExternalId
	}
	return nil
}

func (m *Artist) GetPortrait() []*Image {
	if m != nil {
		return m.Portrait
	}
	return nil
}

func (m *Artist) GetBiography() []*Biography {
	if m != nil {
		return m.Biography
	}
	return nil
}

func (m *Artist) GetActivityPeriod() []*ActivityPeriod {
	if m != nil {
		return m.ActivityPeriod
	}
	return nil
}

func (m *Artist) GetRestriction() []*Restriction {
	if m != nil {
		return m.Restriction
	}
	return nil
}

func (m *Artist) GetRelated() []*Artist {
	if m != nil {
		return m.Related
	}
	return nil
}

func (m *Artist) GetIsPortraitAlbumCover() bool {
	if m != nil && m.IsPortraitAlbumCover != nil {
		return *m.IsPortraitAlbumCover
	}
	return false
}

func (m *Artist) GetPortraitGroup() *ImageGroup {
	if m != nil {
		return m.PortraitGroup
	}
	return nil
}

type AlbumGroup struct {
	Album                []*Album `protobuf:"bytes,1,rep,name=album" json:"album,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlbumGroup) Reset()         { *m = AlbumGroup{} }
func (m *AlbumGroup) String() string { return proto.CompactTextString(m) }
func (*AlbumGroup) ProtoMessage()    {}
func (*AlbumGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{3}
}

func (m *AlbumGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumGroup.Unmarshal(m, b)
}
func (m *AlbumGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumGroup.Marshal(b, m, deterministic)
}
func (m *AlbumGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumGroup.Merge(m, src)
}
func (m *AlbumGroup) XXX_Size() int {
	return xxx_messageInfo_AlbumGroup.Size(m)
}
func (m *AlbumGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumGroup proto.InternalMessageInfo

func (m *AlbumGroup) GetAlbum() []*Album {
	if m != nil {
		return m.Album
	}
	return nil
}

type Date struct {
	Year                 *int32   `protobuf:"zigzag32,1,opt,name=year" json:"year,omitempty"`
	Month                *int32   `protobuf:"zigzag32,2,opt,name=month" json:"month,omitempty"`
	Day                  *int32   `protobuf:"zigzag32,3,opt,name=day" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{4}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil && m.Year != nil {
		return *m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil && m.Month != nil {
		return *m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil && m.Day != nil {
		return *m.Day
	}
	return 0
}

type Album struct {
	Gid                  []byte         `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Name                 *string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Artist               []*Artist      `protobuf:"bytes,3,rep,name=artist" json:"artist,omitempty"`
	Typ                  *Album_Type    `protobuf:"varint,4,opt,name=typ,enum=spotify.Album_Type" json:"typ,omitempty"`
	Label                *string        `protobuf:"bytes,5,opt,name=label" json:"label,omitempty"`
	Date                 *Date          `protobuf:"bytes,6,opt,name=date" json:"date,omitempty"`
	Popularity           *int32         `protobuf:"zigzag32,7,opt,name=popularity" json:"popularity,omitempty"`
	Genre                []string       `protobuf:"bytes,8,rep,name=genre" json:"genre,omitempty"`
	Cover                []*Image       `protobuf:"bytes,9,rep,name=cover" json:"cover,omitempty"`
	ExternalId           []*ExternalID  `protobuf:"bytes,10,rep,name=external_id,json=externalId" json:"external_id,omitempty"`
	Disc                 []*Disc        `protobuf:"bytes,11,rep,name=disc" json:"disc,omitempty"`
	Review               []string       `protobuf:"bytes,12,rep,name=review" json:"review,omitempty"`
	Copyright            []*Copyright   `protobuf:"bytes,13,rep,name=copyright" json:"copyright,omitempty"`
	Restriction          []*Restriction `protobuf:"bytes,14,rep,name=restriction" json:"restriction,omitempty"`
	Related              []*Album       `protobuf:"bytes,15,rep,name=related" json:"related,omitempty"`
	SalePeriod           []*SalePeriod  `protobuf:"bytes,16,rep,name=sale_period,json=salePeriod" json:"sale_period,omitempty"`
	CoverGroup           *ImageGroup    `protobuf:"bytes,17,opt,name=cover_group,json=coverGroup" json:"cover_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Album) Reset()         { *m = Album{} }
func (m *Album) String() string { return proto.CompactTextString(m) }
func (*Album) ProtoMessage()    {}
func (*Album) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{5}
}

func (m *Album) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Album.Unmarshal(m, b)
}
func (m *Album) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Album.Marshal(b, m, deterministic)
}
func (m *Album) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Album.Merge(m, src)
}
func (m *Album) XXX_Size() int {
	return xxx_messageInfo_Album.Size(m)
}
func (m *Album) XXX_DiscardUnknown() {
	xxx_messageInfo_Album.DiscardUnknown(m)
}

var xxx_messageInfo_Album proto.InternalMessageInfo

func (m *Album) GetGid() []byte {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *Album) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Album) GetArtist() []*Artist {
	if m != nil {
		return m.Artist
	}
	return nil
}

func (m *Album) GetTyp() Album_Type {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return Album_ALBUM
}

func (m *Album) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Album) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Album) GetPopularity() int32 {
	if m != nil && m.Popularity != nil {
		return *m.Popularity
	}
	return 0
}

func (m *Album) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *Album) GetCover() []*Image {
	if m != nil {
		return m.Cover
	}
	return nil
}

func (m *Album) GetExternalId() []*ExternalID {
	if m != nil {
		return m.ExternalId
	}
	return nil
}

func (m *Album) GetDisc() []*Disc {
	if m != nil {
		return m.Disc
	}
	return nil
}

func (m *Album) GetReview() []string {
	if m != nil {
		return m.Review
	}
	return nil
}

func (m *Album) GetCopyright() []*Copyright {
	if m != nil {
		return m.Copyright
	}
	return nil
}

func (m *Album) GetRestriction() []*Restriction {
	if m != nil {
		return m.Restriction
	}
	return nil
}

func (m *Album) GetRelated() []*Album {
	if m != nil {
		return m.Related
	}
	return nil
}

func (m *Album) GetSalePeriod() []*SalePeriod {
	if m != nil {
		return m.SalePeriod
	}
	return nil
}

func (m *Album) GetCoverGroup() *ImageGroup {
	if m != nil {
		return m.CoverGroup
	}
	return nil
}

type Track struct {
	Gid                  []byte         `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Name                 *string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Album                *Album         `protobuf:"bytes,3,opt,name=album" json:"album,omitempty"`
	Artist               []*Artist      `protobuf:"bytes,4,rep,name=artist" json:"artist,omitempty"`
	Number               *int32         `protobuf:"zigzag32,5,opt,name=number" json:"number,omitempty"`
	DiscNumber           *int32         `protobuf:"zigzag32,6,opt,name=disc_number,json=discNumber" json:"disc_number,omitempty"`
	Duration             *int32         `protobuf:"zigzag32,7,opt,name=duration" json:"duration,omitempty"`
	Popularity           *int32         `protobuf:"zigzag32,8,opt,name=popularity" json:"popularity,omitempty"`
	Explicit             *bool          `protobuf:"varint,9,opt,name=explicit" json:"explicit,omitempty"`
	ExternalId           []*ExternalID  `protobuf:"bytes,10,rep,name=external_id,json=externalId" json:"external_id,omitempty"`
	Restriction          []*Restriction `protobuf:"bytes,11,rep,name=restriction" json:"restriction,omitempty"`
	File                 []*AudioFile   `protobuf:"bytes,12,rep,name=file" json:"file,omitempty"`
	Alternative          []*Track       `protobuf:"bytes,13,rep,name=alternative" json:"alternative,omitempty"`
	SalePeriod           []*SalePeriod  `protobuf:"bytes,14,rep,name=sale_period,json=salePeriod" json:"sale_period,omitempty"`
	Preview              []*AudioFile   `protobuf:"bytes,15,rep,name=preview" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{6}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetGid() []byte {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *Track) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Track) GetAlbum() *Album {
	if m != nil {
		return m.Album
	}
	return nil
}

func (m *Track) GetArtist() []*Artist {
	if m != nil {
		return m.Artist
	}
	return nil
}

func (m *Track) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *Track) GetDiscNumber() int32 {
	if m != nil && m.DiscNumber != nil {
		return *m.DiscNumber
	}
	return 0
}

func (m *Track) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *Track) GetPopularity() int32 {
	if m != nil && m.Popularity != nil {
		return *m.Popularity
	}
	return 0
}

func (m *Track) GetExplicit() bool {
	if m != nil && m.Explicit != nil {
		return *m.Explicit
	}
	return false
}

func (m *Track) GetExternalId() []*ExternalID {
	if m != nil {
		return m.ExternalId
	}
	return nil
}

func (m *Track) GetRestriction() []*Restriction {
	if m != nil {
		return m.Restriction
	}
	return nil
}

func (m *Track) GetFile() []*AudioFile {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Track) GetAlternative() []*Track {
	if m != nil {
		return m.Alternative
	}
	return nil
}

func (m *Track) GetSalePeriod() []*SalePeriod {
	if m != nil {
		return m.SalePeriod
	}
	return nil
}

func (m *Track) GetPreview() []*AudioFile {
	if m != nil {
		return m.Preview
	}
	return nil
}

type Image struct {
	FileId               []byte      `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	Size                 *Image_Size `protobuf:"varint,2,opt,name=size,enum=spotify.Image_Size" json:"size,omitempty"`
	Width                *int32      `protobuf:"zigzag32,3,opt,name=width" json:"width,omitempty"`
	Height               *int32      `protobuf:"zigzag32,4,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{7}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetFileId() []byte {
	if m != nil {
		return m.FileId
	}
	return nil
}

func (m *Image) GetSize() Image_Size {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return Image_DEFAULT
}

func (m *Image) GetWidth() int32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type ImageGroup struct {
	Image                []*Image `protobuf:"bytes,1,rep,name=image" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageGroup) Reset()         { *m = ImageGroup{} }
func (m *ImageGroup) String() string { return proto.CompactTextString(m) }
func (*ImageGroup) ProtoMessage()    {}
func (*ImageGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{8}
}

func (m *ImageGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageGroup.Unmarshal(m, b)
}
func (m *ImageGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageGroup.Marshal(b, m, deterministic)
}
func (m *ImageGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageGroup.Merge(m, src)
}
func (m *ImageGroup) XXX_Size() int {
	return xxx_messageInfo_ImageGroup.Size(m)
}
func (m *ImageGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ImageGroup proto.InternalMessageInfo

func (m *ImageGroup) GetImage() []*Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type Biography struct {
	Text                 *string       `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Portrait             []*Image      `protobuf:"bytes,2,rep,name=portrait" json:"portrait,omitempty"`
	PortraitGroup        []*ImageGroup `protobuf:"bytes,3,rep,name=portrait_group,json=portraitGroup" json:"portrait_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Biography) Reset()         { *m = Biography{} }
func (m *Biography) String() string { return proto.CompactTextString(m) }
func (*Biography) ProtoMessage()    {}
func (*Biography) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{9}
}

func (m *Biography) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Biography.Unmarshal(m, b)
}
func (m *Biography) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Biography.Marshal(b, m, deterministic)
}
func (m *Biography) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Biography.Merge(m, src)
}
func (m *Biography) XXX_Size() int {
	return xxx_messageInfo_Biography.Size(m)
}
func (m *Biography) XXX_DiscardUnknown() {
	xxx_messageInfo_Biography.DiscardUnknown(m)
}

var xxx_messageInfo_Biography proto.InternalMessageInfo

func (m *Biography) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Biography) GetPortrait() []*Image {
	if m != nil {
		return m.Portrait
	}
	return nil
}

func (m *Biography) GetPortraitGroup() []*ImageGroup {
	if m != nil {
		return m.PortraitGroup
	}
	return nil
}

type Disc struct {
	Number               *int32   `protobuf:"zigzag32,1,opt,name=number" json:"number,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Track                []*Track `protobuf:"bytes,3,rep,name=track" json:"track,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disc) Reset()         { *m = Disc{} }
func (m *Disc) String() string { return proto.CompactTextString(m) }
func (*Disc) ProtoMessage()    {}
func (*Disc) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{10}
}

func (m *Disc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disc.Unmarshal(m, b)
}
func (m *Disc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disc.Marshal(b, m, deterministic)
}
func (m *Disc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disc.Merge(m, src)
}
func (m *Disc) XXX_Size() int {
	return xxx_messageInfo_Disc.Size(m)
}
func (m *Disc) XXX_DiscardUnknown() {
	xxx_messageInfo_Disc.DiscardUnknown(m)
}

var xxx_messageInfo_Disc proto.InternalMessageInfo

func (m *Disc) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *Disc) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Disc) GetTrack() []*Track {
	if m != nil {
		return m.Track
	}
	return nil
}

type Copyright struct {
	Typ                  *Copyright_Type `protobuf:"varint,1,opt,name=typ,enum=spotify.Copyright_Type" json:"typ,omitempty"`
	Text                 *string         `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Copyright) Reset()         { *m = Copyright{} }
func (m *Copyright) String() string { return proto.CompactTextString(m) }
func (*Copyright) ProtoMessage()    {}
func (*Copyright) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{11}
}

func (m *Copyright) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Copyright.Unmarshal(m, b)
}
func (m *Copyright) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Copyright.Marshal(b, m, deterministic)
}
func (m *Copyright) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Copyright.Merge(m, src)
}
func (m *Copyright) XXX_Size() int {
	return xxx_messageInfo_Copyright.Size(m)
}
func (m *Copyright) XXX_DiscardUnknown() {
	xxx_messageInfo_Copyright.DiscardUnknown(m)
}

var xxx_messageInfo_Copyright proto.InternalMessageInfo

func (m *Copyright) GetTyp() Copyright_Type {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return Copyright_P
}

func (m *Copyright) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type Restriction struct {
	CountriesAllowed     *string           `protobuf:"bytes,2,opt,name=countries_allowed,json=countriesAllowed" json:"countries_allowed,omitempty"`
	CountriesForbidden   *string           `protobuf:"bytes,3,opt,name=countries_forbidden,json=countriesForbidden" json:"countries_forbidden,omitempty"`
	Typ                  *Restriction_Type `protobuf:"varint,4,opt,name=typ,enum=spotify.Restriction_Type" json:"typ,omitempty"`
	CatalogueStr         []string          `protobuf:"bytes,5,rep,name=catalogue_str,json=catalogueStr" json:"catalogue_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Restriction) Reset()         { *m = Restriction{} }
func (m *Restriction) String() string { return proto.CompactTextString(m) }
func (*Restriction) ProtoMessage()    {}
func (*Restriction) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{12}
}

func (m *Restriction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restriction.Unmarshal(m, b)
}
func (m *Restriction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restriction.Marshal(b, m, deterministic)
}
func (m *Restriction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restriction.Merge(m, src)
}
func (m *Restriction) XXX_Size() int {
	return xxx_messageInfo_Restriction.Size(m)
}
func (m *Restriction) XXX_DiscardUnknown() {
	xxx_messageInfo_Restriction.DiscardUnknown(m)
}

var xxx_messageInfo_Restriction proto.InternalMessageInfo

func (m *Restriction) GetCountriesAllowed() string {
	if m != nil && m.CountriesAllowed != nil {
		return *m.CountriesAllowed
	}
	return ""
}

func (m *Restriction) GetCountriesForbidden() string {
	if m != nil && m.CountriesForbidden != nil {
		return *m.CountriesForbidden
	}
	return ""
}

func (m *Restriction) GetTyp() Restriction_Type {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return Restriction_STREAMING
}

func (m *Restriction) GetCatalogueStr() []string {
	if m != nil {
		return m.CatalogueStr
	}
	return nil
}

type SalePeriod struct {
	Restriction          []*Restriction `protobuf:"bytes,1,rep,name=restriction" json:"restriction,omitempty"`
	Start                *Date          `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	End                  *Date          `protobuf:"bytes,3,opt,name=end" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SalePeriod) Reset()         { *m = SalePeriod{} }
func (m *SalePeriod) String() string { return proto.CompactTextString(m) }
func (*SalePeriod) ProtoMessage()    {}
func (*SalePeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{13}
}

func (m *SalePeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SalePeriod.Unmarshal(m, b)
}
func (m *SalePeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SalePeriod.Marshal(b, m, deterministic)
}
func (m *SalePeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SalePeriod.Merge(m, src)
}
func (m *SalePeriod) XXX_Size() int {
	return xxx_messageInfo_SalePeriod.Size(m)
}
func (m *SalePeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_SalePeriod.DiscardUnknown(m)
}

var xxx_messageInfo_SalePeriod proto.InternalMessageInfo

func (m *SalePeriod) GetRestriction() []*Restriction {
	if m != nil {
		return m.Restriction
	}
	return nil
}

func (m *SalePeriod) GetStart() *Date {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *SalePeriod) GetEnd() *Date {
	if m != nil {
		return m.End
	}
	return nil
}

type ExternalID struct {
	Typ                  *string  `protobuf:"bytes,1,opt,name=typ" json:"typ,omitempty"`
	Id                   *string  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalID) Reset()         { *m = ExternalID{} }
func (m *ExternalID) String() string { return proto.CompactTextString(m) }
func (*ExternalID) ProtoMessage()    {}
func (*ExternalID) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{14}
}

func (m *ExternalID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalID.Unmarshal(m, b)
}
func (m *ExternalID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalID.Marshal(b, m, deterministic)
}
func (m *ExternalID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalID.Merge(m, src)
}
func (m *ExternalID) XXX_Size() int {
	return xxx_messageInfo_ExternalID.Size(m)
}
func (m *ExternalID) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalID.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalID proto.InternalMessageInfo

func (m *ExternalID) GetTyp() string {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return ""
}

func (m *ExternalID) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type AudioFile struct {
	FileId               []byte            `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	Format               *AudioFile_Format `protobuf:"varint,2,opt,name=format,enum=spotify.AudioFile_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AudioFile) Reset()         { *m = AudioFile{} }
func (m *AudioFile) String() string { return proto.CompactTextString(m) }
func (*AudioFile) ProtoMessage()    {}
func (*AudioFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{15}
}

func (m *AudioFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioFile.Unmarshal(m, b)
}
func (m *AudioFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioFile.Marshal(b, m, deterministic)
}
func (m *AudioFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioFile.Merge(m, src)
}
func (m *AudioFile) XXX_Size() int {
	return xxx_messageInfo_AudioFile.Size(m)
}
func (m *AudioFile) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioFile.DiscardUnknown(m)
}

var xxx_messageInfo_AudioFile proto.InternalMessageInfo

func (m *AudioFile) GetFileId() []byte {
	if m != nil {
		return m.FileId
	}
	return nil
}

func (m *AudioFile) GetFormat() AudioFile_Format {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return AudioFile_OGG_VORBIS_96
}

func init() {
	proto.RegisterEnum("spotify.Album_Type", Album_Type_name, Album_Type_value)
	proto.RegisterEnum("spotify.Image_Size", Image_Size_name, Image_Size_value)
	proto.RegisterEnum("spotify.Copyright_Type", Copyright_Type_name, Copyright_Type_value)
	proto.RegisterEnum("spotify.Restriction_Type", Restriction_Type_name, Restriction_Type_value)
	proto.RegisterEnum("spotify.AudioFile_Format", AudioFile_Format_name, AudioFile_Format_value)
	proto.RegisterType((*TopTracks)(nil), "spotify.TopTracks")
	proto.RegisterType((*ActivityPeriod)(nil), "spotify.ActivityPeriod")
	proto.RegisterType((*Artist)(nil), "spotify.Artist")
	proto.RegisterType((*AlbumGroup)(nil), "spotify.AlbumGroup")
	proto.RegisterType((*Date)(nil), "spotify.Date")
	proto.RegisterType((*Album)(nil), "spotify.Album")
	proto.RegisterType((*Track)(nil), "spotify.Track")
	proto.RegisterType((*Image)(nil), "spotify.Image")
	proto.RegisterType((*ImageGroup)(nil), "spotify.ImageGroup")
	proto.RegisterType((*Biography)(nil), "spotify.Biography")
	proto.RegisterType((*Disc)(nil), "spotify.Disc")
	proto.RegisterType((*Copyright)(nil), "spotify.Copyright")
	proto.RegisterType((*Restriction)(nil), "spotify.Restriction")
	proto.RegisterType((*SalePeriod)(nil), "spotify.SalePeriod")
	proto.RegisterType((*ExternalID)(nil), "spotify.ExternalID")
	proto.RegisterType((*AudioFile)(nil), "spotify.AudioFile")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 1433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x36, 0x25, 0x8a, 0x12, 0x47, 0xb6, 0x4c, 0x6f, 0x7c, 0x62, 0x26, 0xc0, 0x39, 0xf1, 0x61,
	0xd2, 0xc6, 0x69, 0x0a, 0xc7, 0x71, 0x62, 0x03, 0x29, 0x50, 0x20, 0xf2, 0x6f, 0x85, 0xfa, 0x0f,
	0x2b, 0xa5, 0x48, 0xaf, 0xd8, 0xb5, 0xb8, 0x96, 0x17, 0xa5, 0x44, 0x82, 0x5c, 0x39, 0x51, 0x5e,
	0xa0, 0x40, 0x5f, 0xa5, 0x40, 0xd1, 0xdb, 0xa2, 0x4f, 0x51, 0xa0, 0x0f, 0x54, 0xec, 0x0f, 0x29,
	0x99, 0xb2, 0x12, 0x23, 0x57, 0xde, 0xd9, 0x6f, 0x66, 0xc4, 0x9d, 0xfd, 0xbe, 0x99, 0x35, 0x34,
	0xfa, 0x94, 0x93, 0x80, 0x70, 0xb2, 0x1e, 0x27, 0x11, 0x8f, 0x50, 0x35, 0x8d, 0x23, 0xce, 0x2e,
	0x46, 0xde, 0xf7, 0x60, 0x77, 0xa2, 0xb8, 0x93, 0x90, 0xee, 0xcf, 0x29, 0x72, 0xa1, 0xda, 0x8d,
	0x86, 0x03, 0x9e, 0x8c, 0x5c, 0x63, 0xd5, 0x58, 0xb3, 0x71, 0x66, 0xa2, 0x47, 0x50, 0xe1, 0xc2,
	0xc7, 0x2d, 0xad, 0x96, 0xd7, 0xea, 0x9b, 0x8d, 0x75, 0x1d, 0xbf, 0x2e, 0x23, 0xb1, 0x02, 0xbd,
	0x73, 0x68, 0x34, 0xbb, 0x9c, 0x5d, 0x31, 0x3e, 0x3a, 0xa3, 0x09, 0x8b, 0x02, 0xf4, 0x5f, 0x80,
	0x94, 0x93, 0x84, 0xfb, 0x23, 0x4a, 0x12, 0x99, 0x74, 0x09, 0xdb, 0x72, 0xe7, 0x47, 0x4a, 0x12,
	0x74, 0x0f, 0x6a, 0x74, 0x10, 0x28, 0xb0, 0x24, 0xc1, 0x2a, 0x1d, 0x04, 0x12, 0xba, 0x0b, 0x56,
	0x40, 0xbb, 0x24, 0xa0, 0x6e, 0x59, 0x02, 0xda, 0xf2, 0xfe, 0xb0, 0xc0, 0x6a, 0x26, 0x9c, 0xa5,
	0x1c, 0x39, 0x50, 0xee, 0xb1, 0x40, 0x66, 0x9d, 0xc7, 0x62, 0x89, 0x10, 0x98, 0x03, 0xd2, 0xa7,
	0x32, 0x97, 0x8d, 0xe5, 0x1a, 0xfd, 0x0f, 0x20, 0x8e, 0xe2, 0x61, 0x48, 0x12, 0xc6, 0x47, 0x3a,
	0xd9, 0xc4, 0x0e, 0x7a, 0x06, 0x36, 0x8f, 0x62, 0x5f, 0x1d, 0xcf, 0x94, 0xc7, 0x43, 0xe3, 0xe3,
	0x65, 0xb5, 0xc1, 0x35, 0xae, 0x97, 0xe8, 0x25, 0xd4, 0x49, 0x78, 0x3e, 0xec, 0xfb, 0xbd, 0x24,
	0x1a, 0xc6, 0x6e, 0x45, 0x86, 0xdc, 0xc9, 0x43, 0x9a, 0x02, 0x3b, 0x14, 0x10, 0x06, 0x92, 0xaf,
	0xd1, 0x36, 0xcc, 0xa7, 0x6c, 0xd0, 0x0b, 0xa9, 0x0e, 0xb3, 0x66, 0x87, 0xd5, 0x95, 0xa3, 0x8a,
	0x7b, 0x0d, 0x4b, 0xdd, 0xa8, 0x1f, 0xb3, 0x90, 0x70, 0x16, 0x0d, 0x74, 0x70, 0x75, 0x76, 0xb0,
	0x33, 0xe1, 0xad, 0x32, 0x7c, 0x0b, 0x0e, 0x89, 0x63, 0x4a, 0x92, 0xd4, 0xcf, 0x13, 0xd4, 0x66,
	0x27, 0x68, 0x68, 0xe7, 0x53, 0x1d, 0xbe, 0x0c, 0x95, 0x1e, 0x1d, 0x24, 0xd4, 0xb5, 0x57, 0xcb,
	0x6b, 0x36, 0x56, 0x86, 0x28, 0x02, 0x7d, 0xcf, 0x69, 0x32, 0x20, 0xa1, 0xcf, 0x02, 0x17, 0x0a,
	0xf9, 0xf6, 0x35, 0xd6, 0xda, 0xc3, 0x90, 0xf9, 0xb5, 0x02, 0xf4, 0x15, 0xd4, 0xe2, 0x28, 0xe1,
	0x09, 0x61, 0xdc, 0xad, 0x17, 0x98, 0xd4, 0xea, 0x93, 0x1e, 0xc5, 0x39, 0x8e, 0x36, 0xc0, 0x3e,
	0x67, 0x51, 0x2f, 0x21, 0xf1, 0xe5, 0xc8, 0x9d, 0x2f, 0xdc, 0xcb, 0x4e, 0x86, 0xe0, 0xb1, 0x13,
	0x7a, 0x0d, 0x8b, 0x44, 0xd3, 0xcf, 0x8f, 0x25, 0xff, 0xdc, 0x05, 0x19, 0xb7, 0x32, 0x3e, 0xe7,
	0x35, 0x7a, 0xe2, 0x06, 0xb9, 0x4e, 0xd7, 0x6d, 0xa8, 0x27, 0x34, 0xe5, 0x09, 0xeb, 0x8a, 0xf2,
	0xb9, 0x0d, 0x19, 0xbd, 0x9c, 0x47, 0xe3, 0x31, 0x86, 0x27, 0x1d, 0xd1, 0x13, 0xa8, 0x26, 0x34,
	0x24, 0x9c, 0x06, 0xee, 0xa2, 0x8c, 0x59, 0x1c, 0xff, 0xa2, 0xe4, 0x2a, 0xce, 0x70, 0xb4, 0x05,
	0x2b, 0x2c, 0xf5, 0xb3, 0x53, 0xfa, 0x8a, 0x49, 0xdd, 0xe8, 0x8a, 0x26, 0xae, 0xb3, 0x6a, 0xac,
	0xd5, 0xf0, 0x32, 0x4b, 0xcf, 0x34, 0x2a, 0x6f, 0x65, 0x57, 0x60, 0xe8, 0x1b, 0x68, 0xe4, 0x31,
	0xea, 0x0a, 0x97, 0x56, 0x8d, 0x6b, 0x25, 0x97, 0xf5, 0x53, 0x57, 0xb8, 0x90, 0xb9, 0x4a, 0xd3,
	0xdb, 0x04, 0x18, 0xdf, 0xaf, 0x90, 0xb2, 0xfc, 0x51, 0xd7, 0x28, 0x5c, 0x80, 0xf4, 0xc1, 0x0a,
	0xf4, 0x76, 0xc0, 0xdc, 0x23, 0x9c, 0x0a, 0x45, 0x4d, 0x48, 0x57, 0xae, 0x05, 0x23, 0xfa, 0xd1,
	0x80, 0x5f, 0x6a, 0xc9, 0x2a, 0x43, 0xa8, 0x31, 0x20, 0x99, 0xc0, 0xc4, 0xd2, 0xfb, 0xab, 0x02,
	0x15, 0x99, 0xf4, 0x96, 0x4a, 0x7d, 0x0c, 0x16, 0x91, 0xd5, 0x72, 0xcb, 0x37, 0x17, 0x51, 0xc3,
	0xe8, 0x0b, 0x28, 0xf3, 0x51, 0xec, 0x9a, 0xab, 0xc6, 0x5a, 0xa3, 0x48, 0xe2, 0xf5, 0xce, 0x28,
	0xa6, 0x58, 0xe0, 0xe2, 0x3b, 0x43, 0x72, 0x4e, 0x43, 0xb7, 0x22, 0x7f, 0x44, 0x19, 0xe8, 0xff,
	0x60, 0x06, 0x84, 0x53, 0xd7, 0x92, 0xf5, 0x5b, 0xc8, 0xa3, 0xc5, 0x71, 0xb1, 0x84, 0x0a, 0x2d,
	0xa3, 0x3a, 0xd5, 0x32, 0x72, 0x49, 0xd4, 0x26, 0x25, 0xf1, 0x08, 0x2a, 0xea, 0x1e, 0xed, 0x1b,
	0x99, 0xad, 0xc0, 0xcf, 0x14, 0x8e, 0xf8, 0x68, 0x96, 0x76, 0xb5, 0x68, 0x26, 0x3e, 0x9a, 0xa5,
	0x5d, 0x2c, 0x21, 0xd1, 0x30, 0x13, 0x7a, 0xc5, 0xe8, 0x3b, 0x29, 0x16, 0x1b, 0x6b, 0x4b, 0xe8,
	0xa8, 0x1b, 0xc5, 0xa3, 0x84, 0xf5, 0x2e, 0xb9, 0xd6, 0xc3, 0x58, 0x47, 0xbb, 0x19, 0x82, 0xc7,
	0x4e, 0x9f, 0xad, 0x82, 0xb5, 0xa2, 0x0a, 0x8a, 0xdc, 0xca, 0x45, 0xf0, 0x12, 0xea, 0x29, 0x09,
	0x69, 0xa6, 0x52, 0xa7, 0x50, 0x84, 0x36, 0x09, 0xa9, 0x56, 0x28, 0xa4, 0xf9, 0x5a, 0x44, 0xc9,
	0x1a, 0x7e, 0x5a, 0x00, 0x20, 0xfd, 0x14, 0xfb, 0xb7, 0xc1, 0x14, 0x94, 0x40, 0x36, 0x54, 0x9a,
	0x47, 0x3b, 0x6f, 0x8e, 0x1d, 0x03, 0x01, 0x58, 0xed, 0xd6, 0xc9, 0xe1, 0xd1, 0xbe, 0x53, 0x42,
	0x8b, 0x50, 0xdf, 0x3d, 0x3d, 0x3e, 0x6b, 0x1d, 0x35, 0x3b, 0xad, 0xd3, 0x13, 0xa7, 0x8c, 0x2c,
	0x28, 0xed, 0x9f, 0x39, 0xa6, 0xf7, 0xa7, 0x09, 0x15, 0xd5, 0xf0, 0x6f, 0xc7, 0xde, 0x5c, 0x57,
	0x65, 0xf9, 0x5d, 0x37, 0xeb, 0x6a, 0x82, 0xe3, 0xe6, 0xc7, 0x39, 0x7e, 0x17, 0xac, 0xc1, 0xb0,
	0x7f, 0x4e, 0x13, 0xc9, 0xde, 0x25, 0xac, 0x2d, 0xf4, 0x00, 0xea, 0xe2, 0xba, 0x7d, 0x0d, 0x5a,
	0x8a, 0x9c, 0x62, 0xeb, 0x44, 0x39, 0xdc, 0x87, 0x5a, 0x30, 0x4c, 0x64, 0xff, 0xd7, 0xd4, 0xcd,
	0xed, 0x02, 0xb1, 0x6b, 0x53, 0xc4, 0xbe, 0x0f, 0x35, 0xfa, 0x3e, 0x0e, 0x59, 0x97, 0x71, 0xd7,
	0x96, 0xdd, 0x28, 0xb7, 0x3f, 0x93, 0xb8, 0x05, 0x2e, 0xd5, 0x6f, 0xcb, 0xa5, 0x2f, 0xc1, 0xbc,
	0x60, 0x21, 0x9d, 0x6a, 0xfc, 0xcd, 0x61, 0xc0, 0xa2, 0x03, 0x16, 0x52, 0x2c, 0x71, 0xb4, 0x21,
	0x86, 0xb1, 0xfc, 0x35, 0xce, 0xae, 0xa8, 0xe6, 0x77, 0xf1, 0x79, 0x32, 0xe9, 0x52, 0xe4, 0x5e,
	0xe3, 0x76, 0xdc, 0xfb, 0x1a, 0xaa, 0xb1, 0x96, 0xd7, 0xe2, 0xcc, 0x4f, 0xca, 0x5c, 0xbc, 0xdf,
	0x0d, 0xa8, 0x48, 0x3a, 0xa2, 0x15, 0xa8, 0x8a, 0xef, 0xf4, 0x73, 0xfe, 0x58, 0xc2, 0x6c, 0x05,
	0xe8, 0x31, 0x98, 0x29, 0xfb, 0xa0, 0x28, 0xd4, 0x28, 0xb2, 0x78, 0xbd, 0xcd, 0x3e, 0x50, 0x2c,
	0x1d, 0x44, 0xb3, 0x79, 0xc7, 0x02, 0x7e, 0xa9, 0x3b, 0xab, 0x32, 0x04, 0x3d, 0x2e, 0xa9, 0x94,
	0xb4, 0xa9, 0xe8, 0xa1, 0x2c, 0x6f, 0x0b, 0x4c, 0x11, 0x8b, 0xea, 0x50, 0xdd, 0xdb, 0x3f, 0x68,
	0xbe, 0x39, 0xea, 0x38, 0x73, 0x82, 0xfa, 0xed, 0xe3, 0xe6, 0xd1, 0x91, 0x63, 0x88, 0xe5, 0x51,
	0x13, 0x1f, 0x0a, 0xe6, 0x03, 0x58, 0x6f, 0xd5, 0xba, 0x2c, 0x46, 0xc4, 0x58, 0x3e, 0x82, 0xca,
	0x4c, 0x58, 0x53, 0x23, 0x42, 0x77, 0x32, 0x09, 0x7a, 0xbf, 0x18, 0x60, 0xe7, 0x73, 0x58, 0x48,
	0x82, 0xd3, 0xf7, 0x5c, 0x3f, 0x1c, 0xe5, 0xfa, 0xda, 0xb8, 0x2f, 0x7d, 0x62, 0xdc, 0x4f, 0x0f,
	0xb8, 0x72, 0xe1, 0x66, 0x66, 0x0f, 0xb8, 0xb7, 0x60, 0xee, 0xe9, 0x16, 0xa8, 0x65, 0x61, 0x5c,
	0xd3, 0xcc, 0x0c, 0xb9, 0xaa, 0x27, 0x5f, 0xf9, 0x63, 0x2f, 0xda, 0x9f, 0xc0, 0xce, 0x5b, 0x24,
	0x7a, 0xa2, 0xc6, 0x8e, 0x21, 0x6f, 0x6c, 0x65, 0xba, 0x87, 0x4e, 0x8c, 0x9e, 0xac, 0x1a, 0xa5,
	0x71, 0x35, 0xbc, 0x65, 0xdd, 0x88, 0x2a, 0x60, 0x9c, 0x39, 0x73, 0xe2, 0xcf, 0xae, 0x63, 0x78,
	0xff, 0x18, 0x50, 0x9f, 0x50, 0x01, 0x7a, 0x2a, 0xde, 0x7b, 0xe2, 0xd1, 0xcd, 0x68, 0xea, 0x93,
	0x30, 0x8c, 0xde, 0xd1, 0x40, 0xa7, 0x71, 0x72, 0xa0, 0xa9, 0xf6, 0xd1, 0x33, 0xb8, 0x33, 0x76,
	0xbe, 0x88, 0x92, 0x73, 0x16, 0x04, 0x74, 0x20, 0x99, 0x62, 0x63, 0x94, 0x43, 0x07, 0x19, 0x82,
	0x9e, 0x4e, 0x4e, 0xce, 0x7b, 0x37, 0xc9, 0x70, 0xe2, 0x10, 0x0f, 0x61, 0xa1, 0x4b, 0x38, 0x09,
	0xa3, 0xde, 0x90, 0xfa, 0x29, 0x4f, 0xe4, 0x53, 0xd7, 0xc6, 0xf3, 0xf9, 0x66, 0x9b, 0x27, 0xde,
	0x7f, 0xf4, 0xa9, 0x16, 0xc0, 0x6e, 0x77, 0xf0, 0x7e, 0xf3, 0xb8, 0x75, 0x72, 0xe8, 0xcc, 0x79,
	0xbf, 0x1a, 0x00, 0x63, 0x29, 0x15, 0xdb, 0x80, 0x71, 0xdb, 0x36, 0xf0, 0x10, 0x2a, 0xf2, 0xbf,
	0x05, 0x59, 0x81, 0xa9, 0x69, 0xad, 0x30, 0xf4, 0x00, 0xca, 0x74, 0x10, 0xe8, 0xbe, 0x5b, 0x70,
	0x11, 0x88, 0xb7, 0x0e, 0x30, 0x6e, 0x4f, 0xa2, 0x9d, 0x67, 0xd7, 0x68, 0xab, 0x83, 0x36, 0xa0,
	0xc4, 0xb2, 0x22, 0x97, 0x58, 0xe0, 0xfd, 0x56, 0x02, 0x3b, 0x57, 0xf5, 0x6c, 0x09, 0x3f, 0x07,
	0xeb, 0x22, 0x4a, 0xfa, 0x84, 0x6b, 0x11, 0xdf, 0x9b, 0x6e, 0x09, 0xeb, 0x07, 0xd2, 0x01, 0x6b,
	0x47, 0xef, 0x6f, 0x03, 0x2c, 0xb5, 0x85, 0x96, 0x60, 0xe1, 0xf4, 0xf0, 0xd0, 0xff, 0xe1, 0x14,
	0xef, 0xb4, 0xda, 0xfe, 0xab, 0x6d, 0x67, 0x0e, 0x21, 0x68, 0x4c, 0x6c, 0x3d, 0xdf, 0xde, 0x70,
	0x8c, 0xc2, 0xde, 0x8b, 0xcd, 0x0d, 0xa7, 0x24, 0xc4, 0x7d, 0x7c, 0xf6, 0xc2, 0xdf, 0xdc, 0xda,
	0x76, 0xca, 0x99, 0x21, 0x10, 0x33, 0x33, 0x44, 0x68, 0x45, 0x08, 0x5c, 0x18, 0xaf, 0xb6, 0x1d,
	0x4b, 0x8c, 0x39, 0x0d, 0xf8, 0xfb, 0x27, 0xbb, 0x4e, 0x55, 0x80, 0xa7, 0x9d, 0xef, 0xf6, 0xf1,
	0xa6, 0x53, 0xcb, 0xd7, 0x2f, 0x1c, 0x5b, 0x64, 0x68, 0x36, 0x77, 0x65, 0x06, 0xc8, 0x0c, 0x91,
	0xbb, 0x9e, 0x7b, 0xbd, 0x74, 0xe6, 0xf3, 0xf5, 0x96, 0xb3, 0xf0, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x06, 0x1a, 0xa9, 0x5e, 0x5c, 0x0e, 0x00, 0x00,
}
