// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playlist4changes.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeSet_Kind int32

const (
	ChangeSet_KIND_UNKNOWN ChangeSet_Kind = 0
	ChangeSet_DELTA        ChangeSet_Kind = 2
	ChangeSet_MERGE        ChangeSet_Kind = 3
)

var ChangeSet_Kind_name = map[int32]string{
	0: "KIND_UNKNOWN",
	2: "DELTA",
	3: "MERGE",
}

var ChangeSet_Kind_value = map[string]int32{
	"KIND_UNKNOWN": 0,
	"DELTA":        2,
	"MERGE":        3,
}

func (x ChangeSet_Kind) Enum() *ChangeSet_Kind {
	p := new(ChangeSet_Kind)
	*p = x
	return p
}

func (x ChangeSet_Kind) String() string {
	return proto.EnumName(ChangeSet_Kind_name, int32(x))
}

func (x *ChangeSet_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChangeSet_Kind_value, data, "ChangeSet_Kind")
	if err != nil {
		return err
	}
	*x = ChangeSet_Kind(value)
	return nil
}

func (ChangeSet_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{3, 0}
}

type ChangeInfo struct {
	User                 *string  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Timestamp            *int32   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Admin                *bool    `protobuf:"varint,3,opt,name=admin" json:"admin,omitempty"`
	Undo                 *bool    `protobuf:"varint,4,opt,name=undo" json:"undo,omitempty"`
	Redo                 *bool    `protobuf:"varint,5,opt,name=redo" json:"redo,omitempty"`
	Merge                *bool    `protobuf:"varint,6,opt,name=merge" json:"merge,omitempty"`
	Compressed           *bool    `protobuf:"varint,7,opt,name=compressed" json:"compressed,omitempty"`
	Migration            *bool    `protobuf:"varint,8,opt,name=migration" json:"migration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeInfo) Reset()         { *m = ChangeInfo{} }
func (m *ChangeInfo) String() string { return proto.CompactTextString(m) }
func (*ChangeInfo) ProtoMessage()    {}
func (*ChangeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{0}
}

func (m *ChangeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeInfo.Unmarshal(m, b)
}
func (m *ChangeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeInfo.Marshal(b, m, deterministic)
}
func (m *ChangeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeInfo.Merge(m, src)
}
func (m *ChangeInfo) XXX_Size() int {
	return xxx_messageInfo_ChangeInfo.Size(m)
}
func (m *ChangeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeInfo proto.InternalMessageInfo

func (m *ChangeInfo) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *ChangeInfo) GetTimestamp() int32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ChangeInfo) GetAdmin() bool {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return false
}

func (m *ChangeInfo) GetUndo() bool {
	if m != nil && m.Undo != nil {
		return *m.Undo
	}
	return false
}

func (m *ChangeInfo) GetRedo() bool {
	if m != nil && m.Redo != nil {
		return *m.Redo
	}
	return false
}

func (m *ChangeInfo) GetMerge() bool {
	if m != nil && m.Merge != nil {
		return *m.Merge
	}
	return false
}

func (m *ChangeInfo) GetCompressed() bool {
	if m != nil && m.Compressed != nil {
		return *m.Compressed
	}
	return false
}

func (m *ChangeInfo) GetMigration() bool {
	if m != nil && m.Migration != nil {
		return *m.Migration
	}
	return false
}

type Delta struct {
	BaseVersion          []byte      `protobuf:"bytes,1,opt,name=base_version,json=baseVersion" json:"base_version,omitempty"`
	Ops                  []*Op       `protobuf:"bytes,2,rep,name=ops" json:"ops,omitempty"`
	Info                 *ChangeInfo `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}
func (*Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{1}
}

func (m *Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delta.Unmarshal(m, b)
}
func (m *Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delta.Marshal(b, m, deterministic)
}
func (m *Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delta.Merge(m, src)
}
func (m *Delta) XXX_Size() int {
	return xxx_messageInfo_Delta.Size(m)
}
func (m *Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Delta proto.InternalMessageInfo

func (m *Delta) GetBaseVersion() []byte {
	if m != nil {
		return m.BaseVersion
	}
	return nil
}

func (m *Delta) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

func (m *Delta) GetInfo() *ChangeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Merge struct {
	BaseVersion          []byte      `protobuf:"bytes,1,opt,name=base_version,json=baseVersion" json:"base_version,omitempty"`
	MergeVersion         []byte      `protobuf:"bytes,2,opt,name=merge_version,json=mergeVersion" json:"merge_version,omitempty"`
	Info                 *ChangeInfo `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Merge) Reset()         { *m = Merge{} }
func (m *Merge) String() string { return proto.CompactTextString(m) }
func (*Merge) ProtoMessage()    {}
func (*Merge) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{2}
}

func (m *Merge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merge.Unmarshal(m, b)
}
func (m *Merge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merge.Marshal(b, m, deterministic)
}
func (m *Merge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merge.Merge(m, src)
}
func (m *Merge) XXX_Size() int {
	return xxx_messageInfo_Merge.Size(m)
}
func (m *Merge) XXX_DiscardUnknown() {
	xxx_messageInfo_Merge.DiscardUnknown(m)
}

var xxx_messageInfo_Merge proto.InternalMessageInfo

func (m *Merge) GetBaseVersion() []byte {
	if m != nil {
		return m.BaseVersion
	}
	return nil
}

func (m *Merge) GetMergeVersion() []byte {
	if m != nil {
		return m.MergeVersion
	}
	return nil
}

func (m *Merge) GetInfo() *ChangeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ChangeSet struct {
	Kind                 *ChangeSet_Kind `protobuf:"varint,1,opt,name=kind,enum=spotify.ChangeSet_Kind" json:"kind,omitempty"`
	Delta                *Delta          `protobuf:"bytes,2,opt,name=delta" json:"delta,omitempty"`
	Merge                *Merge          `protobuf:"bytes,3,opt,name=merge" json:"merge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChangeSet) Reset()         { *m = ChangeSet{} }
func (m *ChangeSet) String() string { return proto.CompactTextString(m) }
func (*ChangeSet) ProtoMessage()    {}
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{3}
}

func (m *ChangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSet.Unmarshal(m, b)
}
func (m *ChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSet.Marshal(b, m, deterministic)
}
func (m *ChangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSet.Merge(m, src)
}
func (m *ChangeSet) XXX_Size() int {
	return xxx_messageInfo_ChangeSet.Size(m)
}
func (m *ChangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSet proto.InternalMessageInfo

func (m *ChangeSet) GetKind() ChangeSet_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ChangeSet_KIND_UNKNOWN
}

func (m *ChangeSet) GetDelta() *Delta {
	if m != nil {
		return m.Delta
	}
	return nil
}

func (m *ChangeSet) GetMerge() *Merge {
	if m != nil {
		return m.Merge
	}
	return nil
}

type RevisionTaggedChangeSet struct {
	Revision             []byte     `protobuf:"bytes,1,opt,name=revision" json:"revision,omitempty"`
	ChangeSet            *ChangeSet `protobuf:"bytes,2,opt,name=change_set,json=changeSet" json:"change_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RevisionTaggedChangeSet) Reset()         { *m = RevisionTaggedChangeSet{} }
func (m *RevisionTaggedChangeSet) String() string { return proto.CompactTextString(m) }
func (*RevisionTaggedChangeSet) ProtoMessage()    {}
func (*RevisionTaggedChangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{4}
}

func (m *RevisionTaggedChangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevisionTaggedChangeSet.Unmarshal(m, b)
}
func (m *RevisionTaggedChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevisionTaggedChangeSet.Marshal(b, m, deterministic)
}
func (m *RevisionTaggedChangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevisionTaggedChangeSet.Merge(m, src)
}
func (m *RevisionTaggedChangeSet) XXX_Size() int {
	return xxx_messageInfo_RevisionTaggedChangeSet.Size(m)
}
func (m *RevisionTaggedChangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RevisionTaggedChangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_RevisionTaggedChangeSet proto.InternalMessageInfo

func (m *RevisionTaggedChangeSet) GetRevision() []byte {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *RevisionTaggedChangeSet) GetChangeSet() *ChangeSet {
	if m != nil {
		return m.ChangeSet
	}
	return nil
}

type Diff struct {
	FromRevision         []byte   `protobuf:"bytes,1,opt,name=from_revision,json=fromRevision" json:"from_revision,omitempty"`
	Ops                  []*Op    `protobuf:"bytes,2,rep,name=ops" json:"ops,omitempty"`
	ToRevision           []byte   `protobuf:"bytes,3,opt,name=to_revision,json=toRevision" json:"to_revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Diff) Reset()         { *m = Diff{} }
func (m *Diff) String() string { return proto.CompactTextString(m) }
func (*Diff) ProtoMessage()    {}
func (*Diff) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{5}
}

func (m *Diff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Diff.Unmarshal(m, b)
}
func (m *Diff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Diff.Marshal(b, m, deterministic)
}
func (m *Diff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Diff.Merge(m, src)
}
func (m *Diff) XXX_Size() int {
	return xxx_messageInfo_Diff.Size(m)
}
func (m *Diff) XXX_DiscardUnknown() {
	xxx_messageInfo_Diff.DiscardUnknown(m)
}

var xxx_messageInfo_Diff proto.InternalMessageInfo

func (m *Diff) GetFromRevision() []byte {
	if m != nil {
		return m.FromRevision
	}
	return nil
}

func (m *Diff) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

func (m *Diff) GetToRevision() []byte {
	if m != nil {
		return m.ToRevision
	}
	return nil
}

type ListDump struct {
	LatestRevision       []byte          `protobuf:"bytes,1,opt,name=latestRevision" json:"latestRevision,omitempty"`
	Length               *int32          `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Attributes           *ListAttributes `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Checksum             *ListChecksum   `protobuf:"bytes,4,opt,name=checksum" json:"checksum,omitempty"`
	Contents             *ListItems      `protobuf:"bytes,5,opt,name=contents" json:"contents,omitempty"`
	PendingDeltas        []*Delta        `protobuf:"bytes,7,rep,name=pendingDeltas" json:"pendingDeltas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListDump) Reset()         { *m = ListDump{} }
func (m *ListDump) String() string { return proto.CompactTextString(m) }
func (*ListDump) ProtoMessage()    {}
func (*ListDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{6}
}

func (m *ListDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDump.Unmarshal(m, b)
}
func (m *ListDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDump.Marshal(b, m, deterministic)
}
func (m *ListDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDump.Merge(m, src)
}
func (m *ListDump) XXX_Size() int {
	return xxx_messageInfo_ListDump.Size(m)
}
func (m *ListDump) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDump.DiscardUnknown(m)
}

var xxx_messageInfo_ListDump proto.InternalMessageInfo

func (m *ListDump) GetLatestRevision() []byte {
	if m != nil {
		return m.LatestRevision
	}
	return nil
}

func (m *ListDump) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ListDump) GetAttributes() *ListAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ListDump) GetChecksum() *ListChecksum {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *ListDump) GetContents() *ListItems {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *ListDump) GetPendingDeltas() []*Delta {
	if m != nil {
		return m.PendingDeltas
	}
	return nil
}

type ListChanges struct {
	BaseRevision           []byte    `protobuf:"bytes,1,opt,name=baseRevision" json:"baseRevision,omitempty"`
	Deltas                 []*Delta  `protobuf:"bytes,2,rep,name=deltas" json:"deltas,omitempty"`
	WantResultingRevisions *bool     `protobuf:"varint,3,opt,name=wantResultingRevisions" json:"wantResultingRevisions,omitempty"`
	WantSyncResult         *bool     `protobuf:"varint,4,opt,name=wantSyncResult" json:"wantSyncResult,omitempty"`
	Dump                   *ListDump `protobuf:"bytes,5,opt,name=dump" json:"dump,omitempty"`
	Nonces                 []int32   `protobuf:"varint,6,rep,name=nonces" json:"nonces,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *ListChanges) Reset()         { *m = ListChanges{} }
func (m *ListChanges) String() string { return proto.CompactTextString(m) }
func (*ListChanges) ProtoMessage()    {}
func (*ListChanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{7}
}

func (m *ListChanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChanges.Unmarshal(m, b)
}
func (m *ListChanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChanges.Marshal(b, m, deterministic)
}
func (m *ListChanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChanges.Merge(m, src)
}
func (m *ListChanges) XXX_Size() int {
	return xxx_messageInfo_ListChanges.Size(m)
}
func (m *ListChanges) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChanges.DiscardUnknown(m)
}

var xxx_messageInfo_ListChanges proto.InternalMessageInfo

func (m *ListChanges) GetBaseRevision() []byte {
	if m != nil {
		return m.BaseRevision
	}
	return nil
}

func (m *ListChanges) GetDeltas() []*Delta {
	if m != nil {
		return m.Deltas
	}
	return nil
}

func (m *ListChanges) GetWantResultingRevisions() bool {
	if m != nil && m.WantResultingRevisions != nil {
		return *m.WantResultingRevisions
	}
	return false
}

func (m *ListChanges) GetWantSyncResult() bool {
	if m != nil && m.WantSyncResult != nil {
		return *m.WantSyncResult
	}
	return false
}

func (m *ListChanges) GetDump() *ListDump {
	if m != nil {
		return m.Dump
	}
	return nil
}

func (m *ListChanges) GetNonces() []int32 {
	if m != nil {
		return m.Nonces
	}
	return nil
}

type SelectedListContent struct {
	Revision             []byte                 `protobuf:"bytes,1,opt,name=revision" json:"revision,omitempty"`
	Length               *int32                 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Attributes           *ListAttributes        `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Checksum             *ListChecksum          `protobuf:"bytes,4,opt,name=checksum" json:"checksum,omitempty"`
	Contents             *ListItems             `protobuf:"bytes,5,opt,name=contents" json:"contents,omitempty"`
	Diff                 *Diff                  `protobuf:"bytes,6,opt,name=diff" json:"diff,omitempty"`
	SyncResult           *Diff                  `protobuf:"bytes,7,opt,name=syncResult" json:"syncResult,omitempty"`
	ResultingRevisions   [][]byte               `protobuf:"bytes,8,rep,name=resultingRevisions" json:"resultingRevisions,omitempty"`
	MultipleHeads        *bool                  `protobuf:"varint,9,opt,name=multipleHeads" json:"multipleHeads,omitempty"`
	UpToDate             *bool                  `protobuf:"varint,10,opt,name=upToDate" json:"upToDate,omitempty"`
	ResolveAction        []*ClientResolveAction `protobuf:"bytes,12,rep,name=resolveAction" json:"resolveAction,omitempty"`
	Issues               []*ClientIssue         `protobuf:"bytes,13,rep,name=issues" json:"issues,omitempty"`
	Nonces               []int32                `protobuf:"varint,14,rep,name=nonces" json:"nonces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SelectedListContent) Reset()         { *m = SelectedListContent{} }
func (m *SelectedListContent) String() string { return proto.CompactTextString(m) }
func (*SelectedListContent) ProtoMessage()    {}
func (*SelectedListContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee689151b745b07, []int{8}
}

func (m *SelectedListContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectedListContent.Unmarshal(m, b)
}
func (m *SelectedListContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectedListContent.Marshal(b, m, deterministic)
}
func (m *SelectedListContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectedListContent.Merge(m, src)
}
func (m *SelectedListContent) XXX_Size() int {
	return xxx_messageInfo_SelectedListContent.Size(m)
}
func (m *SelectedListContent) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectedListContent.DiscardUnknown(m)
}

var xxx_messageInfo_SelectedListContent proto.InternalMessageInfo

func (m *SelectedListContent) GetRevision() []byte {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *SelectedListContent) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *SelectedListContent) GetAttributes() *ListAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *SelectedListContent) GetChecksum() *ListChecksum {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *SelectedListContent) GetContents() *ListItems {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *SelectedListContent) GetDiff() *Diff {
	if m != nil {
		return m.Diff
	}
	return nil
}

func (m *SelectedListContent) GetSyncResult() *Diff {
	if m != nil {
		return m.SyncResult
	}
	return nil
}

func (m *SelectedListContent) GetResultingRevisions() [][]byte {
	if m != nil {
		return m.ResultingRevisions
	}
	return nil
}

func (m *SelectedListContent) GetMultipleHeads() bool {
	if m != nil && m.MultipleHeads != nil {
		return *m.MultipleHeads
	}
	return false
}

func (m *SelectedListContent) GetUpToDate() bool {
	if m != nil && m.UpToDate != nil {
		return *m.UpToDate
	}
	return false
}

func (m *SelectedListContent) GetResolveAction() []*ClientResolveAction {
	if m != nil {
		return m.ResolveAction
	}
	return nil
}

func (m *SelectedListContent) GetIssues() []*ClientIssue {
	if m != nil {
		return m.Issues
	}
	return nil
}

func (m *SelectedListContent) GetNonces() []int32 {
	if m != nil {
		return m.Nonces
	}
	return nil
}

func init() {
	proto.RegisterEnum("spotify.ChangeSet_Kind", ChangeSet_Kind_name, ChangeSet_Kind_value)
	proto.RegisterType((*ChangeInfo)(nil), "spotify.ChangeInfo")
	proto.RegisterType((*Delta)(nil), "spotify.Delta")
	proto.RegisterType((*Merge)(nil), "spotify.Merge")
	proto.RegisterType((*ChangeSet)(nil), "spotify.ChangeSet")
	proto.RegisterType((*RevisionTaggedChangeSet)(nil), "spotify.RevisionTaggedChangeSet")
	proto.RegisterType((*Diff)(nil), "spotify.Diff")
	proto.RegisterType((*ListDump)(nil), "spotify.ListDump")
	proto.RegisterType((*ListChanges)(nil), "spotify.ListChanges")
	proto.RegisterType((*SelectedListContent)(nil), "spotify.SelectedListContent")
}

func init() { proto.RegisterFile("playlist4changes.proto", fileDescriptor_7ee689151b745b07) }

var fileDescriptor_7ee689151b745b07 = []byte{
	// 844 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x51, 0x6f, 0xdb, 0x36,
	0x10, 0x9e, 0x6d, 0xd9, 0xb1, 0xcf, 0x76, 0x90, 0x31, 0x6d, 0x2a, 0x04, 0xdd, 0xe6, 0x6a, 0x5d,
	0x67, 0x60, 0x9b, 0x81, 0x1a, 0xc5, 0xf6, 0x9c, 0xd5, 0xc1, 0x16, 0xa4, 0x4d, 0x01, 0x26, 0xdb,
	0x1e, 0x03, 0x55, 0x3a, 0xd9, 0x44, 0x24, 0x52, 0x10, 0xe9, 0x6c, 0xf9, 0x2f, 0xfb, 0x17, 0xdb,
	0x0f, 0xd9, 0xcf, 0xd9, 0xe3, 0xc0, 0x13, 0x2d, 0xd9, 0x6a, 0xb6, 0xf5, 0xb5, 0x6f, 0xe4, 0xf7,
	0x7d, 0xc7, 0xe3, 0x7d, 0x77, 0xa2, 0xe0, 0x28, 0x4f, 0xc3, 0xbb, 0x54, 0x68, 0xf3, 0x22, 0x5a,
	0x85, 0x72, 0x89, 0x7a, 0x96, 0x17, 0xca, 0x28, 0xb6, 0xa7, 0x73, 0x65, 0x44, 0x72, 0x77, 0xcc,
	0x2a, 0x81, 0xca, 0x1d, 0x79, 0x7c, 0x58, 0x61, 0x19, 0x9a, 0xd0, 0x81, 0x5b, 0x27, 0x29, 0x69,
	0x50, 0x1a, 0x87, 0x3f, 0xac, 0x70, 0xa1, 0xf5, 0x7a, 0x93, 0x20, 0xf8, 0xab, 0x05, 0xf0, 0x92,
	0x52, 0x9e, 0xc9, 0x44, 0x31, 0x06, 0xde, 0x5a, 0x63, 0xe1, 0xb7, 0x26, 0xad, 0xe9, 0x80, 0xd3,
	0x9a, 0x3d, 0x86, 0x81, 0x11, 0x19, 0x6a, 0x13, 0x66, 0xb9, 0xdf, 0x9e, 0xb4, 0xa6, 0x5d, 0x5e,
	0x03, 0xec, 0x01, 0x74, 0xc3, 0x38, 0x13, 0xd2, 0xef, 0x4c, 0x5a, 0xd3, 0x3e, 0x2f, 0x37, 0x74,
	0x8e, 0x8c, 0x95, 0xef, 0x11, 0x48, 0x6b, 0x8b, 0x15, 0x18, 0x2b, 0xbf, 0x5b, 0x62, 0x76, 0x6d,
	0xa3, 0x33, 0x2c, 0x96, 0xe8, 0xf7, 0xca, 0x68, 0xda, 0xb0, 0x4f, 0x01, 0x22, 0x95, 0xe5, 0x05,
	0x6a, 0x8d, 0xb1, 0xbf, 0x47, 0xd4, 0x16, 0x62, 0x6f, 0x94, 0x89, 0x65, 0x11, 0x1a, 0xa1, 0xa4,
	0xdf, 0x27, 0xba, 0x06, 0x82, 0x02, 0xba, 0x0b, 0x4c, 0x4d, 0xc8, 0x9e, 0xc0, 0xe8, 0x6d, 0xa8,
	0xf1, 0xfa, 0x16, 0x0b, 0x6d, 0x95, 0xb6, 0xa8, 0x11, 0x1f, 0x5a, 0xec, 0xe7, 0x12, 0x62, 0x9f,
	0x40, 0x47, 0xe5, 0xda, 0x6f, 0x4f, 0x3a, 0xd3, 0xe1, 0x7c, 0x38, 0x73, 0x6e, 0xcf, 0xde, 0xe4,
	0xdc, 0xe2, 0xec, 0x4b, 0xf0, 0x84, 0x4c, 0xca, 0x32, 0x86, 0xf3, 0xc3, 0x8a, 0xaf, 0x1d, 0xe3,
	0x24, 0x08, 0x7e, 0x83, 0xee, 0x6b, 0xba, 0xfa, 0x7b, 0xe4, 0xfc, 0x1c, 0xc6, 0x54, 0x66, 0xa5,
	0x69, 0x93, 0x66, 0x44, 0xe0, 0x46, 0xf4, 0xde, 0x99, 0xff, 0x6c, 0xc1, 0xa0, 0x04, 0x2f, 0xd1,
	0xb0, 0xaf, 0xc0, 0xbb, 0x11, 0x32, 0xa6, 0xb4, 0xfb, 0xf3, 0x47, 0x8d, 0xb0, 0x4b, 0x34, 0xb3,
	0x73, 0x21, 0x63, 0x4e, 0x22, 0xf6, 0x14, 0xba, 0xb1, 0x35, 0x8a, 0x2e, 0x30, 0x9c, 0xef, 0x57,
	0x6a, 0xb2, 0x8f, 0x97, 0xa4, 0x55, 0x95, 0x2d, 0xea, 0x34, 0x54, 0x54, 0xb0, 0x6b, 0x59, 0x30,
	0x03, 0xcf, 0x9e, 0xcc, 0x0e, 0x60, 0x74, 0x7e, 0x76, 0xb1, 0xb8, 0xfe, 0xe9, 0xe2, 0xfc, 0xe2,
	0xcd, 0x2f, 0x17, 0x07, 0x1f, 0xb1, 0x01, 0x74, 0x17, 0xa7, 0xaf, 0xae, 0x4e, 0x0e, 0xda, 0x76,
	0xf9, 0xfa, 0x94, 0xff, 0x70, 0x7a, 0xd0, 0x09, 0x56, 0xf0, 0x88, 0xe3, 0xad, 0xb0, 0xb5, 0x5e,
	0x85, 0xcb, 0x25, 0xc6, 0x75, 0x0d, 0xc7, 0xd0, 0x2f, 0x1c, 0xe5, 0xec, 0xab, 0xf6, 0xec, 0x39,
	0x40, 0xf9, 0x81, 0x5c, 0x6b, 0x34, 0xee, 0xde, 0xec, 0xdd, 0x2a, 0xf9, 0x20, 0xda, 0x2c, 0x83,
	0x1b, 0xf0, 0x16, 0x22, 0x49, 0xac, 0xed, 0x49, 0xa1, 0xb2, 0xeb, 0xc6, 0xd9, 0x23, 0x0b, 0x6e,
	0xae, 0xf2, 0x7f, 0xf3, 0xf0, 0x19, 0x0c, 0x8d, 0xaa, 0x4f, 0xe8, 0xd0, 0x09, 0x60, 0xd4, 0x26,
	0x3e, 0xf8, 0xbd, 0x0d, 0xfd, 0x57, 0x42, 0x9b, 0xc5, 0x3a, 0xcb, 0xd9, 0x33, 0xd8, 0x4f, 0x43,
	0x83, 0xda, 0xf0, 0xdd, 0x94, 0x0d, 0x94, 0x1d, 0x41, 0x2f, 0x45, 0xb9, 0x34, 0x2b, 0xf7, 0x75,
	0xb9, 0x1d, 0xfb, 0x0e, 0x20, 0x34, 0xa6, 0x10, 0x6f, 0xd7, 0x06, 0xb5, 0xb3, 0xbf, 0x6e, 0xa9,
	0x4d, 0x73, 0x52, 0xd1, 0x7c, 0x4b, 0xca, 0x9e, 0x43, 0x3f, 0x5a, 0x61, 0x74, 0xa3, 0xd7, 0x99,
	0x1b, 0xa0, 0x87, 0x3b, 0x61, 0x2f, 0x1d, 0xc9, 0x2b, 0x19, 0x9b, 0x41, 0xdf, 0xbd, 0x17, 0x9a,
	0x3e, 0xd0, 0x6d, 0x5b, 0x6d, 0xc8, 0x99, 0xc1, 0x4c, 0xf3, 0x4a, 0xc3, 0x5e, 0xc0, 0x38, 0x47,
	0x19, 0x0b, 0xb9, 0xa4, 0x61, 0xd1, 0xfe, 0x1e, 0x59, 0xd6, 0x9c, 0xa1, 0x5d, 0x51, 0xf0, 0x77,
	0x0b, 0x86, 0xe5, 0x05, 0xe8, 0x91, 0x63, 0x41, 0xf9, 0xb5, 0x34, 0xfc, 0xd9, 0xc1, 0xd8, 0x33,
	0xe8, 0xc5, 0x65, 0x8a, 0xf6, 0xbd, 0x29, 0x1c, 0xcb, 0xbe, 0x85, 0xa3, 0x5f, 0x43, 0x69, 0x38,
	0xea, 0x75, 0x6a, 0x84, 0x5c, 0x6e, 0x0e, 0xd0, 0xee, 0x65, 0xfa, 0x17, 0xd6, 0x76, 0xc9, 0x32,
	0x97, 0x77, 0x32, 0x2a, 0x59, 0xf7, 0x68, 0x35, 0x50, 0xf6, 0x05, 0x78, 0xf1, 0x3a, 0xcb, 0x9d,
	0x3b, 0x1f, 0xef, 0xb8, 0x63, 0xdb, 0xcd, 0x89, 0xb6, 0xcd, 0x94, 0x4a, 0x46, 0xa8, 0xfd, 0xde,
	0xa4, 0x63, 0x9b, 0x59, 0xee, 0x82, 0x3f, 0x3c, 0x38, 0xbc, 0xc4, 0x14, 0x23, 0x83, 0x31, 0x59,
	0x50, 0x3a, 0xf9, 0x9f, 0xd3, 0xfe, 0x21, 0x0e, 0xc6, 0x13, 0xf0, 0x62, 0x91, 0x24, 0xf4, 0xa0,
	0x0f, 0xe7, 0xe3, 0xba, 0x59, 0x22, 0x49, 0x38, 0x51, 0xec, 0x1b, 0x00, 0x5d, 0xbb, 0xbd, 0x77,
	0x9f, 0x70, 0x4b, 0xc0, 0x66, 0xc0, 0x8a, 0x77, 0x9b, 0xda, 0x9f, 0x74, 0xa6, 0x23, 0x7e, 0x0f,
	0xc3, 0x9e, 0xc2, 0x38, 0xb3, 0x58, 0x9e, 0xe2, 0x8f, 0x18, 0xc6, 0xda, 0x1f, 0x50, 0x3f, 0x77,
	0x41, 0xeb, 0xfb, 0x3a, 0xbf, 0x52, 0x8b, 0xd0, 0xa0, 0x0f, 0x24, 0xa8, 0xf6, 0xec, 0x7b, 0x18,
	0x17, 0xa8, 0x55, 0x7a, 0x8b, 0x27, 0x11, 0xfd, 0x63, 0x46, 0x34, 0x79, 0x8f, 0xeb, 0x87, 0x26,
	0x15, 0x48, 0xc3, 0x54, 0x6b, 0xf8, 0x6e, 0x08, 0xfb, 0x1a, 0x7a, 0xe5, 0x8f, 0xd6, 0x1f, 0x53,
	0xf0, 0x83, 0x46, 0xf0, 0x99, 0x25, 0xb9, 0xd3, 0x6c, 0x4d, 0xcd, 0xfe, 0xf6, 0xd4, 0xfc, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xaf, 0xc1, 0xbd, 0x0f, 0x18, 0x08, 0x00, 0x00,
}
