// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playlist4issues.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientIssue_Level int32

const (
	ClientIssue_LEVEL_UNKNOWN ClientIssue_Level = 0
	ClientIssue_LEVEL_DEBUG   ClientIssue_Level = 1
	ClientIssue_LEVEL_INFO    ClientIssue_Level = 2
	ClientIssue_LEVEL_NOTICE  ClientIssue_Level = 3
	ClientIssue_LEVEL_WARNING ClientIssue_Level = 4
	ClientIssue_LEVEL_ERROR   ClientIssue_Level = 5
)

var ClientIssue_Level_name = map[int32]string{
	0: "LEVEL_UNKNOWN",
	1: "LEVEL_DEBUG",
	2: "LEVEL_INFO",
	3: "LEVEL_NOTICE",
	4: "LEVEL_WARNING",
	5: "LEVEL_ERROR",
}

var ClientIssue_Level_value = map[string]int32{
	"LEVEL_UNKNOWN": 0,
	"LEVEL_DEBUG":   1,
	"LEVEL_INFO":    2,
	"LEVEL_NOTICE":  3,
	"LEVEL_WARNING": 4,
	"LEVEL_ERROR":   5,
}

func (x ClientIssue_Level) Enum() *ClientIssue_Level {
	p := new(ClientIssue_Level)
	*p = x
	return p
}

func (x ClientIssue_Level) String() string {
	return proto.EnumName(ClientIssue_Level_name, int32(x))
}

func (x *ClientIssue_Level) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientIssue_Level_value, data, "ClientIssue_Level")
	if err != nil {
		return err
	}
	*x = ClientIssue_Level(value)
	return nil
}

func (ClientIssue_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a64784b4443ab63, []int{0, 0}
}

type ClientIssue_Code int32

const (
	ClientIssue_CODE_UNKNOWN             ClientIssue_Code = 0
	ClientIssue_CODE_INDEX_OUT_OF_BOUNDS ClientIssue_Code = 1
	ClientIssue_CODE_VERSION_MISMATCH    ClientIssue_Code = 2
	ClientIssue_CODE_CACHED_CHANGE       ClientIssue_Code = 3
	ClientIssue_CODE_OFFLINE_CHANGE      ClientIssue_Code = 4
	ClientIssue_CODE_CONCURRENT_CHANGE   ClientIssue_Code = 5
)

var ClientIssue_Code_name = map[int32]string{
	0: "CODE_UNKNOWN",
	1: "CODE_INDEX_OUT_OF_BOUNDS",
	2: "CODE_VERSION_MISMATCH",
	3: "CODE_CACHED_CHANGE",
	4: "CODE_OFFLINE_CHANGE",
	5: "CODE_CONCURRENT_CHANGE",
}

var ClientIssue_Code_value = map[string]int32{
	"CODE_UNKNOWN":             0,
	"CODE_INDEX_OUT_OF_BOUNDS": 1,
	"CODE_VERSION_MISMATCH":    2,
	"CODE_CACHED_CHANGE":       3,
	"CODE_OFFLINE_CHANGE":      4,
	"CODE_CONCURRENT_CHANGE":   5,
}

func (x ClientIssue_Code) Enum() *ClientIssue_Code {
	p := new(ClientIssue_Code)
	*p = x
	return p
}

func (x ClientIssue_Code) String() string {
	return proto.EnumName(ClientIssue_Code_name, int32(x))
}

func (x *ClientIssue_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientIssue_Code_value, data, "ClientIssue_Code")
	if err != nil {
		return err
	}
	*x = ClientIssue_Code(value)
	return nil
}

func (ClientIssue_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a64784b4443ab63, []int{0, 1}
}

type ClientResolveAction_Code int32

const (
	ClientResolveAction_CODE_UNKNOWN               ClientResolveAction_Code = 0
	ClientResolveAction_CODE_NO_ACTION             ClientResolveAction_Code = 1
	ClientResolveAction_CODE_RETRY                 ClientResolveAction_Code = 2
	ClientResolveAction_CODE_RELOAD                ClientResolveAction_Code = 3
	ClientResolveAction_CODE_DISCARD_LOCAL_CHANGES ClientResolveAction_Code = 4
	ClientResolveAction_CODE_SEND_DUMP             ClientResolveAction_Code = 5
	ClientResolveAction_CODE_DISPLAY_ERROR_MESSAGE ClientResolveAction_Code = 6
)

var ClientResolveAction_Code_name = map[int32]string{
	0: "CODE_UNKNOWN",
	1: "CODE_NO_ACTION",
	2: "CODE_RETRY",
	3: "CODE_RELOAD",
	4: "CODE_DISCARD_LOCAL_CHANGES",
	5: "CODE_SEND_DUMP",
	6: "CODE_DISPLAY_ERROR_MESSAGE",
}

var ClientResolveAction_Code_value = map[string]int32{
	"CODE_UNKNOWN":               0,
	"CODE_NO_ACTION":             1,
	"CODE_RETRY":                 2,
	"CODE_RELOAD":                3,
	"CODE_DISCARD_LOCAL_CHANGES": 4,
	"CODE_SEND_DUMP":             5,
	"CODE_DISPLAY_ERROR_MESSAGE": 6,
}

func (x ClientResolveAction_Code) Enum() *ClientResolveAction_Code {
	p := new(ClientResolveAction_Code)
	*p = x
	return p
}

func (x ClientResolveAction_Code) String() string {
	return proto.EnumName(ClientResolveAction_Code_name, int32(x))
}

func (x *ClientResolveAction_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientResolveAction_Code_value, data, "ClientResolveAction_Code")
	if err != nil {
		return err
	}
	*x = ClientResolveAction_Code(value)
	return nil
}

func (ClientResolveAction_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a64784b4443ab63, []int{1, 0}
}

type ClientResolveAction_Initiator int32

const (
	ClientResolveAction_INITIATOR_UNKNOWN ClientResolveAction_Initiator = 0
	ClientResolveAction_INITIATOR_SERVER  ClientResolveAction_Initiator = 1
	ClientResolveAction_INITIATOR_CLIENT  ClientResolveAction_Initiator = 2
)

var ClientResolveAction_Initiator_name = map[int32]string{
	0: "INITIATOR_UNKNOWN",
	1: "INITIATOR_SERVER",
	2: "INITIATOR_CLIENT",
}

var ClientResolveAction_Initiator_value = map[string]int32{
	"INITIATOR_UNKNOWN": 0,
	"INITIATOR_SERVER":  1,
	"INITIATOR_CLIENT":  2,
}

func (x ClientResolveAction_Initiator) Enum() *ClientResolveAction_Initiator {
	p := new(ClientResolveAction_Initiator)
	*p = x
	return p
}

func (x ClientResolveAction_Initiator) String() string {
	return proto.EnumName(ClientResolveAction_Initiator_name, int32(x))
}

func (x *ClientResolveAction_Initiator) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientResolveAction_Initiator_value, data, "ClientResolveAction_Initiator")
	if err != nil {
		return err
	}
	*x = ClientResolveAction_Initiator(value)
	return nil
}

func (ClientResolveAction_Initiator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a64784b4443ab63, []int{1, 1}
}

type ClientIssue struct {
	Level                *ClientIssue_Level `protobuf:"varint,1,opt,name=level,enum=spotify.ClientIssue_Level" json:"level,omitempty"`
	Code                 *ClientIssue_Code  `protobuf:"varint,2,opt,name=code,enum=spotify.ClientIssue_Code" json:"code,omitempty"`
	RepeatCount          *int32             `protobuf:"varint,3,opt,name=repeatCount" json:"repeatCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ClientIssue) Reset()         { *m = ClientIssue{} }
func (m *ClientIssue) String() string { return proto.CompactTextString(m) }
func (*ClientIssue) ProtoMessage()    {}
func (*ClientIssue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a64784b4443ab63, []int{0}
}

func (m *ClientIssue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIssue.Unmarshal(m, b)
}
func (m *ClientIssue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIssue.Marshal(b, m, deterministic)
}
func (m *ClientIssue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIssue.Merge(m, src)
}
func (m *ClientIssue) XXX_Size() int {
	return xxx_messageInfo_ClientIssue.Size(m)
}
func (m *ClientIssue) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIssue.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIssue proto.InternalMessageInfo

func (m *ClientIssue) GetLevel() ClientIssue_Level {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return ClientIssue_LEVEL_UNKNOWN
}

func (m *ClientIssue) GetCode() ClientIssue_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ClientIssue_CODE_UNKNOWN
}

func (m *ClientIssue) GetRepeatCount() int32 {
	if m != nil && m.RepeatCount != nil {
		return *m.RepeatCount
	}
	return 0
}

type ClientResolveAction struct {
	Code                 *ClientResolveAction_Code      `protobuf:"varint,1,opt,name=code,enum=spotify.ClientResolveAction_Code" json:"code,omitempty"`
	Initiator            *ClientResolveAction_Initiator `protobuf:"varint,2,opt,name=initiator,enum=spotify.ClientResolveAction_Initiator" json:"initiator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ClientResolveAction) Reset()         { *m = ClientResolveAction{} }
func (m *ClientResolveAction) String() string { return proto.CompactTextString(m) }
func (*ClientResolveAction) ProtoMessage()    {}
func (*ClientResolveAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a64784b4443ab63, []int{1}
}

func (m *ClientResolveAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResolveAction.Unmarshal(m, b)
}
func (m *ClientResolveAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResolveAction.Marshal(b, m, deterministic)
}
func (m *ClientResolveAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResolveAction.Merge(m, src)
}
func (m *ClientResolveAction) XXX_Size() int {
	return xxx_messageInfo_ClientResolveAction.Size(m)
}
func (m *ClientResolveAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResolveAction.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResolveAction proto.InternalMessageInfo

func (m *ClientResolveAction) GetCode() ClientResolveAction_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ClientResolveAction_CODE_UNKNOWN
}

func (m *ClientResolveAction) GetInitiator() ClientResolveAction_Initiator {
	if m != nil && m.Initiator != nil {
		return *m.Initiator
	}
	return ClientResolveAction_INITIATOR_UNKNOWN
}

func init() {
	proto.RegisterEnum("spotify.ClientIssue_Level", ClientIssue_Level_name, ClientIssue_Level_value)
	proto.RegisterEnum("spotify.ClientIssue_Code", ClientIssue_Code_name, ClientIssue_Code_value)
	proto.RegisterEnum("spotify.ClientResolveAction_Code", ClientResolveAction_Code_name, ClientResolveAction_Code_value)
	proto.RegisterEnum("spotify.ClientResolveAction_Initiator", ClientResolveAction_Initiator_name, ClientResolveAction_Initiator_value)
	proto.RegisterType((*ClientIssue)(nil), "spotify.ClientIssue")
	proto.RegisterType((*ClientResolveAction)(nil), "spotify.ClientResolveAction")
}

func init() { proto.RegisterFile("playlist4issues.proto", fileDescriptor_3a64784b4443ab63) }

var fileDescriptor_3a64784b4443ab63 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0xdb, 0x80, 0x76, 0x0a, 0xc5, 0xf3, 0xe8, 0xe8, 0x2a, 0x84, 0x4a, 0x2e, 0xd0,
	0x6e, 0xa8, 0x10, 0x82, 0x07, 0xf0, 0x6c, 0xb7, 0xb5, 0x48, 0x8f, 0x27, 0x27, 0xe9, 0xd8, 0x55,
	0x54, 0x6d, 0x41, 0x8a, 0x14, 0x35, 0xa5, 0xc9, 0x26, 0xed, 0x05, 0x78, 0x0c, 0x24, 0x24, 0x1e,
	0x14, 0xc5, 0x69, 0xd7, 0x0c, 0x01, 0x97, 0xfe, 0xce, 0xff, 0x1f, 0x1f, 0xfd, 0x3f, 0xf4, 0xd7,
	0xd9, 0xf2, 0x2e, 0x4b, 0x8b, 0xf2, 0x63, 0x5a, 0x14, 0x37, 0x49, 0x31, 0x5e, 0x6f, 0xf2, 0x32,
	0xa7, 0x4f, 0x8a, 0x75, 0x5e, 0xa6, 0x5f, 0xef, 0xbc, 0x5f, 0x6d, 0xe8, 0xf2, 0x2c, 0x4d, 0x56,
	0xa5, 0xaa, 0xe6, 0xf4, 0x3d, 0xb8, 0x59, 0x72, 0x9b, 0x64, 0x03, 0x67, 0xe4, 0x9c, 0xf6, 0x3e,
	0x0c, 0xc7, 0x5b, 0xe1, 0xb8, 0x21, 0x1a, 0xfb, 0x95, 0xc2, 0xd4, 0x42, 0xfa, 0x0e, 0x3a, 0x57,
	0xf9, 0x75, 0x32, 0x68, 0x59, 0xc3, 0xc9, 0x5f, 0x0d, 0x3c, 0xbf, 0x4e, 0x8c, 0x95, 0xd1, 0x11,
	0x74, 0x37, 0xc9, 0x3a, 0x59, 0x96, 0x3c, 0xbf, 0x59, 0x95, 0x83, 0xf6, 0xc8, 0x39, 0x75, 0x4d,
	0x13, 0x79, 0xdf, 0xc0, 0xb5, 0x1f, 0xd0, 0x43, 0x78, 0xe6, 0xcb, 0x85, 0xf4, 0xe3, 0x08, 0x3f,
	0xa3, 0xbe, 0x40, 0xf2, 0x88, 0x3e, 0x87, 0x6e, 0x8d, 0x84, 0x3c, 0x8b, 0xa6, 0xc4, 0xa1, 0x3d,
	0x80, 0x1a, 0x28, 0x9c, 0x68, 0xd2, 0xa2, 0x04, 0x9e, 0xd6, 0x6f, 0xd4, 0xa1, 0xe2, 0x92, 0xb4,
	0xf7, 0x5b, 0x2e, 0x98, 0x41, 0x85, 0x53, 0xd2, 0xd9, 0x6f, 0x91, 0xc6, 0x68, 0x43, 0x5c, 0xef,
	0x87, 0x03, 0x9d, 0xea, 0xc6, 0xca, 0xce, 0xb5, 0x90, 0x8d, 0x1f, 0x5f, 0xc1, 0xc0, 0x12, 0x85,
	0x42, 0x7e, 0x89, 0x75, 0x14, 0xc6, 0x7a, 0x12, 0x9f, 0xe9, 0x08, 0x45, 0x40, 0x1c, 0x7a, 0x02,
	0x7d, 0x3b, 0x5d, 0x48, 0x13, 0x28, 0x8d, 0xf1, 0x5c, 0x05, 0x73, 0x16, 0xf2, 0x19, 0x69, 0xd1,
	0x63, 0xa0, 0x76, 0xc4, 0x19, 0x9f, 0x49, 0x11, 0xf3, 0x19, 0xc3, 0x69, 0x75, 0xcf, 0x4b, 0x38,
	0xb2, 0x5c, 0x4f, 0x26, 0xbe, 0x42, 0xb9, 0x1b, 0x74, 0xe8, 0x10, 0x8e, 0x6b, 0x83, 0x46, 0x1e,
	0x19, 0x23, 0x31, 0xdc, 0xcd, 0x5c, 0xef, 0x7b, 0x1b, 0x8e, 0xea, 0x40, 0x4d, 0x52, 0xe4, 0xd9,
	0x6d, 0xc2, 0xae, 0xca, 0x34, 0x5f, 0xd1, 0x4f, 0xdb, 0xf0, 0xeb, 0xb6, 0xde, 0xfc, 0x11, 0xfe,
	0x03, 0x6d, 0xb3, 0x04, 0x01, 0x07, 0xe9, 0x2a, 0x2d, 0xd3, 0x65, 0x99, 0x6f, 0xb6, 0xc5, 0xbd,
	0xfd, 0xaf, 0x57, 0xed, 0xd4, 0x66, 0x6f, 0xf4, 0x7e, 0xfe, 0x3b, 0x35, 0x0a, 0x3d, 0x4b, 0x50,
	0xc7, 0x8c, 0x87, 0x4a, 0x63, 0x5d, 0x95, 0x65, 0x46, 0x86, 0xe6, 0x92, 0xb4, 0xaa, 0x16, 0xb6,
	0x6f, 0x5f, 0x33, 0x41, 0xda, 0xf4, 0x35, 0x0c, 0x2d, 0x10, 0x2a, 0xe0, 0xcc, 0x88, 0xd8, 0xd7,
	0x9c, 0xf9, 0xdb, 0x0c, 0x02, 0xd2, 0xb9, 0x5f, 0x1a, 0x48, 0x14, 0xb1, 0x88, 0xe6, 0xe7, 0xc4,
	0x6d, 0x7a, 0xce, 0x7d, 0x76, 0x59, 0x37, 0x1a, 0xcf, 0x65, 0x10, 0xb0, 0xa9, 0x24, 0x8f, 0x3d,
	0x84, 0x83, 0xfb, 0xdb, 0x69, 0x1f, 0x0e, 0x15, 0xaa, 0x50, 0xb1, 0x50, 0x9b, 0xc6, 0xb1, 0x2f,
	0x80, 0xec, 0x71, 0x20, 0xcd, 0x42, 0x1a, 0xe2, 0x3c, 0xa4, 0xdc, 0x57, 0x12, 0x43, 0xd2, 0xfa,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x67, 0x52, 0xdf, 0xb1, 0x50, 0x03, 0x00, 0x00,
}
