// Code generated by protoc-gen-go. DO NOT EDIT.
// source: radio.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RadioRequest struct {
	Uris                 []string `protobuf:"bytes,1,rep,name=uris" json:"uris,omitempty"`
	Salt                 *int32   `protobuf:"varint,2,opt,name=salt" json:"salt,omitempty"`
	Length               *int32   `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	StationID            *string  `protobuf:"bytes,5,opt,name=stationID" json:"stationID,omitempty"`
	LastTracks           []string `protobuf:"bytes,6,rep,name=lastTracks" json:"lastTracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RadioRequest) Reset()         { *m = RadioRequest{} }
func (m *RadioRequest) String() string { return proto.CompactTextString(m) }
func (*RadioRequest) ProtoMessage()    {}
func (*RadioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{0}
}

func (m *RadioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadioRequest.Unmarshal(m, b)
}
func (m *RadioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadioRequest.Marshal(b, m, deterministic)
}
func (m *RadioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadioRequest.Merge(m, src)
}
func (m *RadioRequest) XXX_Size() int {
	return xxx_messageInfo_RadioRequest.Size(m)
}
func (m *RadioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RadioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RadioRequest proto.InternalMessageInfo

func (m *RadioRequest) GetUris() []string {
	if m != nil {
		return m.Uris
	}
	return nil
}

func (m *RadioRequest) GetSalt() int32 {
	if m != nil && m.Salt != nil {
		return *m.Salt
	}
	return 0
}

func (m *RadioRequest) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *RadioRequest) GetStationID() string {
	if m != nil && m.StationID != nil {
		return *m.StationID
	}
	return ""
}

func (m *RadioRequest) GetLastTracks() []string {
	if m != nil {
		return m.LastTracks
	}
	return nil
}

type MultiSeedRequest struct {
	Uris                 []string `protobuf:"bytes,1,rep,name=uris" json:"uris,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSeedRequest) Reset()         { *m = MultiSeedRequest{} }
func (m *MultiSeedRequest) String() string { return proto.CompactTextString(m) }
func (*MultiSeedRequest) ProtoMessage()    {}
func (*MultiSeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{1}
}

func (m *MultiSeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSeedRequest.Unmarshal(m, b)
}
func (m *MultiSeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSeedRequest.Marshal(b, m, deterministic)
}
func (m *MultiSeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSeedRequest.Merge(m, src)
}
func (m *MultiSeedRequest) XXX_Size() int {
	return xxx_messageInfo_MultiSeedRequest.Size(m)
}
func (m *MultiSeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSeedRequest proto.InternalMessageInfo

func (m *MultiSeedRequest) GetUris() []string {
	if m != nil {
		return m.Uris
	}
	return nil
}

type Feedback struct {
	Uri                  *string  `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	Type                 *string  `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Timestamp            *float64 `protobuf:"fixed64,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feedback) Reset()         { *m = Feedback{} }
func (m *Feedback) String() string { return proto.CompactTextString(m) }
func (*Feedback) ProtoMessage()    {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{2}
}

func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feedback.Unmarshal(m, b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
}
func (m *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(m, src)
}
func (m *Feedback) XXX_Size() int {
	return xxx_messageInfo_Feedback.Size(m)
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Feedback) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Feedback) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type Tracks struct {
	Gids                 []string    `protobuf:"bytes,1,rep,name=gids" json:"gids,omitempty"`
	Source               *string     `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Identity             *string     `protobuf:"bytes,3,opt,name=identity" json:"identity,omitempty"`
	Tokens               []string    `protobuf:"bytes,4,rep,name=tokens" json:"tokens,omitempty"`
	Feedback             []*Feedback `protobuf:"bytes,5,rep,name=feedback" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tracks) Reset()         { *m = Tracks{} }
func (m *Tracks) String() string { return proto.CompactTextString(m) }
func (*Tracks) ProtoMessage()    {}
func (*Tracks) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{3}
}

func (m *Tracks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracks.Unmarshal(m, b)
}
func (m *Tracks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracks.Marshal(b, m, deterministic)
}
func (m *Tracks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracks.Merge(m, src)
}
func (m *Tracks) XXX_Size() int {
	return xxx_messageInfo_Tracks.Size(m)
}
func (m *Tracks) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracks.DiscardUnknown(m)
}

var xxx_messageInfo_Tracks proto.InternalMessageInfo

func (m *Tracks) GetGids() []string {
	if m != nil {
		return m.Gids
	}
	return nil
}

func (m *Tracks) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Tracks) GetIdentity() string {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return ""
}

func (m *Tracks) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *Tracks) GetFeedback() []*Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type Station struct {
	Id                   *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                *string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	TitleUri             *string  `protobuf:"bytes,3,opt,name=titleUri" json:"titleUri,omitempty"`
	Subtitle             *string  `protobuf:"bytes,4,opt,name=subtitle" json:"subtitle,omitempty"`
	SubtitleUri          *string  `protobuf:"bytes,5,opt,name=subtitleUri" json:"subtitleUri,omitempty"`
	ImageUri             *string  `protobuf:"bytes,6,opt,name=imageUri" json:"imageUri,omitempty"`
	LastListen           *float64 `protobuf:"fixed64,7,opt,name=lastListen" json:"lastListen,omitempty"`
	Seeds                []string `protobuf:"bytes,8,rep,name=seeds" json:"seeds,omitempty"`
	ThumbsUp             *int32   `protobuf:"varint,9,opt,name=thumbsUp" json:"thumbsUp,omitempty"`
	ThumbsDown           *int32   `protobuf:"varint,10,opt,name=thumbsDown" json:"thumbsDown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{4}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Station) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Station) GetTitleUri() string {
	if m != nil && m.TitleUri != nil {
		return *m.TitleUri
	}
	return ""
}

func (m *Station) GetSubtitle() string {
	if m != nil && m.Subtitle != nil {
		return *m.Subtitle
	}
	return ""
}

func (m *Station) GetSubtitleUri() string {
	if m != nil && m.SubtitleUri != nil {
		return *m.SubtitleUri
	}
	return ""
}

func (m *Station) GetImageUri() string {
	if m != nil && m.ImageUri != nil {
		return *m.ImageUri
	}
	return ""
}

func (m *Station) GetLastListen() float64 {
	if m != nil && m.LastListen != nil {
		return *m.LastListen
	}
	return 0
}

func (m *Station) GetSeeds() []string {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func (m *Station) GetThumbsUp() int32 {
	if m != nil && m.ThumbsUp != nil {
		return *m.ThumbsUp
	}
	return 0
}

func (m *Station) GetThumbsDown() int32 {
	if m != nil && m.ThumbsDown != nil {
		return *m.ThumbsDown
	}
	return 0
}

type Rules struct {
	Js                   *string  `protobuf:"bytes,1,opt,name=js" json:"js,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rules) Reset()         { *m = Rules{} }
func (m *Rules) String() string { return proto.CompactTextString(m) }
func (*Rules) ProtoMessage()    {}
func (*Rules) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{5}
}

func (m *Rules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rules.Unmarshal(m, b)
}
func (m *Rules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rules.Marshal(b, m, deterministic)
}
func (m *Rules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rules.Merge(m, src)
}
func (m *Rules) XXX_Size() int {
	return xxx_messageInfo_Rules.Size(m)
}
func (m *Rules) XXX_DiscardUnknown() {
	xxx_messageInfo_Rules.DiscardUnknown(m)
}

var xxx_messageInfo_Rules proto.InternalMessageInfo

func (m *Rules) GetJs() string {
	if m != nil && m.Js != nil {
		return *m.Js
	}
	return ""
}

type StationResponse struct {
	Station              *Station    `protobuf:"bytes,1,opt,name=station" json:"station,omitempty"`
	Feedback             []*Feedback `protobuf:"bytes,2,rep,name=feedback" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StationResponse) Reset()         { *m = StationResponse{} }
func (m *StationResponse) String() string { return proto.CompactTextString(m) }
func (*StationResponse) ProtoMessage()    {}
func (*StationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{6}
}

func (m *StationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationResponse.Unmarshal(m, b)
}
func (m *StationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationResponse.Marshal(b, m, deterministic)
}
func (m *StationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationResponse.Merge(m, src)
}
func (m *StationResponse) XXX_Size() int {
	return xxx_messageInfo_StationResponse.Size(m)
}
func (m *StationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StationResponse proto.InternalMessageInfo

func (m *StationResponse) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *StationResponse) GetFeedback() []*Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type StationList struct {
	Stations             []*Station `protobuf:"bytes,1,rep,name=stations" json:"stations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StationList) Reset()         { *m = StationList{} }
func (m *StationList) String() string { return proto.CompactTextString(m) }
func (*StationList) ProtoMessage()    {}
func (*StationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{7}
}

func (m *StationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationList.Unmarshal(m, b)
}
func (m *StationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationList.Marshal(b, m, deterministic)
}
func (m *StationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationList.Merge(m, src)
}
func (m *StationList) XXX_Size() int {
	return xxx_messageInfo_StationList.Size(m)
}
func (m *StationList) XXX_DiscardUnknown() {
	xxx_messageInfo_StationList.DiscardUnknown(m)
}

var xxx_messageInfo_StationList proto.InternalMessageInfo

func (m *StationList) GetStations() []*Station {
	if m != nil {
		return m.Stations
	}
	return nil
}

type LikedPlaylist struct {
	Uri                  *string  `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikedPlaylist) Reset()         { *m = LikedPlaylist{} }
func (m *LikedPlaylist) String() string { return proto.CompactTextString(m) }
func (*LikedPlaylist) ProtoMessage()    {}
func (*LikedPlaylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_f48a6e2b1a50dd02, []int{8}
}

func (m *LikedPlaylist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikedPlaylist.Unmarshal(m, b)
}
func (m *LikedPlaylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikedPlaylist.Marshal(b, m, deterministic)
}
func (m *LikedPlaylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikedPlaylist.Merge(m, src)
}
func (m *LikedPlaylist) XXX_Size() int {
	return xxx_messageInfo_LikedPlaylist.Size(m)
}
func (m *LikedPlaylist) XXX_DiscardUnknown() {
	xxx_messageInfo_LikedPlaylist.DiscardUnknown(m)
}

var xxx_messageInfo_LikedPlaylist proto.InternalMessageInfo

func (m *LikedPlaylist) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func init() {
	proto.RegisterType((*RadioRequest)(nil), "spotify.RadioRequest")
	proto.RegisterType((*MultiSeedRequest)(nil), "spotify.MultiSeedRequest")
	proto.RegisterType((*Feedback)(nil), "spotify.Feedback")
	proto.RegisterType((*Tracks)(nil), "spotify.Tracks")
	proto.RegisterType((*Station)(nil), "spotify.Station")
	proto.RegisterType((*Rules)(nil), "spotify.Rules")
	proto.RegisterType((*StationResponse)(nil), "spotify.StationResponse")
	proto.RegisterType((*StationList)(nil), "spotify.StationList")
	proto.RegisterType((*LikedPlaylist)(nil), "spotify.LikedPlaylist")
}

func init() { proto.RegisterFile("radio.proto", fileDescriptor_f48a6e2b1a50dd02) }

var fileDescriptor_f48a6e2b1a50dd02 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x38, 0xb1, 0xc7, 0x7c, 0x84, 0x15, 0x82, 0x15, 0x42, 0xc8, 0xf8, 0x80, 0x2c,
	0x04, 0x39, 0xf4, 0xca, 0xb5, 0x42, 0x42, 0x2a, 0x08, 0x6d, 0xe9, 0x0f, 0x70, 0xe2, 0x6d, 0xba,
	0x8d, 0x63, 0x1b, 0xcf, 0x58, 0x28, 0xff, 0x81, 0x7b, 0xff, 0x2e, 0xda, 0xf1, 0xae, 0x1b, 0x04,
	0x82, 0xdb, 0x7b, 0x6f, 0x3e, 0xf6, 0xcd, 0xcc, 0x42, 0xda, 0x97, 0x95, 0x69, 0xd7, 0x5d, 0xdf,
	0x52, 0x2b, 0x96, 0xd8, 0xb5, 0x64, 0xae, 0x8f, 0xf9, 0xcf, 0x00, 0x1e, 0x28, 0x1b, 0x50, 0xfa,
	0xfb, 0xa0, 0x91, 0x84, 0x80, 0xf9, 0xd0, 0x1b, 0x94, 0x41, 0x36, 0x2b, 0x12, 0xc5, 0xd8, 0x6a,
	0x58, 0xd6, 0x24, 0xc3, 0x2c, 0x28, 0x22, 0xc5, 0x58, 0x3c, 0x83, 0x45, 0xad, 0x9b, 0x1d, 0xdd,
	0xc8, 0x39, 0xab, 0x8e, 0x89, 0x97, 0x90, 0x20, 0x95, 0x64, 0xda, 0xe6, 0xd3, 0xb9, 0x8c, 0xb2,
	0xa0, 0x48, 0xd4, 0xbd, 0x20, 0x5e, 0x01, 0xd4, 0x25, 0xd2, 0xb7, 0xbe, 0xdc, 0xee, 0x51, 0x2e,
	0xf8, 0x8d, 0x13, 0x25, 0x7f, 0x03, 0xab, 0xcf, 0x43, 0x4d, 0xe6, 0x52, 0xeb, 0xea, 0x1f, 0x8e,
	0xf2, 0x2f, 0x10, 0x7f, 0xd4, 0xba, 0xda, 0x94, 0xdb, 0xbd, 0x58, 0xc1, 0x6c, 0xe8, 0x8d, 0x0c,
	0xf8, 0x2d, 0x0b, 0x6d, 0x05, 0x1d, 0x3b, 0xcd, 0x7e, 0x13, 0xc5, 0xd8, 0xfa, 0x22, 0x73, 0xd0,
	0x48, 0xe5, 0xa1, 0x93, 0xb3, 0x2c, 0x28, 0x02, 0x75, 0x2f, 0xe4, 0x77, 0x01, 0x2c, 0x46, 0x0b,
	0xb6, 0x78, 0x67, 0xaa, 0xe9, 0x39, 0x8b, 0xed, 0xb0, 0xd8, 0x0e, 0xfd, 0xd6, 0xb7, 0x74, 0x4c,
	0xbc, 0x80, 0xd8, 0x54, 0xba, 0x21, 0x43, 0x47, 0xee, 0x99, 0xa8, 0x89, 0xdb, 0x1a, 0x6a, 0xf7,
	0xba, 0x41, 0x39, 0xe7, 0x4e, 0x8e, 0x89, 0xf7, 0x10, 0x5f, 0x3b, 0xeb, 0x32, 0xca, 0x66, 0x45,
	0x7a, 0xf6, 0x64, 0xed, 0xae, 0xb1, 0xf6, 0x33, 0xa9, 0x29, 0x25, 0xbf, 0x0b, 0x61, 0x79, 0x39,
	0xee, 0x4f, 0x3c, 0x82, 0xd0, 0x54, 0x6e, 0xd0, 0xd0, 0x54, 0xe2, 0x29, 0x44, 0x64, 0xa8, 0xf6,
	0xae, 0x46, 0x62, 0x4d, 0x31, 0xb8, 0xea, 0x8d, 0x37, 0xe5, 0xb9, 0x8d, 0xe1, 0xb0, 0x19, 0x8b,
	0xe6, 0x63, 0xcc, 0x73, 0x91, 0x41, 0xea, 0xb1, 0x2d, 0x1d, 0x6f, 0x77, 0x2a, 0xf1, 0xb8, 0x87,
	0x72, 0xc7, 0xe1, 0x85, 0x1b, 0xd7, 0x71, 0x7f, 0xd9, 0x0b, 0x83, 0xa4, 0x1b, 0xb9, 0xe4, 0x05,
	0x9f, 0x28, 0xd6, 0x2b, 0x6a, 0x5d, 0xa1, 0x8c, 0x79, 0x1b, 0x23, 0x61, 0xaf, 0x37, 0xc3, 0x61,
	0x83, 0x57, 0x9d, 0x4c, 0xf8, 0x1f, 0x4d, 0xdc, 0x76, 0x1c, 0xf1, 0x79, 0xfb, 0xa3, 0x91, 0xc0,
	0xd1, 0x13, 0x25, 0x7f, 0x0e, 0x91, 0x1a, 0x6a, 0x8d, 0x76, 0x2d, 0xb7, 0xe8, 0xd7, 0x72, 0x8b,
	0x79, 0x0d, 0x8f, 0xdd, 0xc6, 0x94, 0xc6, 0xae, 0x6d, 0x50, 0x8b, 0xb7, 0xb0, 0x74, 0x9f, 0x90,
	0xf3, 0xd2, 0xb3, 0xd5, 0xb4, 0x73, 0x9f, 0xea, 0x13, 0x7e, 0x3b, 0x50, 0xf8, 0xff, 0x03, 0x7d,
	0x80, 0xd4, 0xb5, 0xb0, 0x93, 0x8a, 0x77, 0x10, 0xbb, 0x46, 0xe3, 0x17, 0xfa, 0xdb, 0x53, 0x53,
	0x46, 0xfe, 0x1a, 0x1e, 0x5e, 0x98, 0xbd, 0xae, 0xbe, 0xd6, 0xe5, 0xb1, 0xb6, 0xe5, 0x7f, 0x7c,
	0xe6, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0xfe, 0xe0, 0x00, 0xb8, 0x03, 0x00, 0x00,
}
