// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spirc.proto

package spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_kMessageTypeHello          MessageType = 1
	MessageType_kMessageTypeGoodbye        MessageType = 2
	MessageType_kMessageTypeProbe          MessageType = 3
	MessageType_kMessageTypeNotify         MessageType = 10
	MessageType_kMessageTypeLoad           MessageType = 20
	MessageType_kMessageTypePlay           MessageType = 21
	MessageType_kMessageTypePause          MessageType = 22
	MessageType_kMessageTypePlayPause      MessageType = 23
	MessageType_kMessageTypeSeek           MessageType = 24
	MessageType_kMessageTypePrev           MessageType = 25
	MessageType_kMessageTypeNext           MessageType = 26
	MessageType_kMessageTypeVolume         MessageType = 27
	MessageType_kMessageTypeShuffle        MessageType = 28
	MessageType_kMessageTypeRepeat         MessageType = 29
	MessageType_kMessageTypeVolumeDown     MessageType = 31
	MessageType_kMessageTypeVolumeUp       MessageType = 32
	MessageType_kMessageTypeReplace        MessageType = 33
	MessageType_kMessageTypeLogout         MessageType = 34
	MessageType_kMessageTypeAction         MessageType = 35
	MessageType_kMessageTypeRename         MessageType = 36
	MessageType_kMessageTypeUpdateMetadata MessageType = 128
)

var MessageType_name = map[int32]string{
	1:   "kMessageTypeHello",
	2:   "kMessageTypeGoodbye",
	3:   "kMessageTypeProbe",
	10:  "kMessageTypeNotify",
	20:  "kMessageTypeLoad",
	21:  "kMessageTypePlay",
	22:  "kMessageTypePause",
	23:  "kMessageTypePlayPause",
	24:  "kMessageTypeSeek",
	25:  "kMessageTypePrev",
	26:  "kMessageTypeNext",
	27:  "kMessageTypeVolume",
	28:  "kMessageTypeShuffle",
	29:  "kMessageTypeRepeat",
	31:  "kMessageTypeVolumeDown",
	32:  "kMessageTypeVolumeUp",
	33:  "kMessageTypeReplace",
	34:  "kMessageTypeLogout",
	35:  "kMessageTypeAction",
	36:  "kMessageTypeRename",
	128: "kMessageTypeUpdateMetadata",
}

var MessageType_value = map[string]int32{
	"kMessageTypeHello":          1,
	"kMessageTypeGoodbye":        2,
	"kMessageTypeProbe":          3,
	"kMessageTypeNotify":         10,
	"kMessageTypeLoad":           20,
	"kMessageTypePlay":           21,
	"kMessageTypePause":          22,
	"kMessageTypePlayPause":      23,
	"kMessageTypeSeek":           24,
	"kMessageTypePrev":           25,
	"kMessageTypeNext":           26,
	"kMessageTypeVolume":         27,
	"kMessageTypeShuffle":        28,
	"kMessageTypeRepeat":         29,
	"kMessageTypeVolumeDown":     31,
	"kMessageTypeVolumeUp":       32,
	"kMessageTypeReplace":        33,
	"kMessageTypeLogout":         34,
	"kMessageTypeAction":         35,
	"kMessageTypeRename":         36,
	"kMessageTypeUpdateMetadata": 128,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{0}
}

type CapabilityType int32

const (
	CapabilityType_kSupportedContexts  CapabilityType = 1
	CapabilityType_kCanBePlayer        CapabilityType = 2
	CapabilityType_kRestrictToLocal    CapabilityType = 3
	CapabilityType_kDeviceType         CapabilityType = 4
	CapabilityType_kGaiaEqConnectId    CapabilityType = 5
	CapabilityType_kSupportsLogout     CapabilityType = 6
	CapabilityType_kIsObservable       CapabilityType = 7
	CapabilityType_kVolumeSteps        CapabilityType = 8
	CapabilityType_kSupportedTypes     CapabilityType = 9
	CapabilityType_kCommandAcks        CapabilityType = 10
	CapabilityType_kSupportsRename     CapabilityType = 11
	CapabilityType_kHidden             CapabilityType = 12
	CapabilityType_kSupportsPlaylistV2 CapabilityType = 13
	CapabilityType_kUnknown            CapabilityType = 14
)

var CapabilityType_name = map[int32]string{
	1:  "kSupportedContexts",
	2:  "kCanBePlayer",
	3:  "kRestrictToLocal",
	4:  "kDeviceType",
	5:  "kGaiaEqConnectId",
	6:  "kSupportsLogout",
	7:  "kIsObservable",
	8:  "kVolumeSteps",
	9:  "kSupportedTypes",
	10: "kCommandAcks",
	11: "kSupportsRename",
	12: "kHidden",
	13: "kSupportsPlaylistV2",
	14: "kUnknown",
}

var CapabilityType_value = map[string]int32{
	"kSupportedContexts":  1,
	"kCanBePlayer":        2,
	"kRestrictToLocal":    3,
	"kDeviceType":         4,
	"kGaiaEqConnectId":    5,
	"kSupportsLogout":     6,
	"kIsObservable":       7,
	"kVolumeSteps":        8,
	"kSupportedTypes":     9,
	"kCommandAcks":        10,
	"kSupportsRename":     11,
	"kHidden":             12,
	"kSupportsPlaylistV2": 13,
	"kUnknown":            14,
}

func (x CapabilityType) Enum() *CapabilityType {
	p := new(CapabilityType)
	*p = x
	return p
}

func (x CapabilityType) String() string {
	return proto.EnumName(CapabilityType_name, int32(x))
}

func (x *CapabilityType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CapabilityType_value, data, "CapabilityType")
	if err != nil {
		return err
	}
	*x = CapabilityType(value)
	return nil
}

func (CapabilityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{1}
}

type PlayStatus int32

const (
	PlayStatus_kPlayStatusStop    PlayStatus = 0
	PlayStatus_kPlayStatusPlay    PlayStatus = 1
	PlayStatus_kPlayStatusPause   PlayStatus = 2
	PlayStatus_kPlayStatusLoading PlayStatus = 3
)

var PlayStatus_name = map[int32]string{
	0: "kPlayStatusStop",
	1: "kPlayStatusPlay",
	2: "kPlayStatusPause",
	3: "kPlayStatusLoading",
}

var PlayStatus_value = map[string]int32{
	"kPlayStatusStop":    0,
	"kPlayStatusPlay":    1,
	"kPlayStatusPause":   2,
	"kPlayStatusLoading": 3,
}

func (x PlayStatus) Enum() *PlayStatus {
	p := new(PlayStatus)
	*p = x
	return p
}

func (x PlayStatus) String() string {
	return proto.EnumName(PlayStatus_name, int32(x))
}

func (x *PlayStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlayStatus_value, data, "PlayStatus")
	if err != nil {
		return err
	}
	*x = PlayStatus(value)
	return nil
}

func (PlayStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{2}
}

type Frame struct {
	Version              *uint32      `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ident                *string      `protobuf:"bytes,2,opt,name=ident" json:"ident,omitempty"`
	ProtocolVersion      *string      `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	SeqNr                *uint32      `protobuf:"varint,4,opt,name=seq_nr,json=seqNr" json:"seq_nr,omitempty"`
	Typ                  *MessageType `protobuf:"varint,5,opt,name=typ,enum=spotify.MessageType" json:"typ,omitempty"`
	DeviceState          *DeviceState `protobuf:"bytes,7,opt,name=device_state,json=deviceState" json:"device_state,omitempty"`
	Goodbye              *Goodbye     `protobuf:"bytes,11,opt,name=goodbye" json:"goodbye,omitempty"`
	State                *State       `protobuf:"bytes,12,opt,name=state" json:"state,omitempty"`
	Position             *uint32      `protobuf:"varint,13,opt,name=position" json:"position,omitempty"`
	Volume               *uint32      `protobuf:"varint,14,opt,name=volume" json:"volume,omitempty"`
	StateUpdateId        *int64       `protobuf:"varint,17,opt,name=state_update_id,json=stateUpdateId" json:"state_update_id,omitempty"`
	Recipient            []string     `protobuf:"bytes,18,rep,name=recipient" json:"recipient,omitempty"`
	ContextPlayerState   []byte       `protobuf:"bytes,19,opt,name=context_player_state,json=contextPlayerState" json:"context_player_state,omitempty"`
	NewName              *string      `protobuf:"bytes,20,opt,name=new_name,json=newName" json:"new_name,omitempty"`
	Metadata             *Metadata    `protobuf:"bytes,25,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{0}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Frame) GetIdent() string {
	if m != nil && m.Ident != nil {
		return *m.Ident
	}
	return ""
}

func (m *Frame) GetProtocolVersion() string {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return ""
}

func (m *Frame) GetSeqNr() uint32 {
	if m != nil && m.SeqNr != nil {
		return *m.SeqNr
	}
	return 0
}

func (m *Frame) GetTyp() MessageType {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return MessageType_kMessageTypeHello
}

func (m *Frame) GetDeviceState() *DeviceState {
	if m != nil {
		return m.DeviceState
	}
	return nil
}

func (m *Frame) GetGoodbye() *Goodbye {
	if m != nil {
		return m.Goodbye
	}
	return nil
}

func (m *Frame) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Frame) GetPosition() uint32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *Frame) GetVolume() uint32 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *Frame) GetStateUpdateId() int64 {
	if m != nil && m.StateUpdateId != nil {
		return *m.StateUpdateId
	}
	return 0
}

func (m *Frame) GetRecipient() []string {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *Frame) GetContextPlayerState() []byte {
	if m != nil {
		return m.ContextPlayerState
	}
	return nil
}

func (m *Frame) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

func (m *Frame) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type DeviceState struct {
	SwVersion            *string       `protobuf:"bytes,1,opt,name=sw_version,json=swVersion" json:"sw_version,omitempty"`
	IsActive             *bool         `protobuf:"varint,10,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	CanPlay              *bool         `protobuf:"varint,11,opt,name=can_play,json=canPlay" json:"can_play,omitempty"`
	Volume               *uint32       `protobuf:"varint,12,opt,name=volume" json:"volume,omitempty"`
	Name                 *string       `protobuf:"bytes,13,opt,name=name" json:"name,omitempty"`
	ErrorCode            *uint32       `protobuf:"varint,14,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	BecameActiveAt       *int64        `protobuf:"varint,15,opt,name=became_active_at,json=becameActiveAt" json:"became_active_at,omitempty"`
	ErrorMessage         *string       `protobuf:"bytes,16,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	Capabilities         []*Capability `protobuf:"bytes,17,rep,name=capabilities" json:"capabilities,omitempty"`
	ContextPlayerError   *string       `protobuf:"bytes,20,opt,name=context_player_error,json=contextPlayerError" json:"context_player_error,omitempty"`
	Metadata             []*Metadata   `protobuf:"bytes,25,rep,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceState) Reset()         { *m = DeviceState{} }
func (m *DeviceState) String() string { return proto.CompactTextString(m) }
func (*DeviceState) ProtoMessage()    {}
func (*DeviceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{1}
}

func (m *DeviceState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceState.Unmarshal(m, b)
}
func (m *DeviceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceState.Marshal(b, m, deterministic)
}
func (m *DeviceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceState.Merge(m, src)
}
func (m *DeviceState) XXX_Size() int {
	return xxx_messageInfo_DeviceState.Size(m)
}
func (m *DeviceState) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceState.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceState proto.InternalMessageInfo

func (m *DeviceState) GetSwVersion() string {
	if m != nil && m.SwVersion != nil {
		return *m.SwVersion
	}
	return ""
}

func (m *DeviceState) GetIsActive() bool {
	if m != nil && m.IsActive != nil {
		return *m.IsActive
	}
	return false
}

func (m *DeviceState) GetCanPlay() bool {
	if m != nil && m.CanPlay != nil {
		return *m.CanPlay
	}
	return false
}

func (m *DeviceState) GetVolume() uint32 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *DeviceState) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DeviceState) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *DeviceState) GetBecameActiveAt() int64 {
	if m != nil && m.BecameActiveAt != nil {
		return *m.BecameActiveAt
	}
	return 0
}

func (m *DeviceState) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *DeviceState) GetCapabilities() []*Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *DeviceState) GetContextPlayerError() string {
	if m != nil && m.ContextPlayerError != nil {
		return *m.ContextPlayerError
	}
	return ""
}

func (m *DeviceState) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Capability struct {
	Typ                  *CapabilityType `protobuf:"varint,1,opt,name=typ,enum=spotify.CapabilityType" json:"typ,omitempty"`
	IntValue             []int64         `protobuf:"varint,2,rep,name=intValue" json:"intValue,omitempty"`
	StringValue          []string        `protobuf:"bytes,3,rep,name=stringValue" json:"stringValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Capability) Reset()         { *m = Capability{} }
func (m *Capability) String() string { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()    {}
func (*Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{2}
}

func (m *Capability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capability.Unmarshal(m, b)
}
func (m *Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capability.Marshal(b, m, deterministic)
}
func (m *Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capability.Merge(m, src)
}
func (m *Capability) XXX_Size() int {
	return xxx_messageInfo_Capability.Size(m)
}
func (m *Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_Capability proto.InternalMessageInfo

func (m *Capability) GetTyp() CapabilityType {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return CapabilityType_kSupportedContexts
}

func (m *Capability) GetIntValue() []int64 {
	if m != nil {
		return m.IntValue
	}
	return nil
}

func (m *Capability) GetStringValue() []string {
	if m != nil {
		return m.StringValue
	}
	return nil
}

type Goodbye struct {
	Reason               *string  `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Goodbye) Reset()         { *m = Goodbye{} }
func (m *Goodbye) String() string { return proto.CompactTextString(m) }
func (*Goodbye) ProtoMessage()    {}
func (*Goodbye) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{3}
}

func (m *Goodbye) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goodbye.Unmarshal(m, b)
}
func (m *Goodbye) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goodbye.Marshal(b, m, deterministic)
}
func (m *Goodbye) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goodbye.Merge(m, src)
}
func (m *Goodbye) XXX_Size() int {
	return xxx_messageInfo_Goodbye.Size(m)
}
func (m *Goodbye) XXX_DiscardUnknown() {
	xxx_messageInfo_Goodbye.DiscardUnknown(m)
}

var xxx_messageInfo_Goodbye proto.InternalMessageInfo

func (m *Goodbye) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type State struct {
	ContextUri           *string     `protobuf:"bytes,2,opt,name=context_uri,json=contextUri" json:"context_uri,omitempty"`
	Index                *uint32     `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	PositionMs           *uint32     `protobuf:"varint,4,opt,name=position_ms,json=positionMs" json:"position_ms,omitempty"`
	Status               *PlayStatus `protobuf:"varint,5,opt,name=status,enum=spotify.PlayStatus" json:"status,omitempty"`
	PositionMeasuredAt   *uint64     `protobuf:"varint,7,opt,name=position_measured_at,json=positionMeasuredAt" json:"position_measured_at,omitempty"`
	ContextDescription   *string     `protobuf:"bytes,8,opt,name=context_description,json=contextDescription" json:"context_description,omitempty"`
	Shuffle              *bool       `protobuf:"varint,13,opt,name=shuffle" json:"shuffle,omitempty"`
	Repeat               *bool       `protobuf:"varint,14,opt,name=repeat" json:"repeat,omitempty"`
	LastCommandIdent     *string     `protobuf:"bytes,20,opt,name=last_command_ident,json=lastCommandIdent" json:"last_command_ident,omitempty"`
	LastCommandMsgid     *uint32     `protobuf:"varint,21,opt,name=last_command_msgid,json=lastCommandMsgid" json:"last_command_msgid,omitempty"`
	PlayingFromFallback  *bool       `protobuf:"varint,24,opt,name=playing_from_fallback,json=playingFromFallback" json:"playing_from_fallback,omitempty"`
	Row                  *uint32     `protobuf:"varint,25,opt,name=row" json:"row,omitempty"`
	PlayingTrackIndex    *uint32     `protobuf:"varint,26,opt,name=playing_track_index,json=playingTrackIndex" json:"playing_track_index,omitempty"`
	Track                []*TrackRef `protobuf:"bytes,27,rep,name=track" json:"track,omitempty"`
	Ad                   *Ad         `protobuf:"bytes,28,opt,name=ad" json:"ad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{4}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetContextUri() string {
	if m != nil && m.ContextUri != nil {
		return *m.ContextUri
	}
	return ""
}

func (m *State) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *State) GetPositionMs() uint32 {
	if m != nil && m.PositionMs != nil {
		return *m.PositionMs
	}
	return 0
}

func (m *State) GetStatus() PlayStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return PlayStatus_kPlayStatusStop
}

func (m *State) GetPositionMeasuredAt() uint64 {
	if m != nil && m.PositionMeasuredAt != nil {
		return *m.PositionMeasuredAt
	}
	return 0
}

func (m *State) GetContextDescription() string {
	if m != nil && m.ContextDescription != nil {
		return *m.ContextDescription
	}
	return ""
}

func (m *State) GetShuffle() bool {
	if m != nil && m.Shuffle != nil {
		return *m.Shuffle
	}
	return false
}

func (m *State) GetRepeat() bool {
	if m != nil && m.Repeat != nil {
		return *m.Repeat
	}
	return false
}

func (m *State) GetLastCommandIdent() string {
	if m != nil && m.LastCommandIdent != nil {
		return *m.LastCommandIdent
	}
	return ""
}

func (m *State) GetLastCommandMsgid() uint32 {
	if m != nil && m.LastCommandMsgid != nil {
		return *m.LastCommandMsgid
	}
	return 0
}

func (m *State) GetPlayingFromFallback() bool {
	if m != nil && m.PlayingFromFallback != nil {
		return *m.PlayingFromFallback
	}
	return false
}

func (m *State) GetRow() uint32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

func (m *State) GetPlayingTrackIndex() uint32 {
	if m != nil && m.PlayingTrackIndex != nil {
		return *m.PlayingTrackIndex
	}
	return 0
}

func (m *State) GetTrack() []*TrackRef {
	if m != nil {
		return m.Track
	}
	return nil
}

func (m *State) GetAd() *Ad {
	if m != nil {
		return m.Ad
	}
	return nil
}

type TrackRef struct {
	Gid                  []byte   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Uri                  *string  `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
	Queued               *bool    `protobuf:"varint,3,opt,name=queued" json:"queued,omitempty"`
	Context              *string  `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackRef) Reset()         { *m = TrackRef{} }
func (m *TrackRef) String() string { return proto.CompactTextString(m) }
func (*TrackRef) ProtoMessage()    {}
func (*TrackRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{5}
}

func (m *TrackRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackRef.Unmarshal(m, b)
}
func (m *TrackRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackRef.Marshal(b, m, deterministic)
}
func (m *TrackRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackRef.Merge(m, src)
}
func (m *TrackRef) XXX_Size() int {
	return xxx_messageInfo_TrackRef.Size(m)
}
func (m *TrackRef) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackRef.DiscardUnknown(m)
}

var xxx_messageInfo_TrackRef proto.InternalMessageInfo

func (m *TrackRef) GetGid() []byte {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *TrackRef) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *TrackRef) GetQueued() bool {
	if m != nil && m.Queued != nil {
		return *m.Queued
	}
	return false
}

func (m *TrackRef) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

type Ad struct {
	Next                 *int32   `protobuf:"varint,1,opt,name=next" json:"next,omitempty"`
	OggFid               []byte   `protobuf:"bytes,2,opt,name=ogg_fid,json=oggFid" json:"ogg_fid,omitempty"`
	ImageFid             []byte   `protobuf:"bytes,3,opt,name=image_fid,json=imageFid" json:"image_fid,omitempty"`
	Duration             *int32   `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	ClickUrl             *string  `protobuf:"bytes,5,opt,name=click_url,json=clickUrl" json:"click_url,omitempty"`
	ImpressionUrl        *string  `protobuf:"bytes,6,opt,name=impression_url,json=impressionUrl" json:"impression_url,omitempty"`
	Product              *string  `protobuf:"bytes,7,opt,name=product" json:"product,omitempty"`
	Advertiser           *string  `protobuf:"bytes,8,opt,name=advertiser" json:"advertiser,omitempty"`
	Gid                  []byte   `protobuf:"bytes,9,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{6}
}

func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (m *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(m, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetNext() int32 {
	if m != nil && m.Next != nil {
		return *m.Next
	}
	return 0
}

func (m *Ad) GetOggFid() []byte {
	if m != nil {
		return m.OggFid
	}
	return nil
}

func (m *Ad) GetImageFid() []byte {
	if m != nil {
		return m.ImageFid
	}
	return nil
}

func (m *Ad) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *Ad) GetClickUrl() string {
	if m != nil && m.ClickUrl != nil {
		return *m.ClickUrl
	}
	return ""
}

func (m *Ad) GetImpressionUrl() string {
	if m != nil && m.ImpressionUrl != nil {
		return *m.ImpressionUrl
	}
	return ""
}

func (m *Ad) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *Ad) GetAdvertiser() string {
	if m != nil && m.Advertiser != nil {
		return *m.Advertiser
	}
	return ""
}

func (m *Ad) GetGid() []byte {
	if m != nil {
		return m.Gid
	}
	return nil
}

type Metadata struct {
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Metadata             *string  `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc74b820ae77976, []int{7}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Metadata) GetMetadata() string {
	if m != nil && m.Metadata != nil {
		return *m.Metadata
	}
	return ""
}

func init() {
	proto.RegisterEnum("spotify.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("spotify.CapabilityType", CapabilityType_name, CapabilityType_value)
	proto.RegisterEnum("spotify.PlayStatus", PlayStatus_name, PlayStatus_value)
	proto.RegisterType((*Frame)(nil), "spotify.Frame")
	proto.RegisterType((*DeviceState)(nil), "spotify.DeviceState")
	proto.RegisterType((*Capability)(nil), "spotify.Capability")
	proto.RegisterType((*Goodbye)(nil), "spotify.Goodbye")
	proto.RegisterType((*State)(nil), "spotify.State")
	proto.RegisterType((*TrackRef)(nil), "spotify.TrackRef")
	proto.RegisterType((*Ad)(nil), "spotify.Ad")
	proto.RegisterType((*Metadata)(nil), "spotify.Metadata")
}

func init() { proto.RegisterFile("spirc.proto", fileDescriptor_1dc74b820ae77976) }

var fileDescriptor_1dc74b820ae77976 = []byte{
	// 1417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xcd, 0x72, 0xdb, 0x36,
	0x10, 0xae, 0xfe, 0x2c, 0x6a, 0x25, 0xd9, 0x30, 0xfc, 0x47, 0xdb, 0x49, 0xa3, 0x28, 0x69, 0xaa,
	0xb8, 0xad, 0xdb, 0xf1, 0xa5, 0x33, 0xbd, 0xb9, 0x4e, 0x9c, 0x78, 0x26, 0x71, 0x33, 0x70, 0xec,
	0x2b, 0x0b, 0x13, 0xb0, 0xca, 0x11, 0x45, 0xd0, 0x00, 0x69, 0xc7, 0xb7, 0xbe, 0x40, 0xef, 0xbd,
	0xb6, 0x6f, 0xd1, 0x57, 0xeb, 0xa9, 0x83, 0x05, 0x29, 0xd1, 0x72, 0x66, 0x7a, 0x12, 0xf7, 0xfb,
	0x16, 0x8b, 0xc5, 0xee, 0x87, 0x85, 0xa0, 0x6b, 0xd2, 0x48, 0x87, 0xfb, 0xa9, 0x56, 0x99, 0xa2,
	0x6d, 0x93, 0xaa, 0x2c, 0xba, 0xba, 0x1b, 0xfe, 0xdd, 0x84, 0xd6, 0xb1, 0xe6, 0x53, 0x49, 0x7d,
	0x68, 0xdf, 0x48, 0x6d, 0x22, 0x95, 0xf8, 0xb5, 0x41, 0x6d, 0xd4, 0x67, 0xa5, 0x49, 0xd7, 0xa1,
	0x15, 0x09, 0x99, 0x64, 0x7e, 0x7d, 0x50, 0x1b, 0x75, 0x98, 0x33, 0xe8, 0x4b, 0x20, 0x18, 0x2b,
	0x54, 0x71, 0x50, 0x2e, 0x6c, 0xa0, 0xc3, 0x4a, 0x89, 0x5f, 0x14, 0x01, 0x36, 0x60, 0xc9, 0xc8,
	0xeb, 0x20, 0xd1, 0x7e, 0x13, 0x23, 0xb7, 0x8c, 0xbc, 0x3e, 0xd5, 0xf4, 0x05, 0x34, 0xb2, 0xbb,
	0xd4, 0x6f, 0x0d, 0x6a, 0xa3, 0xe5, 0x83, 0xf5, 0xfd, 0x22, 0xa5, 0xfd, 0xf7, 0xd2, 0x18, 0x3e,
	0x96, 0x1f, 0xef, 0x52, 0xc9, 0xac, 0x03, 0xfd, 0x11, 0x7a, 0x42, 0xde, 0x44, 0xa1, 0x0c, 0x4c,
	0xc6, 0x33, 0xe9, 0xb7, 0x07, 0xb5, 0x51, 0xb7, 0xb2, 0xe0, 0x15, 0x92, 0x67, 0x96, 0x63, 0x5d,
	0x31, 0x37, 0xe8, 0x1e, 0xb4, 0xc7, 0x4a, 0x89, 0xcb, 0x3b, 0xe9, 0x77, 0x71, 0x0d, 0x99, 0xad,
	0x79, 0xe3, 0x70, 0x56, 0x3a, 0xd0, 0xe7, 0xd0, 0x72, 0xd1, 0x7b, 0xe8, 0xb9, 0x3c, 0xf3, 0x74,
	0x71, 0x1d, 0x49, 0x77, 0xc0, 0x4b, 0x95, 0x89, 0x32, 0x7b, 0xd8, 0x3e, 0x9e, 0x65, 0x66, 0xd3,
	0x4d, 0x58, 0xba, 0x51, 0x71, 0x3e, 0x95, 0xfe, 0x32, 0x32, 0x85, 0x45, 0x5f, 0xc0, 0x0a, 0x2e,
	0x0e, 0xf2, 0x54, 0xd8, 0x9f, 0x48, 0xf8, 0xab, 0x83, 0xda, 0xa8, 0xc1, 0xfa, 0x08, 0x9f, 0x23,
	0x7a, 0x22, 0xe8, 0x23, 0xe8, 0x68, 0x19, 0x46, 0x69, 0x64, 0x4b, 0x4d, 0x07, 0x8d, 0x51, 0x87,
	0xcd, 0x01, 0xfa, 0x03, 0xac, 0x87, 0x2a, 0xc9, 0xe4, 0xa7, 0x2c, 0x48, 0x63, 0x7e, 0x27, 0x75,
	0x51, 0x8c, 0xb5, 0x41, 0x6d, 0xd4, 0x63, 0xb4, 0xe0, 0x3e, 0x20, 0xe5, 0x4e, 0xbf, 0x0d, 0x5e,
	0x22, 0x6f, 0x83, 0x84, 0x4f, 0xa5, 0xbf, 0x8e, 0x8d, 0x69, 0x27, 0xf2, 0xf6, 0xd4, 0xf6, 0xfa,
	0x3b, 0xf0, 0xa6, 0x32, 0xe3, 0x82, 0x67, 0xdc, 0xdf, 0xc6, 0xf3, 0xae, 0x56, 0xca, 0xef, 0x08,
	0x36, 0x73, 0x19, 0xfe, 0xd9, 0x80, 0x6e, 0xa5, 0xc8, 0xf4, 0x31, 0x80, 0xb9, 0x0d, 0xaa, 0x6a,
	0xe9, 0xb0, 0x8e, 0xb9, 0x2d, 0xdb, 0xbd, 0x0b, 0x9d, 0xc8, 0x04, 0x3c, 0xcc, 0xa2, 0x1b, 0xe9,
	0xc3, 0xa0, 0x36, 0xf2, 0x98, 0x17, 0x99, 0x43, 0xb4, 0x6d, 0x56, 0x21, 0x4f, 0xf0, 0x0c, 0xd8,
	0x14, 0x8f, 0xb5, 0x43, 0x9e, 0xd8, 0xbc, 0x2b, 0x05, 0xec, 0xdd, 0x2b, 0x20, 0x85, 0x26, 0x1e,
	0xa2, 0x8f, 0x1b, 0xe1, 0xb7, 0x4d, 0x41, 0x6a, 0xad, 0x74, 0x10, 0x2a, 0x51, 0x16, 0xbc, 0x83,
	0xc8, 0x91, 0x12, 0x92, 0x8e, 0x80, 0x5c, 0xca, 0x90, 0x4f, 0x65, 0x91, 0x46, 0xc0, 0x33, 0x7f,
	0x05, 0x8b, 0xbe, 0xec, 0x70, 0x97, 0xcd, 0x61, 0x46, 0x9f, 0x41, 0xdf, 0x05, 0x9a, 0x3a, 0xd9,
	0xf9, 0x04, 0x77, 0xe9, 0x21, 0x58, 0x48, 0xd1, 0x2a, 0x30, 0xe4, 0x29, 0xbf, 0x8c, 0xe2, 0x28,
	0x8b, 0xa4, 0xf1, 0x57, 0x07, 0x8d, 0x51, 0xf7, 0x60, 0x6d, 0x56, 0xb3, 0xa3, 0x92, 0xbc, 0x63,
	0xf7, 0x1c, 0x3f, 0xd3, 0x35, 0x8c, 0x5b, 0xf4, 0xe3, 0x7e, 0xd7, 0x5e, 0x5b, 0x66, 0xa1, 0x35,
	0x8d, 0xff, 0x6b, 0x4d, 0x0e, 0x30, 0xdf, 0x9c, 0xbe, 0x74, 0x37, 0xaa, 0x86, 0x37, 0x6a, 0xeb,
	0x33, 0xe9, 0xcd, 0x2f, 0xd5, 0x0e, 0x78, 0x51, 0x92, 0x5d, 0xf0, 0x38, 0x97, 0x7e, 0x7d, 0xd0,
	0x18, 0x35, 0xd8, 0xcc, 0xa6, 0x03, 0xe8, 0x9a, 0x4c, 0x47, 0xc9, 0xd8, 0xd1, 0x0d, 0xd4, 0x62,
	0x15, 0x1a, 0x3e, 0x85, 0x76, 0x71, 0x83, 0x6c, 0xd7, 0xb4, 0xe4, 0x66, 0x26, 0x84, 0xc2, 0x1a,
	0xfe, 0xd3, 0x84, 0x96, 0x93, 0xcb, 0x13, 0xe8, 0x96, 0x45, 0xc8, 0x75, 0x54, 0x4c, 0x11, 0x28,
	0xa0, 0x73, 0x1d, 0xe1, 0x80, 0x49, 0x84, 0xfc, 0x84, 0xf3, 0xa3, 0xcf, 0x9c, 0x61, 0x97, 0x95,
	0x77, 0x2b, 0x98, 0x9a, 0x62, 0x74, 0x40, 0x09, 0xbd, 0x37, 0xf4, 0x1b, 0x58, 0xb2, 0x77, 0x20,
	0x37, 0xc5, 0x08, 0x99, 0xf7, 0xc3, 0x16, 0xf4, 0x0c, 0x29, 0x56, 0xb8, 0xd8, 0x4e, 0xcc, 0xa3,
	0x49, 0x6e, 0x72, 0x2d, 0x85, 0x55, 0x85, 0x1d, 0x26, 0x4d, 0x46, 0x67, 0x61, 0x0b, 0xea, 0x30,
	0xa3, 0xdf, 0xc3, 0x5a, 0x99, 0xb6, 0x90, 0x26, 0xd4, 0x51, 0x8a, 0xd7, 0xde, 0xbb, 0xd7, 0xba,
	0x57, 0x73, 0xc6, 0x4e, 0x50, 0xf3, 0x5b, 0x7e, 0x75, 0x15, 0x3b, 0xa9, 0x7a, 0xac, 0x34, 0x5d,
	0x8d, 0x52, 0xc9, 0x33, 0x54, 0xaa, 0xc7, 0x0a, 0x8b, 0x7e, 0x0b, 0x34, 0xe6, 0x26, 0x0b, 0x42,
	0x35, 0x9d, 0xf2, 0x44, 0x04, 0x6e, 0xcc, 0x3a, 0x71, 0x10, 0xcb, 0x1c, 0x39, 0xe2, 0x04, 0x27,
	0xee, 0xa2, 0xf7, 0xd4, 0x8c, 0x23, 0xe1, 0x6f, 0x60, 0x5d, 0xaa, 0xde, 0xef, 0x2d, 0x4e, 0x0f,
	0x60, 0xc3, 0x4a, 0x2e, 0x4a, 0xc6, 0xc1, 0x95, 0x56, 0xd3, 0xe0, 0x8a, 0xc7, 0xf1, 0x25, 0x0f,
	0x27, 0xbe, 0x8f, 0x29, 0xac, 0x15, 0xe4, 0xb1, 0x56, 0xd3, 0xe3, 0x82, 0xa2, 0x04, 0x1a, 0x5a,
	0xdd, 0xe2, 0x48, 0xe8, 0x33, 0xfb, 0x49, 0xf7, 0xa1, 0x74, 0x0c, 0x32, 0xcd, 0xc3, 0x49, 0xe0,
	0x1a, 0xb5, 0x83, 0x1e, 0xab, 0x05, 0xf5, 0xd1, 0x32, 0x27, 0xd8, 0xb4, 0xaf, 0xa1, 0x85, 0x7e,
	0xfe, 0xee, 0x82, 0x76, 0xd1, 0x87, 0xc9, 0x2b, 0xe6, 0x78, 0xba, 0x0b, 0x75, 0x2e, 0xfc, 0x47,
	0x38, 0x7c, 0xba, 0x33, 0xaf, 0x43, 0xc1, 0xea, 0x5c, 0x0c, 0x7f, 0x05, 0xaf, 0xf4, 0xb7, 0x39,
	0xd9, 0x63, 0xd6, 0x70, 0xce, 0xd9, 0x4f, 0x8b, 0xcc, 0x75, 0x64, 0x3f, 0x6d, 0x7d, 0xaf, 0x73,
	0x99, 0x4b, 0x81, 0x0a, 0xf2, 0x58, 0x61, 0xd9, 0x8e, 0x14, 0x7d, 0x42, 0xf9, 0x74, 0x58, 0x69,
	0x0e, 0xff, 0xad, 0x41, 0xfd, 0x50, 0xe0, 0x68, 0xb1, 0xac, 0x8d, 0xde, 0x62, 0xf8, 0x4d, 0xb7,
	0xa0, 0xad, 0xc6, 0xe3, 0xe0, 0x2a, 0x12, 0xb8, 0x45, 0x8f, 0x2d, 0xa9, 0xf1, 0xf8, 0x38, 0x12,
	0x38, 0xd7, 0xa6, 0x7c, 0x2c, 0x91, 0x6a, 0x20, 0xe5, 0x21, 0x60, 0xc9, 0x1d, 0xf0, 0x44, 0xae,
	0x39, 0x4a, 0xa4, 0x89, 0xd1, 0x66, 0xb6, 0x5d, 0x18, 0xc6, 0x51, 0x38, 0x09, 0x72, 0x1d, 0xa3,
	0x56, 0x3b, 0xcc, 0x43, 0xe0, 0x5c, 0xc7, 0xf4, 0x2b, 0x58, 0x8e, 0xa6, 0xa9, 0x96, 0xc6, 0xce,
	0x4e, 0xf4, 0x58, 0x42, 0x8f, 0xfe, 0x1c, 0xb5, 0x6e, 0x3e, 0xb4, 0x53, 0xad, 0x44, 0x1e, 0x3a,
	0xc9, 0x76, 0x58, 0x69, 0xd2, 0x2f, 0x01, 0xb8, 0xb8, 0x91, 0x3a, 0x8b, 0x8c, 0xd4, 0x85, 0x3c,
	0x2b, 0x48, 0x59, 0xc0, 0xce, 0xac, 0x80, 0xc3, 0x9f, 0xc0, 0x2b, 0x47, 0x89, 0xad, 0x40, 0x76,
	0x97, 0xca, 0xe2, 0xf2, 0xe2, 0xb7, 0x3d, 0xcb, 0x6c, 0x06, 0xb9, 0x2a, 0xcf, 0xec, 0xbd, 0x3f,
	0x9a, 0xd0, 0xad, 0xbc, 0xd0, 0x74, 0x03, 0x56, 0x27, 0x15, 0xfb, 0xad, 0x8c, 0x63, 0x45, 0x6a,
	0x74, 0x0b, 0xd6, 0xaa, 0x70, 0x31, 0x2c, 0x48, 0x7d, 0xd1, 0xff, 0x83, 0x56, 0x97, 0x92, 0x34,
	0xe8, 0x26, 0xd0, 0x2a, 0x7c, 0x8a, 0x72, 0x20, 0x40, 0xd7, 0x81, 0x54, 0xf1, 0x77, 0x8a, 0x0b,
	0xb2, 0xbe, 0x88, 0xda, 0xeb, 0x4e, 0x36, 0x1e, 0x84, 0xe6, 0xb9, 0x91, 0x64, 0x93, 0x6e, 0xc3,
	0xc6, 0xa2, 0xb3, 0xa3, 0xb6, 0x16, 0xe3, 0x9c, 0x49, 0x39, 0x21, 0xfe, 0x83, 0xe8, 0x5a, 0xde,
	0x90, 0xed, 0x45, 0xf4, 0x54, 0x7e, 0xca, 0xc8, 0xce, 0x62, 0xde, 0x17, 0xf8, 0x62, 0x91, 0xdd,
	0xc5, 0xf3, 0x9f, 0xb9, 0x41, 0x40, 0x1e, 0x2d, 0x2e, 0x60, 0x38, 0x08, 0xc8, 0x63, 0xba, 0x03,
	0x9b, 0x0f, 0x03, 0xbd, 0x52, 0xb7, 0x09, 0x79, 0x42, 0x7d, 0x58, 0x7f, 0xc8, 0x9d, 0xa7, 0x64,
	0xb0, 0xb8, 0x0d, 0x93, 0x69, 0xcc, 0x43, 0x49, 0x9e, 0x2e, 0x6e, 0xf3, 0x4e, 0x8d, 0x55, 0x9e,
	0x91, 0xe1, 0x22, 0x6e, 0x9f, 0x41, 0x95, 0x90, 0x67, 0x0f, 0xd3, 0xb2, 0xaf, 0x2c, 0x79, 0x4e,
	0x9f, 0xc0, 0x4e, 0x15, 0x77, 0x7f, 0x56, 0x4a, 0xf1, 0x90, 0xdf, 0x6b, 0x7b, 0x7f, 0xd5, 0x61,
	0xf9, 0xfe, 0xfb, 0x82, 0xb1, 0xce, 0xf2, 0x34, 0x55, 0x3a, 0x93, 0xe2, 0xc8, 0x5d, 0x38, 0x43,
	0x6a, 0x94, 0x40, 0x6f, 0x72, 0xc4, 0x93, 0x9f, 0xa5, 0x7b, 0xef, 0x48, 0x1d, 0x6b, 0xca, 0xa4,
	0x7d, 0x58, 0xc2, 0xec, 0xa3, 0x7a, 0xa7, 0x42, 0x1e, 0x93, 0x06, 0x5d, 0x81, 0xee, 0xc4, 0xfd,
	0xdd, 0xb0, 0xe1, 0x48, 0x13, 0xdd, 0xde, 0xf0, 0x88, 0xbf, 0xbe, 0x3e, 0x52, 0x49, 0x22, 0xc3,
	0xec, 0x44, 0x90, 0x16, 0x5d, 0x83, 0x95, 0x72, 0x1b, 0x53, 0x9c, 0x6f, 0x89, 0xae, 0x42, 0x7f,
	0x72, 0x62, 0x7e, 0xb9, 0x34, 0x52, 0xdf, 0xf0, 0xcb, 0x58, 0x92, 0x36, 0x6e, 0xeb, 0x4a, 0x76,
	0x96, 0xc9, 0xd4, 0x10, 0xaf, 0xba, 0x52, 0x0a, 0xbb, 0x87, 0x21, 0x1d, 0x97, 0x9d, 0x1b, 0xa0,
	0x87, 0xe1, 0xc4, 0x10, 0xb8, 0xb7, 0x41, 0x51, 0x90, 0x2e, 0xed, 0x42, 0x7b, 0xf2, 0x36, 0x12,
	0x42, 0x26, 0xa4, 0x87, 0xe5, 0x2f, 0x3d, 0xec, 0xa1, 0xe2, 0xc8, 0x64, 0x17, 0x07, 0xa4, 0x4f,
	0x7b, 0xe0, 0x4d, 0xce, 0x93, 0x49, 0x62, 0xfb, 0xb7, 0xbc, 0x27, 0x00, 0xe6, 0x2f, 0x12, 0x86,
	0x9d, 0x9b, 0x67, 0x99, 0x4a, 0xc9, 0x17, 0x0b, 0x20, 0x0a, 0xba, 0x86, 0xe7, 0xae, 0x80, 0x28,
	0xda, 0x3a, 0x96, 0x77, 0x8e, 0xda, 0x1b, 0x11, 0x25, 0x63, 0xd2, 0xf8, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x46, 0x7c, 0xc6, 0x1a, 0xe1, 0x0b, 0x00, 0x00,
}
